/* Fishguesser — photo attribution.
 *
 * GENERATED FILE — do not edit by hand.
 * Run `python3 tools/build_credits.py` to rebuild from
 * assets/fish/credits.json. Kept as a plain script (not JSON fetched at
 * runtime) so the game still works when opened straight from disk. */

const PHOTO_CREDITS = {
  "african-butterflyfish": {
    author: "Vassil",
    license: "CC0",
    license_url: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Pantodon_buchholzi_K%C3%B6ln_Zoo_31122014_1.jpg",
  },
  "american-paddlefish": {
    author: "Jon Mortin",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/255918853",
  },
  "angelshark": {
    author: "Julien Renoult",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Squatina_squatina_120867948.jpg",
  },
  "antarctic-cushion-star": {
    author: "Oleksii Vasyliuk",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/134769128",
  },
  "antarctic-krill": {
    author: "Ingvild Riska",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/264532850",
  },
  "antarctic-toothfish": {
    author: "Citron",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Dissostichus_mawsoni.jpg",
  },
  "arapaima": {
    author: "T.Voekler",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Arapaima_gigas_5147.jpg",
  },
  "archerfish": {
    author: "Andrew Parker",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/310996412",
  },
  "arctic-char": {
    author: "Totti",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Salvelinus_alpinus_Kaiyukan.jpg",
  },
  "arctic-grayling": {
    author: "AKSMITH",
    license: "CC BY-SA 2.5",
    license_url: "https://creativecommons.org/licenses/by-sa/2.5",
    source: "https://commons.wikimedia.org/wiki/File:Underwater_Arctic_Grayling.jpg",
  },
  "atlantic-blue-tang": {
    author: "Diego Delso",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Pez_cirujano_azul_(Acanthurus_coeruleus),_Cozumel,_México,_2025-12-20,_DD_75.jpg",
  },
  "atlantic-cod": {
    author: "Wilhelm Thomas Fiege",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Atlantic_Cod,_Atlantischer_Kabeljau_(Gadus_morhua).jpg",
  },
  "atlantic-mackerel": {
    author: "Petar Milošević",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Atlantic_mackerel_(Scomber_scombrus).jpg",
  },
  "atlantic-salmon": {
    author: "Jarvin - Jarle Vines",
    license: "CC BY 3.0",
    license_url: "https://creativecommons.org/licenses/by/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Laks_i_laksetrappa.JPG",
  },
  "atlantic-wolffish": {
    author: "Bjørn Christian Tørrissen",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Anarhichas-lupus-Atlanterhavsparken.jpg",
  },
  "aubrys-flapshell-turtle": {
    author: "Lucy Keith-Diagne",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/66467819",
  },
  "australasian-snapper": {
    author: "Auckland War Memorial Museum",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Pagrus_auratus_(Forster,_1801)_(AM_MA36682-1).jpg",
  },
  "australian-lungfish": {
    author: "タウナギ",
    license: "CC0",
    license_url: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Neoceratodus_forsteri_Nagoya1.jpg",
  },
  "ayu": {
    author: "タウナギ",
    license: "CC0",
    license_url: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Plecoglossus_altivelis_Totto.jpg",
  },
  "bala-shark": {
    author: "Martyn Drabik-Hamshare",
    license: "CC0",
    license_url: "https://creativecommons.org/publicdomain/zero/1.0/",
    source: "https://www.inaturalist.org/observations/180968053",
  },
  "ballan-wrasse": {
    author: "Julien Renoult",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/34802668",
  },
  "banded-leporinus": {
    author: "Andrew J. Crawford",
    license: "CC0",
    license_url: "https://creativecommons.org/publicdomain/zero/1.0/",
    source: "https://www.inaturalist.org/observations/111130147",
  },
  "banded-wrasse": {
    author: "Luca Davenport-Thomas",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/106113650",
  },
  "banggai-cardinalfish": {
    author: "Holger Krisp",
    license: "CC BY 3.0",
    license_url: "https://creativecommons.org/licenses/by/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Banggai-Kardinalbarsch_Pterapogon_kauderni.jpg",
  },
  "barramundi": {
    author: "Mitch Ames",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Lates_calcarifer,_2014-09-19a.jpg",
  },
  "barred-knifejaw": {
    author: "Nicola Crockford",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/254047520",
  },
  "barrier-reef-anemonefish": {
    author: "Leonard Low from Australia",
    license: "CC BY 2.0",
    license_url: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Amphiprion_akindynos.jpg",
  },
  "basking-shark": {
    author: "Green Fire Productions",
    license: "CC BY 2.0",
    license_url: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Cetorhinus_maximus_atlantic.jpg",
  },
  "bat-ray": {
    author: "Claire Fackler, CINMS, NOAA",
    license: "Public domain",
    license_url: "",
    source: "https://commons.wikimedia.org/wiki/File:Myliobatis_californica_channel_islands.jpg",
  },
  "beluga-whale": {
    author: "Antony Stanley",
    license: "CC BY-SA 2.0",
    license_url: "https://creativecommons.org/licenses/by-sa/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Beluga_Whale_(Underwater),_Vancouver_Aquarium_(319841848).jpg",
  },
  "black-rockcod": {
    author: "Sarka Masova",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/45839264",
  },
  "blackfin-icefish": {
    author: "Ambiederman",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:C._aceratus.jpg",
  },
  "blacktip-reef-shark": {
    author: "陳德範（Chen, De-Fan）",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/259913283",
  },
  "blue-cod": {
    author: "André Richard Chalmers",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Blue_Cod_in_Milford_Sound.jpg",
  },
  "blue-land-crab": {
    author: "Krzysztof Ziarnek, Kenraiz",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Cardisoma_guanhumi_kz01.jpg",
  },
  "blue-maomao": {
    author: "Luca Davenport-Thomas",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/263095867",
  },
  "blue-ringed-octopus": {
    author: "Gregor Bailar",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/393772050",
  },
  "blue-swimmer-crab": {
    author: "Debra Baker",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/267319789",
  },
  "bluegill": {
    author: "USFWS Mountain Prairie",
    license: "Public domain",
    license_url: "",
    source: "https://commons.wikimedia.org/wiki/File:Bluegill_(Lepomis_macrochirus)_black_background.jpg",
  },
  "bluegirdled-angelfish": {
    author: "Rickard Zerpe",
    license: "CC BY 2.0",
    license_url: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Bluegirdled_angelfish_(Pomacanthus_navarchus)_(46982094954).jpg",
  },
  "blunthead-cichlid": {
    author: "H. Zell",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Tropheus_moorii_'Moliro'_-_Karlsruhe_Zoo_01.jpg",
  },
  "bonnethead": {
    author: "Eric Kilby from Somerville, MA, USA",
    license: "CC BY-SA 2.0",
    license_url: "https://creativecommons.org/licenses/by-sa/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Bonnethead_shark_Aquarium_of_the_Pacific.jpg",
  },
  "bowfin": {
    author: "United States Fish and Wildlife Services",
    license: "Public domain",
    license_url: "",
    source: "https://commons.wikimedia.org/wiki/File:Bowfin_01.jpg",
  },
  "brook-trout": {
    author: "James St. John",
    license: "CC BY 2.0",
    license_url: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Salvelinus_fontinalis_(coaster_brook_trout)_2.jpg",
  },
  "buffalohead-cichlid": {
    author: "5snake5",
    license: "CC0",
    license_url: "https://creativecommons.org/publicdomain/zero/1.0/",
    source: "https://commons.wikimedia.org/wiki/File:Steatocranus_casuarius,_male.jpg",
  },
  "bumphead-parrotfish": {
    author: "R Vasconcellos",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/259177333",
  },
  "butterfish": {
    author: "Shaun Lee",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/113183821",
  },
  "cabezon": {
    author: "Chris Spain",
    license: "CC0",
    license_url: "https://creativecommons.org/publicdomain/zero/1.0/",
    source: "https://www.inaturalist.org/observations/391272116",
  },
  "california-halibut": {
    author: "Mike Carr",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/66279407",
  },
  "california-sheephead": {
    author: "Ed Bierman from CA, usa",
    license: "CC BY 2.0",
    license_url: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:CA_Sheephead,_CINMS.jpg",
  },
  "capelin": {
    author: "michaelbakkerpaiva",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Mallotus_villosus.jpg",
  },
  "cardinal-tetra": {
    author: "CHUCAO",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Cardinal_Paracheirodon_axelrodi_(3).jpg",
  },
  "caribbean-reef-octopus": {
    author: "Roger Rittmaster",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/151780613",
  },
  "caribbean-reef-shark": {
    author: "Dennis Hipp (Zepto)",
    license: "CC0",
    license_url: "https://creativecommons.org/publicdomain/zero/1.0/",
    source: "https://commons.wikimedia.org/wiki/File:Full_Shot_of_a_Caribbean_Reef_Shark_at_Tiger_Beach_Bahamas.jpg",
  },
  "cherry-anthias": {
    author: "harum.koh from Kobe city, Japan",
    license: "CC BY-SA 2.0",
    license_url: "https://creativecommons.org/licenses/by-sa/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Japan_fish,_Sakuradai_(Sacura_margaritacea)_(15770306721).jpg",
  },
  "china-rockfish": {
    author: "dpcmiller",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/193925914",
  },
  "christmas-island-red-crab": {
    author: "ian_mcallan",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/207689589",
  },
  "climbing-perch": {
    author: "Abu Hamas",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://www.inaturalist.org/observations/33406064",
  },
  "clown-anemonefish": {
    author: "Nick Hobgood",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Amphiprion_ocellaris_(Clown_anemonefish)_by_Nick_Hobgood.jpg",
  },
  "clown-featherback": {
    author: "Jesaya Li",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Adult_Clown_featherback_in_aquarium.jpg",
  },
  "clown-triggerfish": {
    author: "H. Zell",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Balistoides_conspicillum_01.jpg",
  },
  "common-cuttlefish": {
    author: "Michael Bommerer",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/247648491",
  },
  "common-dragonet": {
    author: "Klaus Kevin Kristensen",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/335263442",
  },
  "common-stingray": {
    author: "Chris Taklis",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Dasyatis_pastinaca_24933880.jpg",
  },
  "congo-tetra": {
    author: "7TP (Krzysztof Bartosik)",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Phenacogrammus_interruptus_1.jpg",
  },
  "coral-trout": {
    author: "Leonard Low from Australia",
    license: "CC BY 2.0",
    license_url: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Plectropomus_leopardus.jpg",
  },
  "corkwing-wrasse": {
    author: "Micha Baum",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://www.inaturalist.org/observations/152157136",
  },
  "cownose-ray": {
    author: "Citron",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Rhinoptera_bonasus_Brest.jpg",
  },
  "crown-of-thorns-starfish": {
    author: "Darren Obbard",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/264634378",
  },
  "cuckoo-catfish": {
    author: "Mario Rubio García",
    license: "CC BY 2.0",
    license_url: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Synodontis-multipunctatus.jpg",
  },
  "cuckoo-wrasse": {
    author: "Bingar1234",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Labrus_mixtus_23_BG.jpg",
  },
  "discus": {
    author: "H. Zell",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Symphysodon_aequifasciatus_-_Karlsruhe_Zoo_04.jpg",
  },
  "draughtsboard-shark": {
    author: "Py1jtp",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Carpetshark.jpg",
  },
  "dungeness-crab": {
    author: "Bildflut",
    license: "CC0",
    license_url: "https://creativecommons.org/publicdomain/zero/1.0/",
    source: "https://commons.wikimedia.org/wiki/File:Dungeness_crab_(Metacarcinus_magister)_2.jpg",
  },
  "dusky-grouper": {
    author: "Diego Delso",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Mero_(Epinephelus_marginatus),_Cabo_de_Palos,_Espa%C3%B1a,_2022-07-15,_DD_34.jpg",
  },
  "eastern-rainbowfish": {
    author: "Jesse de Vries",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Melanotaenia_splendida_splendida_188164829.jpg",
  },
  "edible-crab": {
    author: "Olivier Dugornay (Ifremer)",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Tourteau_(Cancer_pagurus)_(Ifremer_00378-48930_-_1097).jpg",
  },
  "electric-catfish": {
    author: "Stan Shebs",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Malapterurus_electricus_1.jpg",
  },
  "electric-eel": {
    author: "FakirNL",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Electrophorus_electricus_in_Ouwehands_Dierenpark_01.jpg",
  },
  "electric-yellow-cichlid": {
    author: "Jmatz at English Wikipedia\n\n(Original text: Julian Matz (talk))",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Labidochromis_caeruleus_(male).jpg",
  },
  "elephantnose-fish": {
    author: "NasserHalaweh",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Mormyridae_Gnathonemus_petersii_2.jpg",
  },
  "emerald-rockcod": {
    author: "Zureks",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Emerald_rockcod,_Trematomus_bernacchii.jpg",
  },
  "epaulette-shark": {
    author: "bbcjk.king",
    license: "CC BY 2.0",
    license_url: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Epaulette_shark_camden2.jpg",
  },
  "european-conger": {
    author: "Oscar Hopgood",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/311749158",
  },
  "european-seabass": {
    author: "Bjoertvedt",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Dicentrarchus_labrax_LoroParqueTenerife_seabass_IMG_4959.JPG",
  },
  "fairy-cichlid": {
    author: "Bjoertvedt",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Neolamprologus_brichardi_LoroParqueTenerife_princess_of_burundi_IMG_5384.JPG",
  },
  "flying-gurnard": {
    author: "Vicmicallef",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:FlyingGurnard.jpg",
  },
  "foureye-butterflyfish": {
    author: "Fish and Dive",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Chaetodon_capistratus_394406658.jpg",
  },
  "french-angelfish": {
    author: "LASZLO ILYES from Cleveland, Ohio, USA",
    license: "CC BY 2.0",
    license_url: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:French_Angelfish_in_Profile_(47447869022).jpg",
  },
  "freshwater-angelfish": {
    author: "Nick T.",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://www.inaturalist.org/observations/271102605",
  },
  "freshwater-jellyfish": {
    author: "OpenCage",
    license: "CC BY-SA 2.5",
    license_url: "https://creativecommons.org/licenses/by-sa/2.5",
    source: "https://commons.wikimedia.org/wiki/File:Craspedacusta_sowerbyi_by_OpenCage.jpg",
  },
  "frontosa": {
    author: "H. Zell",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Cyphotilapia_frontosa_-_Karlsruhe_Zoo_01.jpg",
  },
  "garfish": {
    author: "Sarah Faulwetter",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/130620757",
  },
  "garibaldi": {
    author: "Dwij Joshipura",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Garibaldi_(Fish).jpg",
  },
  "giant-barb": {
    author: "Mhlayson",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Siamese_giant_carp_(Catlocarpio_siamensis)_2.jpg",
  },
  "giant-freshwater-stingray": {
    author: "Gant223",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Urogymnus_polylepis_at_Itabashi_Botanical_Garden.png",
  },
  "giant-gourami": {
    author: "Jarro Nevsbaru",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/243375053",
  },
  "giant-mudskipper": {
    author: "Mhlayson",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Giant_Mudskipper_(Periophthalmodon_schlosseri).jpg",
  },
  "giant-river-prawn": {
    author: "Dmitry Ivanov",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/321247585",
  },
  "giant-sea-bass": {
    author: "tunicatedreamz",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/388891522",
  },
  "giant-snakehead": {
    author: "Cedricguppy - Loury Cédric",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Channa_micropeltes_-_T%C3%AAte_de_serpent_-_Aqua_Porte_Dor%C3%A9e_01.JPG",
  },
  "gilt-head-bream": {
    author: "Thesupermat",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Brest_-_Oc%C3%A9anopolis_-_2015_-_051.jpg",
  },
  "glass-catfish": {
    author: "TomCatX",
    license: "CC0",
    license_url: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Kryptopterus_vitreolus_(Cologne_Zoo).jpg",
  },
  "golden-mbuna": {
    author: "Roland Godon",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/138845070",
  },
  "goliath-tigerfish": {
    author: "Sablegsd",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Hydrocynus_goliath.jpg",
  },
  "greenland-shark": {
    author: "Hemming1952",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Greenland_shark_profile.jpg",
  },
  "grey-reef-shark": {
    author: "Daniel Benák",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/134590155",
  },
  "grunt-sculpin": {
    author: "Alicia Christman",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/231605752",
  },
  "gulf-saratoga": {
    author: "Ginkgo100",
    license: "CC BY-SA 3.0",
    license_url: "http://creativecommons.org/licenses/by-sa/3.0/",
    source: "https://commons.wikimedia.org/wiki/File:Scleropages_jardinii_043.JPG",
  },
  "harlequin-sweetlips": {
    author: "Rickard Zerpe",
    license: "CC BY 2.0",
    license_url: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Harlequin_sweetlips_(Plectorhinchus_chaetodonoides)_(40815006613).jpg",
  },
  "hippopotamus": {
    author: "Tony King",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/212246796",
  },
  "horsehair-crab": {
    author: "Totti",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Erimacrus_isenbeckii_Sunpiazza1.jpg",
  },
  "horseshoe-crab": {
    author: "Ryan Hearty",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/27591961",
  },
  "irrawaddy-dolphin": {
    author: "Ian Dugdale",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/302263707",
  },
  "japanese-angelshark": {
    author: "RYO SATO",
    license: "CC BY-SA 2.0",
    license_url: "https://creativecommons.org/licenses/by-sa/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Squatina_japonica3.jpg",
  },
  "japanese-bullhead-shark": {
    author: "Jin Kemoole",
    license: "CC BY 2.0",
    license_url: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Japanese_bullhead_shark_Suma_Aqualife_Park.jpg",
  },
  "japanese-pineconefish": {
    author: "Georgina Jones",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://www.inaturalist.org/observations/337396330",
  },
  "japanese-sawshark": {
    author: "タウナギ",
    license: "CC0",
    license_url: "https://creativecommons.org/publicdomain/zero/1.0/",
    source: "https://commons.wikimedia.org/wiki/File:Pristiophorus_japonicus_ioworld.jpg",
  },
  "japanese-seabass": {
    author: "Totti",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Lateolabrax_japonicus_Iwaki.jpg",
  },
  "japanese-spider-crab": {
    author: "Dallas Krentzel",
    license: "CC BY 2.0",
    license_url: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Giant_Japanese_spider_crab_(Macrocheira_kaempferi)_at_the_Shedd_Aquarium,_Chicago,_IL_(6802024350).jpg",
  },
  "japanese-surfperch": {
    author: "タウナギ",
    license: "CC0",
    license_url: "https://creativecommons.org/publicdomain/zero/1.0/",
    source: "https://commons.wikimedia.org/wiki/File:Ditrema_temmincki_temmincki_Oarai.jpg",
  },
  "jungle-perch": {
    author: "dhfischer",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/55850718",
  },
  "kahawai": {
    author: "Peter Crowcroft",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/64148300",
  },
  "kelp-greenling": {
    author: "Steve Lonhart / NOAA MBNMS",
    license: "Public domain",
    license_url: "",
    source: "https://commons.wikimedia.org/wiki/File:Hexagrammos_decagrammus_hembra.jpg",
  },
  "kissing-gourami": {
    author: "Igor Balashov",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/183323839",
  },
  "lake-sturgeon": {
    author: "USFWS Mountain Prairie",
    license: "Public domain",
    license_url: "",
    source: "https://commons.wikimedia.org/wiki/File:Juvenile_Acipenser_fulvescens_black_background.jpg",
  },
  "lake-trout": {
    author: "USFWS",
    license: "Public domain",
    license_url: "",
    source: "https://commons.wikimedia.org/wiki/File:Iron_River_NFH_lake_trout_6_March_2024.png",
  },
  "largetooth-sawfish": {
    author: "Peter Kyne, Charles Darwin University",
    license: "CC BY 3.0",
    license_url: "https://creativecommons.org/licenses/by/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Pristis_pristis_-_Daly_River.JPG",
  },
  "lemon-shark": {
    author: "Albert kok",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Lemon_shark2.jpg",
  },
  "leopard-bushfish": {
    author: "Karelj",
    license: "Public domain",
    license_url: "",
    source: "https://commons.wikimedia.org/wiki/File:Ctenopoma_acutirostre_1.JPG",
  },
  "leopard-seal": {
    author: "Kyle Bowman",
    license: "CC0",
    license_url: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://www.inaturalist.org/observations/340198432",
  },
  "leopard-shark": {
    author: "Brian Gratwicke",
    license: "CC BY 2.0",
    license_url: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Triakis_semifasciata_Gratwicke.jpg",
  },
  "lingcod": {
    author: "Chris Spain",
    license: "CC0",
    license_url: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Ophiodon_elongatus_458366655.jpg",
  },
  "lions-mane-jellyfish": {
    author: "W.carter",
    license: "CC0",
    license_url: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Lion's_mane_jellyfish_in_Gullmarn_fjord_at_S%C3%A4mstad_3.jpg",
  },
  "longfin-eel": {
    author: "Nil NZ",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Anguilla_dieffenbachii_01.jpg",
  },
  "longhorn-cowfish": {
    author: "Julien Lepage",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/239936453",
  },
  "longnose-gar": {
    author: "USFWS Mountain Prairie",
    license: "Public domain",
    license_url: "",
    source: "https://commons.wikimedia.org/wiki/File:Longnose_Gar_(Lepisosteus_osseus).jpg",
  },
  "luderick": {
    author: "Tim",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/143350190",
  },
  "lumpfish": {
    author: "Deadlymeap",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Lumpfish-Cyclopterus_lumpus.jpg",
  },
  "malawi-eyebiter": {
    author: "Hectonichus",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Cichlidae_-_Dimidiochromis_compressiceps.JPG",
  },
  "mandarinfish": {
    author: "Luc Viatour",
    license: "CC BY-SA 3.0",
    license_url: "http://creativecommons.org/licenses/by-sa/3.0/",
    source: "https://commons.wikimedia.org/wiki/File:Synchiropus_splendidus_2_Luc_Viatour.jpg",
  },
  "mangrove-jack": {
    author: "portioid",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/184223339",
  },
  "marbled-electric-ray": {
    author: "Ericsfr",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Torpedo_marmorata_(20150825)_01.jpg",
  },
  "marbled-rock-crab": {
    author: "Charles J. Sharp",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Marbled_crab_(Pachygrapsus_marmoratus)_Butrint.jpg",
  },
  "matamata": {
    author: "Whaldener Endo",
    license: "CC0",
    license_url: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://www.inaturalist.org/observations/121178138",
  },
  "mediterranean-cardinalfish": {
    author: "Ben Costamagna",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/229580364",
  },
  "mediterranean-damselfish": {
    author: "Donald Davesne",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/193870677",
  },
  "mediterranean-moray": {
    author: "Diego Delso",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Morena_del_Mediterr%C3%A1neo_(Muraena_helena),_Catania,_Sicilia,_Italia,_2025-04-05,_DD_35.jpg",
  },
  "mekong-giant-catfish": {
    author: "Cool critter channel",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Mekong_giant_catfish.jpg",
  },
  "moorish-idol": {
    author: "Rusty",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/188577",
  },
  "mud-crab": {
    author: "coenobita",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/117701367",
  },
  "muskellunge": {
    author: "James St. John",
    license: "CC BY 2.0",
    license_url: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Esox_masquinongy_(muskellunge)_1.jpg",
  },
  "nassau-grouper": {
    author: "OAR/National Undersea Research Program",
    license: "Public domain",
    license_url: "",
    source: "https://commons.wikimedia.org/wiki/File:Epinephelus_striatus_2.jpg",
  },
  "new-zealand-eagle-ray": {
    author: "Oscar Dove",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Myliobatis_tenuicaudatus_186845675.jpg",
  },
  "northern-hogsucker": {
    author: "Donald Davesne",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/225896518",
  },
  "northern-pike": {
    author: "Klaus Kevin Kristensen",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/86468799",
  },
  "nurse-shark": {
    author: "Ross Garner",
    license: "CC BY 2.0",
    license_url: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Ginglymostoma_cirratum_utila.jpg",
  },
  "nurseryfish": {
    author: "Geekgecko",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Kurtus_gulliveri.jpg",
  },
  "ocellate-river-stingray": {
    author: "Steven G. Johnson",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Ocellate_river_stingray,_Boston_Aquarium.jpg",
  },
  "ocellated-icefish": {
    author: "Valerie Loeb",
    license: "Public domain",
    license_url: "",
    source: "https://commons.wikimedia.org/wiki/File:Chionodraco_rastrospinosus.jpg",
  },
  "ornate-bichir": {
    author: "Bloopityboop",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Polypterus_ornatipinnis_VA_01.jpg",
  },
  "ornate-wrasse": {
    author: "Cisamarc",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Thalassoma_pavo_male.jpg",
  },
  "oscar": {
    author: "André Karwath aka Aka",
    license: "CC BY-SA 2.5",
    license_url: "https://creativecommons.org/licenses/by-sa/2.5",
    source: "https://commons.wikimedia.org/wiki/File:Astronotus_ocellatus_-_side_(aka).jpg",
  },
  "pacific-saury": {
    author: "出羽雀台",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Cololabis_saira_in_a_tank.jpg",
  },
  "pacific-spiny-dogfish": {
    author: "出羽雀台",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Squalus_suckleyi_in_an_aquarium.jpg",
  },
  "painted-comber": {
    author: "Donald Davesne",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/154755047",
  },
  "peacock-bass": {
    author: "Petruss",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Cichla_ocellaris.jpg",
  },
  "peacock-cichlid": {
    author: "Igor Balashov",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/187368348",
  },
  "peacock-flounder": {
    author: "Eamon Corbett",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/37806678",
  },
  "peacock-mantis-shrimp": {
    author: "portioid",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/197441524",
  },
  "pink-river-dolphin": {
    author: "Tiago Lubiana",
    license: "CC0",
    license_url: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://www.inaturalist.org/observations/104514790",
  },
  "polar-cod": {
    author: "Totti",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Boreogadus_saida_Kaiyukan.jpg",
  },
  "portuguese-man-o-war": {
    author: "Jan Ebr & Ivana Ebrová",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/108680440",
  },
  "potato-cod": {
    author: "NasserHalaweh",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Serranidae_Epinephelus_tukula_1.jpg",
  },
  "psychedelic-frogfish": {
    author: "Truite agile",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Psychedelic_frogfish_juvenile.jpg",
  },
  "pumpkinseed": {
    author: "Henggang Cui",
    license: "CC0",
    license_url: "https://creativecommons.org/publicdomain/zero/1.0",
    source: "https://www.inaturalist.org/observations/13315289",
  },
  "purple-rock-crab": {
    author: "Geoff Shuetrim",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/52443782",
  },
  "pygmy-seahorse": {
    author: "Rickard Zerpe",
    license: "CC BY-SA 2.0",
    license_url: "https://creativecommons.org/licenses/by-sa/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Pygmy_seahorse_(Hippocampus_bargibanti)_(16245385685).jpg",
  },
  "pyjama-cardinalfish": {
    author: "Rickard Zerpe",
    license: "CC BY 2.0",
    license_url: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Pajama_cardinalfish_(Sphaeramia_nematoptera)_(44065265714).jpg",
  },
  "queen-angelfish": {
    author: "Diego Delso",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Pez_ángel_reina_(Holacanthus_ciliaris),_Cozumel,_México,_2025-12-20,_DD_134.jpg",
  },
  "queen-triggerfish": {
    author: "Greg Grimes",
    license: "CC BY-SA 2.0",
    license_url: "https://creativecommons.org/licenses/by-sa/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Queen_Triggerfish_Balistes_vetula.jpg",
  },
  "rainbow-darter": {
    author: "Julien Renoult",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/10943406",
  },
  "red-bellied-piranha": {
    author: "H. Zell",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Pygocentrus_nattereri_-_Karlsruhe_Zoo_01.jpg",
  },
  "red-gurnard": {
    author: "Brian Gratwicke",
    license: "CC BY 2.0",
    license_url: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Chelidonichthys_kumu.jpg",
  },
  "red-king-crab": {
    author: "Sasha Isachenko",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Paralithodes_camtschaticus,_1.jpg",
  },
  "red-moki": {
    author: "Avenue",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Red_Moki_(Cheilodactylus_spectabilis).jpg",
  },
  "red-scorpionfish": {
    author: "Vicmicallef",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Red_Scorpionfish_(cropped).jpg",
  },
  "red-seabream": {
    author: "タウナギ",
    license: "CC0",
    license_url: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Pagrus_major_ioworld.jpg",
  },
  "redtail-catfish": {
    author: "Emőke Dénes",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Hal_-_Phractocephalus_hemioliopterus_-_1.jpg",
  },
  "reedfish": {
    author: "Tylwyth Eldar",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Erpetoichthys_calabaricus_01.jpg",
  },
  "ribbon-eel": {
    author: "Diego Delso",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Anguila_list%C3%B3n_azul_(Rhinomuraena_quaesita),_Anilao,_Filipinas,_2023-08-23,_DD_60.jpg",
  },
  "rock-beauty": {
    author: "Diego Delso",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Chabelita_tricolor_(Holacanthus_tricolor),_Cozumel,_México,_2025-12-20,_DD_104.jpg",
  },
  "royal-gramma": {
    author: "H. Zell",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Gramma_loreto_01.jpg",
  },
  "rusty-crayfish": {
    author: "Evan Feusi",
    license: "CC0",
    license_url: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://www.inaturalist.org/observations/304187437",
  },
  "sailfin-sandfish": {
    author: "Totti",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Arctoscopus_japonicus_Umigatari.png",
  },
  "sakhalin-taimen": {
    author: "Totti",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Hucho_perryi_Yamano1.jpg",
  },
  "salema": {
    author: "Donald Davesne",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/155020772",
  },
  "sally-lightfoot-crab": {
    author: "Brook",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/2455785",
  },
  "sand-tiger-shark": {
    author: "The Vertebrate Pokédex",
    license: "CC0",
    license_url: "https://creativecommons.org/publicdomain/zero/1.0/",
    source: "https://www.inaturalist.org/observations/293707953",
  },
  "sarcastic-fringehead": {
    author: "DrKjaergaard",
    license: "CC BY-SA 2.5",
    license_url: "https://creativecommons.org/licenses/by-sa/2.5",
    source: "https://commons.wikimedia.org/wiki/File:Sarcastic_fringehead_in_plastic_tube.JPG",
  },
  "sardine-cichlid": {
    author: "H. Zell",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Cyprichromis_leptosoma_%27Kitumba%27_-_Karlsruhe_Zoo_01.jpg",
  },
  "sea-angel": {
    author: "Tine Kinn Kvamme",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/8387299",
  },
  "sea-lamprey": {
    author: "Stephanie Tran",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Petromyzon_marinus_282284066_(cropped).jpg",
  },
  "sea-scorpion": {
    author: "Libby Keatley",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/248457271",
  },
  "sevengill-shark": {
    author: "Luca Davenport-Thomas",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/330674724",
  },
  "severum": {
    author: "Matthew Inabinett",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/351898598",
  },
  "shell-dweller-cichlid": {
    author: "Richard A. Ingebrigtsen",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Neolamprologus_multifasciatus_male.JPG",
  },
  "shorthorn-sculpin": {
    author: "Rebekah Bajkó",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/381745131",
  },
  "siamese-fighting-fish": {
    author: "Henryk Niestrój",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Bojownik_syjamski.jpg",
  },
  "siamese-tigerfish": {
    author: "Daiju Azuma",
    license: "CC BY-SA 2.5",
    license_url: "https://creativecommons.org/licenses/by-sa/2.5",
    source: "https://commons.wikimedia.org/wiki/File:Datnioides_pulcher_by_OpenCage.jpg",
  },
  "silver-arowana": {
    author: "Matthew Inabinett",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/203671686",
  },
  "six-barred-distichodus": {
    author: "Hectonichus",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Distichodontidae_-_Distichodus_sexfasciatus.JPG",
  },
  "smallmouth-bass": {
    author: "Engbretson Eric, U.S. Fish and Wildlife Service",
    license: "Public domain",
    license_url: "",
    source: "https://commons.wikimedia.org/wiki/File:Detailed_underwater_photo_of_smallmouth_bass_fish_micropterus_dolomieu.jpg",
  },
  "smallspotted-catshark": {
    author: "Ecomare/Sytske Dijksen",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Ecomare_-_hondshaai_(hondshaai-zeeaquarium-1108-sd).jpg",
  },
  "sockeye-salmon": {
    author: "David Menke",
    license: "Public domain",
    license_url: "",
    source: "https://commons.wikimedia.org/wiki/File:Oncorhynchus_nerka_2.jpg",
  },
  "southern-stingray": {
    author: "Albert kok",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Dasyatis_americana_(2008).jpg",
  },
  "spangled-perch": {
    author: "Tom Ferguson",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/382883636",
  },
  "spanish-dancer": {
    author: "Georgina Jones",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://www.inaturalist.org/observations/25713973",
  },
  "spanish-hogfish": {
    author: "LASZLO ILYES from Cleveland, Ohio, USA",
    license: "CC BY 2.0",
    license_url: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Bodianus_rufus_(46598633625).jpg",
  },
  "spiny-lumpsucker": {
    author: "Sue Carnahan",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/217304938",
  },
  "spotted-ratfish": {
    author: "Stosh Morency",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Hydrolagus_colliei_8049778.jpg",
  },
  "spotty": {
    author: "Thomas Linley",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/316212027",
  },
  "stoplight-parrotfish": {
    author: "Adona9 at English Wikipedia",
    license: "CC BY-SA 3.0",
    license_url: "http://creativecommons.org/licenses/by-sa/3.0/",
    source: "https://commons.wikimedia.org/wiki/File:Stoplight-parrotfish.jpg",
  },
  "striped-catfish": {
    author: "Gannu03",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://www.inaturalist.org/observations/203116244",
  },
  "striped-red-mullet": {
    author: "Tigerente",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Mullus_surmuletus_Cala_Gracio.jpg",
  },
  "swell-shark": {
    author: "Matthew Inabinett",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/322520636",
  },
  "tambaqui": {
    author: "Brian Gratwicke",
    license: "CC BY 2.0",
    license_url: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Black_pacu.jpg",
  },
  "tarakihi": {
    author: "Luca Davenport-Thomas",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/279166843",
  },
  "tarpon": {
    author: "Daiju Azuma",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Megalops_atlanticus_by_DaijuAzuma.jpg",
  },
  "tasselled-wobbegong": {
    author: "Rickard Zerpe",
    license: "CC BY 2.0",
    license_url: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Tasselled_wobbegong_(Eucrossorhinus_dasypogon).jpg",
  },
  "threadsail-filefish": {
    author: "呂一起(Lyu yi-chi)",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/305762931",
  },
  "tompot-blenny": {
    author: "Katerina Kalogerini",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/57164613",
  },
  "torafugu": {
    author: "Totti",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Takifugu_rubripes_AQUAS.jpg",
  },
  "trahira": {
    author: "R Vasconcellos",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/208159476",
  },
  "two-banded-seabream": {
    author: "Donald Davesne",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/83306261",
  },
  "upside-down-catfish": {
    author: "Igor Balashov",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/237908815",
  },
  "vampire-crab": {
    author: "CEphoto, Uwe Aranas",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Lahad-Datu_Sabah_Mount-Silam-Red-Crab-Geosesarma-aurantium-01.jpg",
  },
  "walleye": {
    author: "Engbretson, Eric / U.S. Fish and Wildlife Service",
    license: "Public domain",
    license_url: "",
    source: "https://commons.wikimedia.org/wiki/File:Sander_vitreus.jpg",
  },
  "walrus": {
    author: "steve b",
    license: "CC0",
    license_url: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://www.inaturalist.org/observations/279753045",
  },
  "warty-frogfish": {
    author: "Diego Delso",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Pez_sapo_payaso_(Antennarius_maculatus),_Anilao,_Filipinas,_2023-08-24,_DD_39.jpg",
  },
  "weedy-seadragon": {
    author: "Kai Squires",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/37463914",
  },
  "white-spotted-cichlid": {
    author: "lienyuan lee",
    license: "CC BY 3.0",
    license_url: "https://creativecommons.org/licenses/by/3.0",
    source: "https://commons.wikimedia.org/wiki/File:珍珠蝴蝶_Tropheus_duboisi_(Marlier,_1959)_-_panoramio.jpg",
  },
  "whitetip-reef-shark": {
    author: "Peter Nathaniel Boyer",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/10386392",
  },
  "wolf-eel": {
    author: "Julien Lepage",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/145836028",
  },
  "yellow-perch": {
    author: "USFWS Mountain Prairie",
    license: "Public domain",
    license_url: "",
    source: "https://commons.wikimedia.org/wiki/File:Yellow_Perch_(Perca_flavescens).jpg",
  },
  "yelloweye-rockfish": {
    author: "Oregon Department of Fish & Wildlife",
    license: "CC BY-SA 2.0",
    license_url: "https://creativecommons.org/licenses/by-sa/2.0",
    source: "https://commons.wikimedia.org/wiki/File:25_yeye2_frierson_odfw_(8253212034).jpg",
  },
  "yellowhead-jawfish": {
    author: "Pauline Walsh Jacobson",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/103705249",
  },
  "yellowmouth-barracuda": {
    author: "Donald Davesne",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/255624935",
  },
  "yellowtail-kingfish": {
    author: "Debra Baker",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/261228182",
  },
  "zebra-bullhead-shark": {
    author: "劉哲瑋",
    license: "CC0",
    license_url: "https://creativecommons.org/publicdomain/zero/1.0/",
    source: "https://www.inaturalist.org/observations/107635630",
  },
  "zebra-mbuna": {
    author: "Klaus Rudloff",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Maylandia_zebra_B.jpg",
  },
  "zebra-pleco": {
    author: "Birger A",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Hypancistrus_zebra4305.jpg",
  },
  "zebra-shark": {
    author: "Theo Kruse / Burgers' Zoo",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Zebra_shark_(Stegostoma_fasciatum).jpg",
  },
};

/* Fish ids in the order their photo was added, oldest first. */
const PHOTO_ORDER = [
  "sockeye-salmon",
  "queen-angelfish",
  "red-bellied-piranha",
  "atlantic-cod",
  "gilt-head-bream",
  "goliath-tigerfish",
  "electric-yellow-cichlid",
  "mandarinfish",
  "barramundi",
  "antarctic-toothfish",
  "yelloweye-rockfish",
  "lingcod",
  "nassau-grouper",
  "stoplight-parrotfish",
  "arapaima",
  "discus",
  "atlantic-wolffish",
  "atlantic-mackerel",
  "dusky-grouper",
  "european-seabass",
  "elephantnose-fish",
  "congo-tetra",
  "frontosa",
  "zebra-mbuna",
  "clown-anemonefish",
  "banggai-cardinalfish",
  "australian-lungfish",
  "potato-cod",
  "blackfin-icefish",
  "emerald-rockcod",
  "tarpon",
  "electric-eel",
  "lumpfish",
  "mediterranean-moray",
  "african-butterflyfish",
  "malawi-eyebiter",
  "ribbon-eel",
  "gulf-saratoga",
  "greenland-shark",
  "polar-cod",
  "capelin",
  "arctic-char",
  "lake-sturgeon",
  "muskellunge",
  "lake-trout",
  "bluegill",
  "red-seabream",
  "torafugu",
  "pacific-saury",
  "mekong-giant-catfish",
  "siamese-fighting-fish",
  "giant-freshwater-stingray",
  "giant-snakehead",
  "australasian-snapper",
  "longfin-eel",
  "blue-cod",
  "kahawai",
  "spotted-ratfish",
  "atlantic-blue-tang",
  "oscar",
  "atlantic-salmon",
  "red-scorpionfish",
  "six-barred-distichodus",
  "pygmy-seahorse",
  "walleye",
  "ayu",
  "red-moki",
  "ocellated-icefish",
  "sakhalin-taimen",
  "kelp-greenling",
  "queen-triggerfish",
  "foureye-butterflyfish",
  "redtail-catfish",
  "cardinal-tetra",
  "cuckoo-wrasse",
  "striped-red-mullet",
  "ornate-bichir",
  "cuckoo-catfish",
  "white-spotted-cichlid",
  "harlequin-sweetlips",
  "eastern-rainbowfish",
  "nurseryfish",
  "arctic-grayling",
  "longnose-gar",
  "yellow-perch",
  "sailfin-sandfish",
  "clown-featherback",
  "giant-barb",
  "red-gurnard",
  "leopard-shark",
  "pacific-spiny-dogfish",
  "nurse-shark",
  "bonnethead",
  "basking-shark",
  "angelshark",
  "tasselled-wobbegong",
  "epaulette-shark",
  "japanese-bullhead-shark",
  "draughtsboard-shark",
  "warty-frogfish",
  "psychedelic-frogfish",
  "sarcastic-fringehead",
  "sea-lamprey",
  "tambaqui",
  "reedfish",
  "glass-catfish",
  "giant-mudskipper",
  "bowfin",
  "flying-gurnard",
  "bluegirdled-angelfish",
  "pyjama-cardinalfish",
  "clown-triggerfish",
  "coral-trout",
  "barrier-reef-anemonefish",
  "royal-gramma",
  "rock-beauty",
  "spanish-hogfish",
  "ornate-wrasse",
  "cherry-anthias",
  "garibaldi",
  "california-sheephead",
  "southern-stingray",
  "french-angelfish",
  "marbled-electric-ray",
  "smallspotted-catshark",
  "whitetip-reef-shark",
  "peacock-bass",
  "siamese-tigerfish",
  "smallmouth-bass",
  "spotty",
  "banded-wrasse",
  "blue-maomao",
  "tarakihi",
  "luderick",
  "ballan-wrasse",
  "corkwing-wrasse",
  "european-conger",
  "painted-comber",
  "mediterranean-damselfish",
  "salema",
  "pumpkinseed",
  "northern-pike",
  "archerfish",
  "barred-knifejaw",
  "peacock-cichlid",
  "upside-down-catfish",
  "silver-arowana",
  "freshwater-angelfish",
  "blunthead-cichlid",
  "wolf-eel",
  "longhorn-cowfish",
  "japanese-pineconefish",
  "american-paddlefish",
  "electric-catfish",
  "shorthorn-sculpin",
  "climbing-perch",
  "largetooth-sawfish",
  "trahira",
  "golden-mbuna",
  "california-halibut",
  "grunt-sculpin",
  "giant-sea-bass",
  "mediterranean-cardinalfish",
  "tompot-blenny",
  "yellowhead-jawfish",
  "peacock-flounder",
  "moorish-idol",
  "bumphead-parrotfish",
  "giant-gourami",
  "butterfish",
  "rainbow-darter",
  "common-dragonet",
  "sea-scorpion",
  "yellowtail-kingfish",
  "sevengill-shark",
  "mangrove-jack",
  "threadsail-filefish",
  "kissing-gourami",
  "severum",
  "northern-hogsucker",
  "cabezon",
  "china-rockfish",
  "two-banded-seabream",
  "yellowmouth-barracuda",
  "garfish",
  "jungle-perch",
  "spangled-perch",
  "banded-leporinus",
  "bala-shark",
  "striped-catfish",
  "blue-ringed-octopus",
  "caribbean-reef-octopus",
  "common-cuttlefish",
  "swell-shark",
  "sand-tiger-shark",
  "blacktip-reef-shark",
  "grey-reef-shark",
  "zebra-bullhead-shark",
  "leopard-bushfish",
  "fairy-cichlid",
  "black-rockcod",
  "spiny-lumpsucker",
  "japanese-seabass",
  "zebra-pleco",
  "buffalohead-cichlid",
  "sardine-cichlid",
  "brook-trout",
  "japanese-surfperch",
  "caribbean-reef-shark",
  "lemon-shark",
  "ocellate-river-stingray",
  "shell-dweller-cichlid",
  "japanese-sawshark",
  "bat-ray",
  "cownose-ray",
  "common-stingray",
  "japanese-angelshark",
  "new-zealand-eagle-ray",
  "zebra-shark",
  "beluga-whale",
  "dungeness-crab",
  "red-king-crab",
  "edible-crab",
  "marbled-rock-crab",
  "blue-land-crab",
  "japanese-spider-crab",
  "horsehair-crab",
  "vampire-crab",
  "mud-crab",
  "purple-rock-crab",
  "peacock-mantis-shrimp",
  "antarctic-cushion-star",
  "sea-angel",
  "horseshoe-crab",
  "weedy-seadragon",
  "christmas-island-red-crab",
  "sally-lightfoot-crab",
  "blue-swimmer-crab",
  "spanish-dancer",
  "giant-river-prawn",
  "lions-mane-jellyfish",
  "freshwater-jellyfish",
  "pink-river-dolphin",
  "leopard-seal",
  "portuguese-man-o-war",
  "irrawaddy-dolphin",
  "rusty-crayfish",
  "aubrys-flapshell-turtle",
  "matamata",
  "crown-of-thorns-starfish",
  "walrus",
  "antarctic-krill",
  "hippopotamus",
];
