/* Fishguesser — photo attribution.
 *
 * GENERATED FILE — do not edit by hand.
 * Run `python3 tools/build_credits.py` to rebuild from
 * assets/fish/credits.json. Kept as a plain script (not JSON fetched at
 * runtime) so the game still works when opened straight from disk. */

const PHOTO_CREDITS = {
  "african-butterflyfish": {
    author: "Vassil",
    license: "CC0",
    license_url: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Pantodon_buchholzi_K%C3%B6ln_Zoo_31122014_1.jpg",
  },
  "american-paddlefish": {
    author: "Jon Mortin",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/255918853",
  },
  "angelshark": {
    author: "Julien Renoult",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Squatina_squatina_120867948.jpg",
  },
  "antarctic-toothfish": {
    author: "Citron",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Dissostichus_mawsoni.jpg",
  },
  "arapaima": {
    author: "T.Voekler",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Arapaima_gigas_5147.jpg",
  },
  "archerfish": {
    author: "Andrew Parker",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/310996412",
  },
  "arctic-char": {
    author: "Totti",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Salvelinus_alpinus_Kaiyukan.jpg",
  },
  "arctic-grayling": {
    author: "AKSMITH",
    license: "CC BY-SA 2.5",
    license_url: "https://creativecommons.org/licenses/by-sa/2.5",
    source: "https://commons.wikimedia.org/wiki/File:Underwater_Arctic_Grayling.jpg",
  },
  "atlantic-blue-tang": {
    author: "Diego Delso",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Pez_cirujano_azul_(Acanthurus_coeruleus),_Cozumel,_México,_2025-12-20,_DD_75.jpg",
  },
  "atlantic-cod": {
    author: "Wilhelm Thomas Fiege",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Atlantic_Cod,_Atlantischer_Kabeljau_(Gadus_morhua).jpg",
  },
  "atlantic-mackerel": {
    author: "Petar Milošević",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Atlantic_mackerel_(Scomber_scombrus).jpg",
  },
  "atlantic-salmon": {
    author: "Jarvin - Jarle Vines",
    license: "CC BY 3.0",
    license_url: "https://creativecommons.org/licenses/by/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Laks_i_laksetrappa.JPG",
  },
  "atlantic-wolffish": {
    author: "Bjørn Christian Tørrissen",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Anarhichas-lupus-Atlanterhavsparken.jpg",
  },
  "australasian-snapper": {
    author: "Auckland War Memorial Museum",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Pagrus_auratus_(Forster,_1801)_(AM_MA36682-1).jpg",
  },
  "australian-lungfish": {
    author: "タウナギ",
    license: "CC0",
    license_url: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Neoceratodus_forsteri_Nagoya1.jpg",
  },
  "ayu": {
    author: "タウナギ",
    license: "CC0",
    license_url: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Plecoglossus_altivelis_Totto.jpg",
  },
  "ballan-wrasse": {
    author: "Julien Renoult",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/34802668",
  },
  "banded-wrasse": {
    author: "Luca Davenport-Thomas",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/106113650",
  },
  "banggai-cardinalfish": {
    author: "Holger Krisp",
    license: "CC BY 3.0",
    license_url: "https://creativecommons.org/licenses/by/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Banggai-Kardinalbarsch_Pterapogon_kauderni.jpg",
  },
  "barramundi": {
    author: "Mitch Ames",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Lates_calcarifer,_2014-09-19a.jpg",
  },
  "barred-knifejaw": {
    author: "Nicola Crockford",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/254047520",
  },
  "barrier-reef-anemonefish": {
    author: "Leonard Low from Australia",
    license: "CC BY 2.0",
    license_url: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Amphiprion_akindynos.jpg",
  },
  "basking-shark": {
    author: "Green Fire Productions",
    license: "CC BY 2.0",
    license_url: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Cetorhinus_maximus_atlantic.jpg",
  },
  "blackfin-icefish": {
    author: "Ambiederman",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:C._aceratus.jpg",
  },
  "blue-cod": {
    author: "André Richard Chalmers",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Blue_Cod_in_Milford_Sound.jpg",
  },
  "blue-maomao": {
    author: "Luca Davenport-Thomas",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/263095867",
  },
  "bluegill": {
    author: "USFWS Mountain Prairie",
    license: "Public domain",
    license_url: "",
    source: "https://commons.wikimedia.org/wiki/File:Bluegill_(Lepomis_macrochirus)_black_background.jpg",
  },
  "bluegirdled-angelfish": {
    author: "Rickard Zerpe",
    license: "CC BY 2.0",
    license_url: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Bluegirdled_angelfish_(Pomacanthus_navarchus)_(46982094954).jpg",
  },
  "blunthead-cichlid": {
    author: "H. Zell",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Tropheus_moorii_'Moliro'_-_Karlsruhe_Zoo_01.jpg",
  },
  "bonnethead": {
    author: "Eric Kilby from Somerville, MA, USA",
    license: "CC BY-SA 2.0",
    license_url: "https://creativecommons.org/licenses/by-sa/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Bonnethead_shark_Aquarium_of_the_Pacific.jpg",
  },
  "bowfin": {
    author: "United States Fish and Wildlife Services",
    license: "Public domain",
    license_url: "",
    source: "https://commons.wikimedia.org/wiki/File:Bowfin_01.jpg",
  },
  "bumphead-parrotfish": {
    author: "R Vasconcellos",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/259177333",
  },
  "butterfish": {
    author: "Shaun Lee",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/113183821",
  },
  "california-halibut": {
    author: "Mike Carr",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/66279407",
  },
  "california-sheephead": {
    author: "Ed Bierman from CA, usa",
    license: "CC BY 2.0",
    license_url: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:CA_Sheephead,_CINMS.jpg",
  },
  "capelin": {
    author: "michaelbakkerpaiva",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Mallotus_villosus.jpg",
  },
  "cardinal-tetra": {
    author: "CHUCAO",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Cardinal_Paracheirodon_axelrodi_(3).jpg",
  },
  "cherry-anthias": {
    author: "harum.koh from Kobe city, Japan",
    license: "CC BY-SA 2.0",
    license_url: "https://creativecommons.org/licenses/by-sa/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Japan_fish,_Sakuradai_(Sacura_margaritacea)_(15770306721).jpg",
  },
  "climbing-perch": {
    author: "Abu Hamas",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://www.inaturalist.org/observations/33406064",
  },
  "clown-anemonefish": {
    author: "Nick Hobgood",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Amphiprion_ocellaris_(Clown_anemonefish)_by_Nick_Hobgood.jpg",
  },
  "clown-featherback": {
    author: "Jesaya Li",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Adult_Clown_featherback_in_aquarium.jpg",
  },
  "clown-triggerfish": {
    author: "H. Zell",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Balistoides_conspicillum_01.jpg",
  },
  "common-dragonet": {
    author: "Klaus Kevin Kristensen",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/335263442",
  },
  "congo-tetra": {
    author: "7TP (Krzysztof Bartosik)",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Phenacogrammus_interruptus_1.jpg",
  },
  "coral-trout": {
    author: "Leonard Low from Australia",
    license: "CC BY 2.0",
    license_url: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Plectropomus_leopardus.jpg",
  },
  "corkwing-wrasse": {
    author: "Micha Baum",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://www.inaturalist.org/observations/152157136",
  },
  "cuckoo-catfish": {
    author: "Mario Rubio García",
    license: "CC BY 2.0",
    license_url: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Synodontis-multipunctatus.jpg",
  },
  "cuckoo-wrasse": {
    author: "Bingar1234",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Labrus_mixtus_23_BG.jpg",
  },
  "discus": {
    author: "H. Zell",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Symphysodon_aequifasciatus_-_Karlsruhe_Zoo_04.jpg",
  },
  "draughtsboard-shark": {
    author: "Py1jtp",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Carpetshark.jpg",
  },
  "dusky-grouper": {
    author: "Diego Delso",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Mero_(Epinephelus_marginatus),_Cabo_de_Palos,_Espa%C3%B1a,_2022-07-15,_DD_34.jpg",
  },
  "eastern-rainbowfish": {
    author: "Jesse de Vries",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Melanotaenia_splendida_splendida_188164829.jpg",
  },
  "electric-catfish": {
    author: "Stan Shebs",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Malapterurus_electricus_1.jpg",
  },
  "electric-eel": {
    author: "FakirNL",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Electrophorus_electricus_in_Ouwehands_Dierenpark_01.jpg",
  },
  "electric-yellow-cichlid": {
    author: "Jmatz at English Wikipedia\n\n(Original text: Julian Matz (talk))",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Labidochromis_caeruleus_(male).jpg",
  },
  "elephantnose-fish": {
    author: "NasserHalaweh",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Mormyridae_Gnathonemus_petersii_2.jpg",
  },
  "emerald-rockcod": {
    author: "Zureks",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Emerald_rockcod,_Trematomus_bernacchii.jpg",
  },
  "epaulette-shark": {
    author: "bbcjk.king",
    license: "CC BY 2.0",
    license_url: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Epaulette_shark_camden2.jpg",
  },
  "european-conger": {
    author: "Oscar Hopgood",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/311749158",
  },
  "european-seabass": {
    author: "Bjoertvedt",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Dicentrarchus_labrax_LoroParqueTenerife_seabass_IMG_4959.JPG",
  },
  "flying-gurnard": {
    author: "Vicmicallef",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:FlyingGurnard.jpg",
  },
  "foureye-butterflyfish": {
    author: "Fish and Dive",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Chaetodon_capistratus_394406658.jpg",
  },
  "french-angelfish": {
    author: "LASZLO ILYES from Cleveland, Ohio, USA",
    license: "CC BY 2.0",
    license_url: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:French_Angelfish_in_Profile_(47447869022).jpg",
  },
  "freshwater-angelfish": {
    author: "Nick T.",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://www.inaturalist.org/observations/271102605",
  },
  "frontosa": {
    author: "H. Zell",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Cyphotilapia_frontosa_-_Karlsruhe_Zoo_01.jpg",
  },
  "garibaldi": {
    author: "Dwij Joshipura",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Garibaldi_(Fish).jpg",
  },
  "giant-barb": {
    author: "Mhlayson",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Siamese_giant_carp_(Catlocarpio_siamensis)_2.jpg",
  },
  "giant-freshwater-stingray": {
    author: "Gant223",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Urogymnus_polylepis_at_Itabashi_Botanical_Garden.png",
  },
  "giant-gourami": {
    author: "Jarro Nevsbaru",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/243375053",
  },
  "giant-mudskipper": {
    author: "Mhlayson",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Giant_Mudskipper_(Periophthalmodon_schlosseri).jpg",
  },
  "giant-sea-bass": {
    author: "tunicatedreamz",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/388891522",
  },
  "giant-snakehead": {
    author: "Cedricguppy - Loury Cédric",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Channa_micropeltes_-_T%C3%AAte_de_serpent_-_Aqua_Porte_Dor%C3%A9e_01.JPG",
  },
  "gilt-head-bream": {
    author: "Thesupermat",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Brest_-_Oc%C3%A9anopolis_-_2015_-_051.jpg",
  },
  "glass-catfish": {
    author: "TomCatX",
    license: "CC0",
    license_url: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Kryptopterus_vitreolus_(Cologne_Zoo).jpg",
  },
  "golden-mbuna": {
    author: "Roland Godon",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/138845070",
  },
  "goliath-tigerfish": {
    author: "Sablegsd",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Hydrocynus_goliath.jpg",
  },
  "greenland-shark": {
    author: "Hemming1952",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Greenland_shark_profile.jpg",
  },
  "grunt-sculpin": {
    author: "Alicia Christman",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/231605752",
  },
  "gulf-saratoga": {
    author: "Ginkgo100",
    license: "CC BY-SA 3.0",
    license_url: "http://creativecommons.org/licenses/by-sa/3.0/",
    source: "https://commons.wikimedia.org/wiki/File:Scleropages_jardinii_043.JPG",
  },
  "harlequin-sweetlips": {
    author: "Rickard Zerpe",
    license: "CC BY 2.0",
    license_url: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Harlequin_sweetlips_(Plectorhinchus_chaetodonoides)_(40815006613).jpg",
  },
  "japanese-bullhead-shark": {
    author: "Jin Kemoole",
    license: "CC BY 2.0",
    license_url: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Japanese_bullhead_shark_Suma_Aqualife_Park.jpg",
  },
  "japanese-pineconefish": {
    author: "Georgina Jones",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://www.inaturalist.org/observations/337396330",
  },
  "kahawai": {
    author: "Peter Crowcroft",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/64148300",
  },
  "kelp-greenling": {
    author: "Steve Lonhart / NOAA MBNMS",
    license: "Public domain",
    license_url: "",
    source: "https://commons.wikimedia.org/wiki/File:Hexagrammos_decagrammus_hembra.jpg",
  },
  "kissing-gourami": {
    author: "Igor Balashov",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/183323839",
  },
  "lake-sturgeon": {
    author: "USFWS Mountain Prairie",
    license: "Public domain",
    license_url: "",
    source: "https://commons.wikimedia.org/wiki/File:Juvenile_Acipenser_fulvescens_black_background.jpg",
  },
  "lake-trout": {
    author: "USFWS",
    license: "Public domain",
    license_url: "",
    source: "https://commons.wikimedia.org/wiki/File:Iron_River_NFH_lake_trout_6_March_2024.png",
  },
  "largetooth-sawfish": {
    author: "Peter Kyne, Charles Darwin University",
    license: "CC BY 3.0",
    license_url: "https://creativecommons.org/licenses/by/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Pristis_pristis_-_Daly_River.JPG",
  },
  "leopard-shark": {
    author: "Brian Gratwicke",
    license: "CC BY 2.0",
    license_url: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Triakis_semifasciata_Gratwicke.jpg",
  },
  "lingcod": {
    author: "Chris Spain",
    license: "CC0",
    license_url: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Ophiodon_elongatus_458366655.jpg",
  },
  "longfin-eel": {
    author: "Nil NZ",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Anguilla_dieffenbachii_01.jpg",
  },
  "longhorn-cowfish": {
    author: "Julien Lepage",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/239936453",
  },
  "longnose-gar": {
    author: "USFWS Mountain Prairie",
    license: "Public domain",
    license_url: "",
    source: "https://commons.wikimedia.org/wiki/File:Longnose_Gar_(Lepisosteus_osseus).jpg",
  },
  "luderick": {
    author: "Tim",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/143350190",
  },
  "lumpfish": {
    author: "Deadlymeap",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Lumpfish-Cyclopterus_lumpus.jpg",
  },
  "malawi-eyebiter": {
    author: "Hectonichus",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Cichlidae_-_Dimidiochromis_compressiceps.JPG",
  },
  "mandarinfish": {
    author: "Luc Viatour",
    license: "CC BY-SA 3.0",
    license_url: "http://creativecommons.org/licenses/by-sa/3.0/",
    source: "https://commons.wikimedia.org/wiki/File:Synchiropus_splendidus_2_Luc_Viatour.jpg",
  },
  "mangrove-jack": {
    author: "portioid",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/184223339",
  },
  "marbled-electric-ray": {
    author: "Ericsfr",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Torpedo_marmorata_(20150825)_01.jpg",
  },
  "mediterranean-cardinalfish": {
    author: "Ben Costamagna",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/229580364",
  },
  "mediterranean-damselfish": {
    author: "Donald Davesne",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/193870677",
  },
  "mediterranean-moray": {
    author: "Diego Delso",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Morena_del_Mediterr%C3%A1neo_(Muraena_helena),_Catania,_Sicilia,_Italia,_2025-04-05,_DD_35.jpg",
  },
  "mekong-giant-catfish": {
    author: "Cool critter channel",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Mekong_giant_catfish.jpg",
  },
  "moorish-idol": {
    author: "Rusty",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/188577",
  },
  "muskellunge": {
    author: "James St. John",
    license: "CC BY 2.0",
    license_url: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Esox_masquinongy_(muskellunge)_1.jpg",
  },
  "nassau-grouper": {
    author: "OAR/National Undersea Research Program",
    license: "Public domain",
    license_url: "",
    source: "https://commons.wikimedia.org/wiki/File:Epinephelus_striatus_2.jpg",
  },
  "northern-hogsucker": {
    author: "Donald Davesne",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/225896518",
  },
  "northern-pike": {
    author: "Klaus Kevin Kristensen",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/86468799",
  },
  "nurse-shark": {
    author: "Ross Garner",
    license: "CC BY 2.0",
    license_url: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Ginglymostoma_cirratum_utila.jpg",
  },
  "nurseryfish": {
    author: "Geekgecko",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Kurtus_gulliveri.jpg",
  },
  "ocellated-icefish": {
    author: "Valerie Loeb",
    license: "Public domain",
    license_url: "",
    source: "https://commons.wikimedia.org/wiki/File:Chionodraco_rastrospinosus.jpg",
  },
  "ornate-bichir": {
    author: "Bloopityboop",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Polypterus_ornatipinnis_VA_01.jpg",
  },
  "ornate-wrasse": {
    author: "Cisamarc",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Thalassoma_pavo_male.jpg",
  },
  "oscar": {
    author: "André Karwath aka Aka",
    license: "CC BY-SA 2.5",
    license_url: "https://creativecommons.org/licenses/by-sa/2.5",
    source: "https://commons.wikimedia.org/wiki/File:Astronotus_ocellatus_-_side_(aka).jpg",
  },
  "pacific-saury": {
    author: "出羽雀台",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Cololabis_saira_in_a_tank.jpg",
  },
  "pacific-spiny-dogfish": {
    author: "出羽雀台",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Squalus_suckleyi_in_an_aquarium.jpg",
  },
  "painted-comber": {
    author: "Donald Davesne",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/154755047",
  },
  "peacock-bass": {
    author: "Petruss",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Cichla_ocellaris.jpg",
  },
  "peacock-cichlid": {
    author: "Igor Balashov",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/187368348",
  },
  "peacock-flounder": {
    author: "Eamon Corbett",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/37806678",
  },
  "polar-cod": {
    author: "Totti",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Boreogadus_saida_Kaiyukan.jpg",
  },
  "potato-cod": {
    author: "NasserHalaweh",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Serranidae_Epinephelus_tukula_1.jpg",
  },
  "psychedelic-frogfish": {
    author: "Truite agile",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Psychedelic_frogfish_juvenile.jpg",
  },
  "pumpkinseed": {
    author: "Henggang Cui",
    license: "CC0",
    license_url: "https://creativecommons.org/publicdomain/zero/1.0",
    source: "https://www.inaturalist.org/observations/13315289",
  },
  "pygmy-seahorse": {
    author: "Rickard Zerpe",
    license: "CC BY-SA 2.0",
    license_url: "https://creativecommons.org/licenses/by-sa/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Pygmy_seahorse_(Hippocampus_bargibanti)_(16245385685).jpg",
  },
  "pyjama-cardinalfish": {
    author: "Rickard Zerpe",
    license: "CC BY 2.0",
    license_url: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Pajama_cardinalfish_(Sphaeramia_nematoptera)_(44065265714).jpg",
  },
  "queen-angelfish": {
    author: "Diego Delso",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Pez_ángel_reina_(Holacanthus_ciliaris),_Cozumel,_México,_2025-12-20,_DD_134.jpg",
  },
  "queen-triggerfish": {
    author: "Greg Grimes",
    license: "CC BY-SA 2.0",
    license_url: "https://creativecommons.org/licenses/by-sa/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Queen_Triggerfish_Balistes_vetula.jpg",
  },
  "rainbow-darter": {
    author: "Julien Renoult",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/10943406",
  },
  "red-bellied-piranha": {
    author: "H. Zell",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Pygocentrus_nattereri_-_Karlsruhe_Zoo_01.jpg",
  },
  "red-gurnard": {
    author: "Brian Gratwicke",
    license: "CC BY 2.0",
    license_url: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Chelidonichthys_kumu.jpg",
  },
  "red-moki": {
    author: "Avenue",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Red_Moki_(Cheilodactylus_spectabilis).jpg",
  },
  "red-scorpionfish": {
    author: "Vicmicallef",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Red_Scorpionfish_(cropped).jpg",
  },
  "red-seabream": {
    author: "タウナギ",
    license: "CC0",
    license_url: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Pagrus_major_ioworld.jpg",
  },
  "redtail-catfish": {
    author: "Emőke Dénes",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Hal_-_Phractocephalus_hemioliopterus_-_1.jpg",
  },
  "reedfish": {
    author: "Tylwyth Eldar",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Erpetoichthys_calabaricus_01.jpg",
  },
  "ribbon-eel": {
    author: "Diego Delso",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Anguila_list%C3%B3n_azul_(Rhinomuraena_quaesita),_Anilao,_Filipinas,_2023-08-23,_DD_60.jpg",
  },
  "rock-beauty": {
    author: "Diego Delso",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Chabelita_tricolor_(Holacanthus_tricolor),_Cozumel,_México,_2025-12-20,_DD_104.jpg",
  },
  "royal-gramma": {
    author: "H. Zell",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Gramma_loreto_01.jpg",
  },
  "sailfin-sandfish": {
    author: "Totti",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Arctoscopus_japonicus_Umigatari.png",
  },
  "sakhalin-taimen": {
    author: "Totti",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Hucho_perryi_Yamano1.jpg",
  },
  "salema": {
    author: "Donald Davesne",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/155020772",
  },
  "sarcastic-fringehead": {
    author: "DrKjaergaard",
    license: "CC BY-SA 2.5",
    license_url: "https://creativecommons.org/licenses/by-sa/2.5",
    source: "https://commons.wikimedia.org/wiki/File:Sarcastic_fringehead_in_plastic_tube.JPG",
  },
  "sea-lamprey": {
    author: "Stephanie Tran",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Petromyzon_marinus_282284066_(cropped).jpg",
  },
  "sea-scorpion": {
    author: "Libby Keatley",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/248457271",
  },
  "sevengill-shark": {
    author: "Luca Davenport-Thomas",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/330674724",
  },
  "severum": {
    author: "Matthew Inabinett",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/351898598",
  },
  "shorthorn-sculpin": {
    author: "Rebekah Bajkó",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/381745131",
  },
  "siamese-fighting-fish": {
    author: "Henryk Niestrój",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Bojownik_syjamski.jpg",
  },
  "siamese-tigerfish": {
    author: "Daiju Azuma",
    license: "CC BY-SA 2.5",
    license_url: "https://creativecommons.org/licenses/by-sa/2.5",
    source: "https://commons.wikimedia.org/wiki/File:Datnioides_pulcher_by_OpenCage.jpg",
  },
  "silver-arowana": {
    author: "Matthew Inabinett",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/203671686",
  },
  "six-barred-distichodus": {
    author: "Hectonichus",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Distichodontidae_-_Distichodus_sexfasciatus.JPG",
  },
  "smallmouth-bass": {
    author: "Engbretson Eric, U.S. Fish and Wildlife Service",
    license: "Public domain",
    license_url: "",
    source: "https://commons.wikimedia.org/wiki/File:Detailed_underwater_photo_of_smallmouth_bass_fish_micropterus_dolomieu.jpg",
  },
  "smallspotted-catshark": {
    author: "Ecomare/Sytske Dijksen",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Ecomare_-_hondshaai_(hondshaai-zeeaquarium-1108-sd).jpg",
  },
  "sockeye-salmon": {
    author: "David Menke",
    license: "Public domain",
    license_url: "",
    source: "https://commons.wikimedia.org/wiki/File:Oncorhynchus_nerka_2.jpg",
  },
  "southern-stingray": {
    author: "Albert kok",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Dasyatis_americana_(2008).jpg",
  },
  "spanish-hogfish": {
    author: "LASZLO ILYES from Cleveland, Ohio, USA",
    license: "CC BY 2.0",
    license_url: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Bodianus_rufus_(46598633625).jpg",
  },
  "spotted-ratfish": {
    author: "Stosh Morency",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Hydrolagus_colliei_8049778.jpg",
  },
  "spotty": {
    author: "Thomas Linley",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/316212027",
  },
  "stoplight-parrotfish": {
    author: "Adona9 at English Wikipedia",
    license: "CC BY-SA 3.0",
    license_url: "http://creativecommons.org/licenses/by-sa/3.0/",
    source: "https://commons.wikimedia.org/wiki/File:Stoplight-parrotfish.jpg",
  },
  "striped-red-mullet": {
    author: "Tigerente",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Mullus_surmuletus_Cala_Gracio.jpg",
  },
  "tambaqui": {
    author: "Brian Gratwicke",
    license: "CC BY 2.0",
    license_url: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Black_pacu.jpg",
  },
  "tarakihi": {
    author: "Luca Davenport-Thomas",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/279166843",
  },
  "tarpon": {
    author: "Daiju Azuma",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Megalops_atlanticus_by_DaijuAzuma.jpg",
  },
  "tasselled-wobbegong": {
    author: "Rickard Zerpe",
    license: "CC BY 2.0",
    license_url: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Tasselled_wobbegong_(Eucrossorhinus_dasypogon).jpg",
  },
  "threadsail-filefish": {
    author: "呂一起(Lyu yi-chi)",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/305762931",
  },
  "tompot-blenny": {
    author: "Katerina Kalogerini",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/57164613",
  },
  "torafugu": {
    author: "Totti",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Takifugu_rubripes_AQUAS.jpg",
  },
  "trahira": {
    author: "R Vasconcellos",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/208159476",
  },
  "upside-down-catfish": {
    author: "Igor Balashov",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/237908815",
  },
  "walleye": {
    author: "Engbretson, Eric / U.S. Fish and Wildlife Service",
    license: "Public domain",
    license_url: "",
    source: "https://commons.wikimedia.org/wiki/File:Sander_vitreus.jpg",
  },
  "warty-frogfish": {
    author: "Diego Delso",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Pez_sapo_payaso_(Antennarius_maculatus),_Anilao,_Filipinas,_2023-08-24,_DD_39.jpg",
  },
  "white-spotted-cichlid": {
    author: "lienyuan lee",
    license: "CC BY 3.0",
    license_url: "https://creativecommons.org/licenses/by/3.0",
    source: "https://commons.wikimedia.org/wiki/File:珍珠蝴蝶_Tropheus_duboisi_(Marlier,_1959)_-_panoramio.jpg",
  },
  "whitetip-reef-shark": {
    author: "Peter Nathaniel Boyer",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/10386392",
  },
  "wolf-eel": {
    author: "Julien Lepage",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/145836028",
  },
  "yellow-perch": {
    author: "USFWS Mountain Prairie",
    license: "Public domain",
    license_url: "",
    source: "https://commons.wikimedia.org/wiki/File:Yellow_Perch_(Perca_flavescens).jpg",
  },
  "yelloweye-rockfish": {
    author: "Oregon Department of Fish & Wildlife",
    license: "CC BY-SA 2.0",
    license_url: "https://creativecommons.org/licenses/by-sa/2.0",
    source: "https://commons.wikimedia.org/wiki/File:25_yeye2_frierson_odfw_(8253212034).jpg",
  },
  "yellowhead-jawfish": {
    author: "Pauline Walsh Jacobson",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/103705249",
  },
  "yellowtail-kingfish": {
    author: "Debra Baker",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://www.inaturalist.org/observations/261228182",
  },
  "zebra-mbuna": {
    author: "Klaus Rudloff",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Maylandia_zebra_B.jpg",
  },
};
