/* Fishguesser — photo attribution.
 *
 * GENERATED FILE — do not edit by hand.
 * Run `python3 tools/build_credits.py` to rebuild from
 * assets/fish/credits.json. Kept as a plain script (not JSON fetched at
 * runtime) so the game still works when opened straight from disk. */

const PHOTO_CREDITS = {
  "african-butterflyfish": {
    author: "Vassil",
    license: "CC0",
    license_url: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Pantodon_buchholzi_K%C3%B6ln_Zoo_31122014_1.jpg",
  },
  "antarctic-toothfish": {
    author: "Valerie Loeb",
    license: "Public domain",
    license_url: "",
    source: "https://commons.wikimedia.org/wiki/File:Dissostichus_mawsoni_NOAA_Fish8711.jpg",
  },
  "arapaima": {
    author: "T.Voekler",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Arapaima_gigas_5147.jpg",
  },
  "arctic-char": {
    author: "Totti",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Salvelinus_alpinus_Kaiyukan.jpg",
  },
  "atlantic-blue-tang": {
    author: "Diego Delso",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Pez_cirujano_azul_(Acanthurus_coeruleus),_Cozumel,_México,_2025-12-20,_DD_75.jpg",
  },
  "atlantic-cod": {
    author: "Wilhelm Thomas Fiege",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Atlantic_Cod,_Atlantischer_Kabeljau_(Gadus_morhua).jpg",
  },
  "atlantic-mackerel": {
    author: "Petar Milošević",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Atlantic_mackerel_(Scomber_scombrus).jpg",
  },
  "atlantic-salmon": {
    author: "Jarvin - Jarle Vines",
    license: "CC BY 3.0",
    license_url: "https://creativecommons.org/licenses/by/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Laks_i_laksetrappa.JPG",
  },
  "atlantic-wolffish": {
    author: "Bjørn Christian Tørrissen",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Anarhichas-lupus-Atlanterhavsparken.jpg",
  },
  "australasian-snapper": {
    author: "Auckland War Memorial Museum",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Pagrus_auratus_(Forster,_1801)_(AM_MA36682-1).jpg",
  },
  "australian-lungfish": {
    author: "タウナギ",
    license: "CC0",
    license_url: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Neoceratodus_forsteri_Nagoya1.jpg",
  },
  "ayu": {
    author: "タウナギ",
    license: "CC0",
    license_url: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Plecoglossus_altivelis_Totto.jpg",
  },
  "banggai-cardinalfish": {
    author: "Holger Krisp",
    license: "CC BY 3.0",
    license_url: "https://creativecommons.org/licenses/by/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Banggai-Kardinalbarsch_Pterapogon_kauderni.jpg",
  },
  "barramundi": {
    author: "Mitch Ames",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Lates_calcarifer,_2014-09-19a.jpg",
  },
  "blackfin-icefish": {
    author: "Ambiederman",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:C._aceratus.jpg",
  },
  "blue-cod": {
    author: "André Richard Chalmers",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Blue_Cod_in_Milford_Sound.jpg",
  },
  "bluegill": {
    author: "USFWS Mountain Prairie",
    license: "Public domain",
    license_url: "",
    source: "https://commons.wikimedia.org/wiki/File:Bluegill_(Lepomis_macrochirus)_black_background.jpg",
  },
  "capelin": {
    author: "michaelbakkerpaiva",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Mallotus_villosus.jpg",
  },
  "clown-anemonefish": {
    author: "Nick Hobgood",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Amphiprion_ocellaris_(Clown_anemonefish)_by_Nick_Hobgood.jpg",
  },
  "congo-tetra": {
    author: "7TP (Krzysztof Bartosik)",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Phenacogrammus_interruptus_1.jpg",
  },
  "discus": {
    author: "H. Zell",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Symphysodon_aequifasciatus_-_Karlsruhe_Zoo_04.jpg",
  },
  "dusky-grouper": {
    author: "Diego Delso",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Mero_(Epinephelus_marginatus),_Cabo_de_Palos,_Espa%C3%B1a,_2022-07-15,_DD_34.jpg",
  },
  "electric-eel": {
    author: "FakirNL",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Electrophorus_electricus_in_Ouwehands_Dierenpark_01.jpg",
  },
  "electric-yellow-cichlid": {
    author: "Jmatz at English Wikipedia\n\n(Original text: Julian Matz (talk))",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Labidochromis_caeruleus_(male).jpg",
  },
  "elephantnose-fish": {
    author: "NasserHalaweh",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Mormyridae_Gnathonemus_petersii_2.jpg",
  },
  "emerald-rockcod": {
    author: "Zureks",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Emerald_rockcod,_Trematomus_bernacchii.jpg",
  },
  "european-seabass": {
    author: "Bjoertvedt",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Dicentrarchus_labrax_LoroParqueTenerife_seabass_IMG_4959.JPG",
  },
  "frontosa": {
    author: "H. Zell",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Cyphotilapia_frontosa_-_Karlsruhe_Zoo_01.jpg",
  },
  "giant-freshwater-stingray": {
    author: "Gant223",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Urogymnus_polylepis_at_Itabashi_Botanical_Garden.png",
  },
  "giant-snakehead": {
    author: "Cedricguppy - Loury Cédric",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Channa_micropeltes_-_T%C3%AAte_de_serpent_-_Aqua_Porte_Dor%C3%A9e_01.JPG",
  },
  "gilt-head-bream": {
    author: "Thesupermat",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Brest_-_Oc%C3%A9anopolis_-_2015_-_051.jpg",
  },
  "goliath-tigerfish": {
    author: "Sablegsd",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Hydrocynus_goliath.jpg",
  },
  "greenland-shark": {
    author: "Hemming1952",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Greenland_shark_profile.jpg",
  },
  "gulf-saratoga": {
    author: "Ginkgo100",
    license: "CC BY-SA 3.0",
    license_url: "http://creativecommons.org/licenses/by-sa/3.0/",
    source: "https://commons.wikimedia.org/wiki/File:Scleropages_jardinii_043.JPG",
  },
  "japanese-amberjack": {
    author: "re_nebel",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Seriola_quinqueradiata.jpg",
  },
  "kahawai": {
    author: "zoology",
    license: "CC0",
    license_url: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Arripis_trutta_NZ.jpg",
  },
  "lake-sturgeon": {
    author: "USFWS Mountain Prairie",
    license: "Public domain",
    license_url: "",
    source: "https://commons.wikimedia.org/wiki/File:Juvenile_Acipenser_fulvescens_black_background.jpg",
  },
  "lake-trout": {
    author: "Knepp Timothy, U.S. Fish and Wildlife Service",
    license: "Public domain",
    license_url: "",
    source: "https://commons.wikimedia.org/wiki/File:Lake_trout_fishes_salvelinus_namaycush.jpg",
  },
  "lingcod": {
    author: "Chris Spain",
    license: "CC0",
    license_url: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Ophiodon_elongatus_458366655.jpg",
  },
  "longfin-eel": {
    author: "nick_goldwater",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Anguilla_dieffenbachii_62220829.jpg",
  },
  "lumpfish": {
    author: "Tiit Hunt",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Merivarblane.jpg",
  },
  "mackerel-icefish": {
    author: "Ryan Somma",
    license: "CC BY-SA 2.0",
    license_url: "https://creativecommons.org/licenses/by-sa/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Mackerel_Icefish_(Champsocephalus_gunnari).jpg",
  },
  "malawi-eyebiter": {
    author: "Hectonichus",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Cichlidae_-_Dimidiochromis_compressiceps.JPG",
  },
  "mandarinfish": {
    author: "Luc Viatour",
    license: "CC BY-SA 3.0",
    license_url: "http://creativecommons.org/licenses/by-sa/3.0/",
    source: "https://commons.wikimedia.org/wiki/File:Synchiropus_splendidus_2_Luc_Viatour.jpg",
  },
  "mediterranean-moray": {
    author: "Diego Delso",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Morena_del_Mediterr%C3%A1neo_(Muraena_helena),_Catania,_Sicilia,_Italia,_2025-04-05,_DD_35.jpg",
  },
  "mekong-giant-catfish": {
    author: "Cool critter channel",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Mekong_giant_catfish.jpg",
  },
  "muskellunge": {
    author: "James St. John",
    license: "CC BY 2.0",
    license_url: "https://creativecommons.org/licenses/by/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Esox_masquinongy_(muskellunge)_1.jpg",
  },
  "nassau-grouper": {
    author: "OAR/National Undersea Research Program",
    license: "Public domain",
    license_url: "",
    source: "https://commons.wikimedia.org/wiki/File:Epinephelus_striatus_2.jpg",
  },
  "oscar": {
    author: "André Karwath aka Aka",
    license: "CC BY-SA 2.5",
    license_url: "https://creativecommons.org/licenses/by-sa/2.5",
    source: "https://commons.wikimedia.org/wiki/File:Astronotus_ocellatus_-_side_(aka).jpg",
  },
  "pacific-halibut": {
    author: "Баранчук-Червонный Лев",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Hippoglossus_stenolepis_1.JPG",
  },
  "pacific-saury": {
    author: "出羽雀台",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Cololabis_saira_in_a_tank.jpg",
  },
  "polar-cod": {
    author: "Totti",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Boreogadus_saida_Kaiyukan.jpg",
  },
  "potato-cod": {
    author: "NasserHalaweh",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Serranidae_Epinephelus_tukula_1.jpg",
  },
  "pygmy-seahorse": {
    author: "Rickard Zerpe",
    license: "CC BY-SA 2.0",
    license_url: "https://creativecommons.org/licenses/by-sa/2.0",
    source: "https://commons.wikimedia.org/wiki/File:Pygmy_seahorse_(Hippocampus_bargibanti)_(16245385685).jpg",
  },
  "queen-angelfish": {
    author: "Stan Shebs",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Holacanthus_ciliaris_2.jpg",
  },
  "red-bellied-piranha": {
    author: "H. Zell",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Pygocentrus_nattereri_-_Karlsruhe_Zoo_01.jpg",
  },
  "red-moki": {
    author: "Avenue",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Red_Moki_(Cheilodactylus_spectabilis).jpg",
  },
  "red-scorpionfish": {
    author: "Vicmicallef",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Red_Scorpionfish_(cropped).jpg",
  },
  "red-seabream": {
    author: "タウナギ",
    license: "CC0",
    license_url: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    source: "https://commons.wikimedia.org/wiki/File:Pagrus_major_ioworld.jpg",
  },
  "ribbon-eel": {
    author: "Diego Delso",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Anguila_list%C3%B3n_azul_(Rhinomuraena_quaesita),_Anilao,_Filipinas,_2023-08-23,_DD_60.jpg",
  },
  "siamese-fighting-fish": {
    author: "Henryk Niestrój",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Bojownik_syjamski.jpg",
  },
  "six-barred-distichodus": {
    author: "Hectonichus",
    license: "CC BY-SA 3.0",
    license_url: "https://creativecommons.org/licenses/by-sa/3.0",
    source: "https://commons.wikimedia.org/wiki/File:Distichodontidae_-_Distichodus_sexfasciatus.JPG",
  },
  "sockeye-salmon": {
    author: "David Menke",
    license: "Public domain",
    license_url: "",
    source: "https://commons.wikimedia.org/wiki/File:Oncorhynchus_nerka_2.jpg",
  },
  "spotted-ratfish": {
    author: "Stosh Morency",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Hydrolagus_colliei_8049778.jpg",
  },
  "stoplight-parrotfish": {
    author: "Adona9 at English Wikipedia",
    license: "CC BY-SA 3.0",
    license_url: "http://creativecommons.org/licenses/by-sa/3.0/",
    source: "https://commons.wikimedia.org/wiki/File:Stoplight-parrotfish.jpg",
  },
  "tarpon": {
    author: "Daiju Azuma",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Megalops_atlanticus_by_DaijuAzuma.jpg",
  },
  "torafugu": {
    author: "Totti",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Takifugu_rubripes_AQUAS.jpg",
  },
  "walleye": {
    author: "Engbretson, Eric / U.S. Fish and Wildlife Service",
    license: "Public domain",
    license_url: "",
    source: "https://commons.wikimedia.org/wiki/File:Sander_vitreus.jpg",
  },
  "yelloweye-rockfish": {
    author: "Jason Grant",
    license: "CC BY 4.0",
    license_url: "https://creativecommons.org/licenses/by/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Sebastes_ruberrimus_143567641.jpg",
  },
  "zebra-mbuna": {
    author: "Klaus Rudloff",
    license: "CC BY-SA 4.0",
    license_url: "https://creativecommons.org/licenses/by-sa/4.0",
    source: "https://commons.wikimedia.org/wiki/File:Maylandia_zebra_B.jpg",
  },
};
