/* Fishguesser — the guessable fish, grouped by home region.
 *
 * `region` must match an id in REGIONS (see regions.js); several fish share a
 * region, which is what makes the map worth reading rather than memorising.
 * Photos are linked straight from Wikimedia Commons or iNaturalist rather than
 * stored here, so the game needs a network connection to show them. The URLs point at the CDN
 * thumbnail directly — the path hash is derived from the filename, not the
 * contents, so it stays valid if the file is re-uploaded. Which Commons file
 * each fish uses, and who to credit, is recorded in assets/fish/credits.json;
 * see CREDITS.md. Regenerate the URLs with tools/build_photo_urls.py.
 *
 * Species are picked so their natural range genuinely centres on the region
 * they are filed under — a widespread Indo-Pacific fish would make for an
 * unfair round. */

const FISH = [
  // ---- North Pacific ----
  {
    id: 'sockeye-salmon',
    name: 'Sockeye Salmon',
    sciName: 'Oncorhynchus nerka',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Oncorhynchus_nerka_2.jpg/1280px-Oncorhynchus_nerka_2.jpg',
    region: 'north-pacific',
    fact: 'Sockeye spend years at sea silver, then turn brilliant red with a green head to spawn in the same freshwater stream they hatched in.',
  },
  {
    id: 'yelloweye-rockfish',
    name: 'Yelloweye Rockfish',
    sciName: 'Sebastes ruberrimus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/25_yeye2_frierson_odfw_%288253212034%29.jpg/1280px-25_yeye2_frierson_odfw_%288253212034%29.jpg',
    region: 'north-pacific',
    fact: 'One of the longest-lived fish in the world — individuals over 100 years old have been aged. Growing that slowly makes the species very slow to recover from fishing.',
  },
  {
    id: 'lingcod',
    name: 'Lingcod',
    sciName: 'Ophiodon elongatus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Ophiodon_elongatus_458366655.jpg/1280px-Ophiodon_elongatus_458366655.jpg',
    region: 'north-pacific',
    fact: 'Not a cod at all, but a greenling. Roughly one in five has startling blue-green flesh from a harmless pigment that cooks away white.',
  },
  {
    id: 'california-halibut',
    name: 'California Halibut',
    sciName: 'Paralichthys californicus',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/106810626/large.jpg',
    region: 'north-pacific',
    fact: 'Hatches upright with an eye on each side, then one eye migrates across its skull as it tips over to live flat. Which side it settles on is close to a coin toss — about half end up left-eyed, half right — where most flatfish commit to one.',
  },

  {
    id: 'spotted-ratfish',
    name: 'Spotted Ratfish',
    sciName: 'Hydrolagus colliei',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Hydrolagus_colliei_8049778.jpg/1280px-Hydrolagus_colliei_8049778.jpg',
    region: 'north-pacific',
    fact: 'Not a shark but a chimaera, from a branch that split off before sharks were sharks: it grinds shellfish with permanent tooth plates, and the spine in front of its dorsal fin is venomous.',
  },
  {
    id: 'kelp-greenling',
    name: 'Kelp Greenling',
    sciName: 'Hexagrammos decagrammus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Hexagrammos_decagrammus_hembra.jpg/1280px-Hexagrammos_decagrammus_hembra.jpg',
    region: 'north-pacific',
    fact: 'Males and females look like separate species — he is grey-blue under electric blue spots, she is brown under golden-orange ones — and both carry five lateral lines down each flank where most fish have one.',
  },
  {
    id: 'pacific-spiny-dogfish',
    name: 'Pacific Spiny Dogfish',
    sciName: 'Squalus suckleyi',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Squalus_suckleyi_in_an_aquarium.jpg/1280px-Squalus_suckleyi_in_an_aquarium.jpg',
    region: 'north-pacific',
    fact: 'Carries a mildly venomous spine in front of each dorsal fin, lives past eighty, and is pregnant for about two years — the longest gestation of any shark.',
  },
  {
    id: 'leopard-shark',
    name: 'Leopard Shark',
    sciName: 'Triakis semifasciata',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Triakis_semifasciata_Gratwicke.jpg/1280px-Triakis_semifasciata_Gratwicke.jpg',
    region: 'north-pacific',
    fact: 'Rides the flooding tide up onto mudflats to hunt in water barely deep enough to cover it, then slips back out with the ebb.',
  },
  {
    id: 'sarcastic-fringehead',
    name: 'Sarcastic Fringehead',
    sciName: 'Neoclinus blanchardi',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Sarcastic_fringehead_in_plastic_tube.JPG/1280px-Sarcastic_fringehead_in_plastic_tube.JPG',
    region: 'north-pacific',
    fact: 'Lives in a bottle or an empty shell and defends it by unfolding its whole head into a gaping frill, then wrestling rivals mouth to mouth.',
  },
  {
    id: 'california-sheephead',
    name: 'California Sheephead',
    sciName: 'Semicossyphus pulcher',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/CA_Sheephead%2C_CINMS.jpg/1280px-CA_Sheephead%2C_CINMS.jpg',
    region: 'north-pacific',
    fact: 'Every one starts as a drab female; the largest then turns male, grows a bulbous forehead and a white chin, and looks like a different animal altogether.',
  },
  {
    id: 'garibaldi',
    name: 'Garibaldi',
    sciName: 'Hypsypops rubicundus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Garibaldi_%28Fish%29.jpg/1280px-Garibaldi_%28Fish%29.jpg',
    region: 'north-pacific',
    fact: 'California made it the state marine fish and then made it illegal to take one, so the brightest orange thing on the reef is also among the best protected.',
  },
  {
    id: 'wolf-eel',
    name: 'Wolf-eel',
    sciName: 'Anarrhichthys ocellatus',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/250584063/large.jpg',
    region: 'north-pacific',
    fact: 'Pairs move into a den and stay together for decades, and the jaws that let them crush whole sea urchins give an old male the face of a scowling boxer.',
  },
  {
    id: 'grunt-sculpin',
    name: 'Grunt Sculpin',
    sciName: 'Rhamphocottus richardsonii',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/411378230/large.jpeg',
    region: 'north-pacific',
    fact: 'Barely swims at all: it hops and walks the bottom on finger-like fin rays, and reverses into an empty giant barnacle shell until only its face shows.',
  },
  {
    id: 'giant-sea-bass',
    name: 'Giant Sea Bass',
    sciName: 'Stereolepis gigas',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/712302269/large.jpg',
    region: 'north-pacific',
    fact: 'Passes two metres and 250 kilos in the kelp and booms audibly at anything that crowds it. The young look nothing like it — bright orange with black spots.',
  },
  {
    id: 'cabezon',
    name: 'Cabezon',
    sciName: 'Scorpaenichthys marmoratus',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/716927153/large.jpg',
    region: 'north-pacific',
    fact: 'Turns up red, green or brown depending on where it settled, and a male guarding eggs will sit on them and refuse to be moved. Its roe is poisonous to people.',
  },
  {
    id: 'china-rockfish',
    name: 'China Rockfish',
    sciName: 'Sebastes nebulosus',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/340744477/large.jpg',
    region: 'north-pacific',
    fact: 'Barely travels once it has a home: one crevice can hold the same fish for decades, and they live well past eighty.',
  },
  {
    id: 'swell-shark',
    name: 'Swell Shark',
    sciName: 'Cephaloscyllium ventriosum',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/583464564/large.jpg',
    region: 'north-pacific',
    fact: 'Gulps seawater until it has doubled in girth, then wedges itself into a crevice nothing can drag it out of. Its skin glows green under blue light.',
  },
  // ---- Caribbean Sea ----
  {
    id: 'queen-angelfish',
    name: 'Queen Angelfish',
    sciName: 'Holacanthus ciliaris',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Pez_%C3%A1ngel_reina_%28Holacanthus_ciliaris%29%2C_Cozumel%2C_M%C3%A9xico%2C_2025-12-20%2C_DD_134.jpg/1280px-Pez_%C3%A1ngel_reina_%28Holacanthus_ciliaris%29%2C_Cozumel%2C_M%C3%A9xico%2C_2025-12-20%2C_DD_134.jpg',
    region: 'caribbean',
    fact: 'Named for the ringed blue "crown" on its forehead. It grazes mostly on sponges around Caribbean and Floridian reefs.',
  },
  {
    id: 'nassau-grouper',
    name: 'Nassau Grouper',
    sciName: 'Epinephelus striatus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Epinephelus_striatus_2.jpg/1280px-Epinephelus_striatus_2.jpg',
    region: 'caribbean',
    fact: 'Gathers by the thousand to spawn at the same reefs each winter full moon — predictable enough that fishing collapsed the species to critically endangered.',
  },
  {
    id: 'stoplight-parrotfish',
    name: 'Stoplight Parrotfish',
    sciName: 'Sparisoma viride',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Stoplight-parrotfish.jpg/1280px-Stoplight-parrotfish.jpg',
    region: 'caribbean',
    fact: 'Scrapes algae off coral with a beak of fused teeth and excretes the ground-up rock as fine white sand — a single fish can make hundreds of kilos of beach a year.',
  },
  {
    id: 'tarpon',
    name: 'Atlantic Tarpon',
    sciName: 'Megalops atlanticus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Megalops_atlanticus_by_DaijuAzuma.jpg/1280px-Megalops_atlanticus_by_DaijuAzuma.jpg',
    region: 'caribbean',
    fact: 'Gulps air at the surface through a lung-like swim bladder, which lets it survive in stagnant backwaters that would suffocate its predators.',
  },

  {
    id: 'atlantic-blue-tang',
    name: 'Atlantic Blue Tang',
    sciName: 'Acanthurus coeruleus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Pez_cirujano_azul_%28Acanthurus_coeruleus%29%2C_Cozumel%2C_M%C3%A9xico%2C_2025-12-20%2C_DD_75.jpg/1280px-Pez_cirujano_azul_%28Acanthurus_coeruleus%29%2C_Cozumel%2C_M%C3%A9xico%2C_2025-12-20%2C_DD_75.jpg',
    region: 'caribbean',
    fact: 'Hatches bright yellow and darkens to deep blue as it matures, keeping a scalpel-sharp hinged spine at the base of the tail that it swings sideways like a switchblade.',
  },
  {
    id: 'foureye-butterflyfish',
    name: 'Foureye Butterflyfish',
    sciName: 'Chaetodon capistratus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Chaetodon_capistratus_394406658.jpg/1280px-Chaetodon_capistratus_394406658.jpg',
    region: 'caribbean',
    fact: 'The big ringed spot near the tail is a decoy eye, and the real one is hidden in a dark band — a predator aims for the wrong end and the fish escapes forwards.',
  },
  {
    id: 'queen-triggerfish',
    name: 'Queen Triggerfish',
    sciName: 'Balistes vetula',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Queen_Triggerfish_Balistes_vetula.jpg/1280px-Queen_Triggerfish_Balistes_vetula.jpg',
    region: 'caribbean',
    fact: 'Wedges itself into a crevice by locking a stout dorsal spine upright; a smaller spine behind it works the catch, and until that is released the fish cannot be pulled out.',
  },
  {
    id: 'bonnethead',
    name: 'Bonnethead',
    sciName: 'Sphyrna tiburo',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Bonnethead_shark_Aquarium_of_the_Pacific.jpg/1280px-Bonnethead_shark_Aquarium_of_the_Pacific.jpg',
    region: 'caribbean',
    fact: 'The only shark known to properly digest plants: seagrass makes up more than half of what it eats, and it grows on the stuff.',
  },
  {
    id: 'nurse-shark',
    name: 'Nurse Shark',
    sciName: 'Ginglymostoma cirratum',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Ginglymostoma_cirratum_utila.jpg/1280px-Ginglymostoma_cirratum_utila.jpg',
    region: 'caribbean',
    fact: 'Sucks prey out of rock crevices hard enough that divers can hear the slurp, and spends the day piled up motionless with dozens of others.',
  },
  {
    id: 'spanish-hogfish',
    name: 'Spanish Hogfish',
    sciName: 'Bodianus rufus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Bodianus_rufus_%2846598633625%29.jpg/1280px-Bodianus_rufus_%2846598633625%29.jpg',
    region: 'caribbean',
    fact: 'Young ones set up as cleaners, picking parasites off fish easily big enough to eat them, and give up the trade once they are grown.',
  },
  {
    id: 'rock-beauty',
    name: 'Rock Beauty',
    sciName: 'Holacanthus tricolor',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Chabelita_tricolor_%28Holacanthus_tricolor%29%2C_Cozumel%2C_M%C3%A9xico%2C_2025-12-20%2C_DD_104.jpg/1280px-Chabelita_tricolor_%28Holacanthus_tricolor%29%2C_Cozumel%2C_M%C3%A9xico%2C_2025-12-20%2C_DD_104.jpg',
    region: 'caribbean',
    fact: 'Juveniles are entirely yellow but for one blue-ringed spot, and the black spreads outward from that spot as the fish grows until it covers most of the body.',
  },
  {
    id: 'royal-gramma',
    name: 'Royal Gramma',
    sciName: 'Gramma loreto',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Gramma_loreto_01.jpg/1280px-Gramma_loreto_01.jpg',
    region: 'caribbean',
    fact: 'Holds itself square to whatever surface it is nearest, so a fish tucked under an overhang hangs there calmly upside down.',
  },
  {
    id: 'french-angelfish',
    name: 'French Angelfish',
    sciName: 'Pomacanthus paru',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/French_Angelfish_in_Profile_%2847447869022%29.jpg/1280px-French_Angelfish_in_Profile_%2847447869022%29.jpg',
    region: 'caribbean',
    fact: 'Pairs stay together for years and patrol a shared territory, and juveniles run cleaning stations that even predators queue up at rather than eat.',
  },
  {
    id: 'southern-stingray',
    name: 'Southern Stingray',
    sciName: 'Hypanus americanus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Dasyatis_americana_%282008%29.jpg/1280px-Dasyatis_americana_%282008%29.jpg',
    region: 'caribbean',
    fact: 'Flaps its wings to blow a pit in the sand, drops in and vanishes but for two eyes, then pumps water through the holes behind them rather than through a buried mouth.',
  },
  {
    id: 'yellowhead-jawfish',
    name: 'Yellowhead Jawfish',
    sciName: 'Opistognathus aurifrons',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/173629583/large.jpg',
    region: 'caribbean',
    fact: 'Builds a vertical shaft in the seabed and shores the walls up with stones carried one at a time in its mouth, then hovers above the door ready to drop in tail-first.',
  },
  {
    id: 'peacock-flounder',
    name: 'Peacock Flounder',
    sciName: 'Bothus lunatus',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/60009071/large.jpg',
    region: 'caribbean',
    fact: 'Redraws the pigment in its skin to match whatever it lands on — gravel, sand, even a chequerboard — in a few seconds, working from what its eyes report.',
  },
  {
    id: 'caribbean-reef-octopus',
    name: 'Caribbean Reef Octopus',
    sciName: 'Octopus briareus',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/261936025/large.jpeg',
    region: 'caribbean',
    fact: 'Hunts by parachuting its webbed arms over a whole coral head at once, then feeling underneath for whatever is sheltering in it.',
  },
  // ---- Amazon Basin ----
  {
    id: 'red-bellied-piranha',
    name: 'Red-bellied Piranha',
    sciName: 'Pygocentrus nattereri',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Pygocentrus_nattereri_-_Karlsruhe_Zoo_01.jpg/1280px-Pygocentrus_nattereri_-_Karlsruhe_Zoo_01.jpg',
    region: 'amazon',
    fact: 'Far less bloodthirsty than its reputation — it mostly scavenges and eats insects, and shoals largely for protection from predators.',
  },
  {
    id: 'arapaima',
    name: 'Arapaima',
    sciName: 'Arapaima gigas',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Arapaima_gigas_5147.jpg/1280px-Arapaima_gigas_5147.jpg',
    region: 'amazon',
    fact: 'One of the largest freshwater fish alive, past three metres. It breathes air through a lung-like swim bladder and drowns if kept from the surface.',
  },
  {
    id: 'discus',
    name: 'Discus',
    sciName: 'Symphysodon aequifasciatus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Symphysodon_aequifasciatus_-_Karlsruhe_Zoo_04.jpg/1280px-Symphysodon_aequifasciatus_-_Karlsruhe_Zoo_04.jpg',
    region: 'amazon',
    fact: 'Both parents grow a nutritious skin mucus that their fry graze on for the first few weeks — a fish equivalent of nursing.',
  },
  {
    id: 'electric-eel',
    name: 'Electric Eel',
    sciName: 'Electrophorus electricus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Electrophorus_electricus_in_Ouwehands_Dierenpark_01.jpg/1280px-Electrophorus_electricus_in_Ouwehands_Dierenpark_01.jpg',
    region: 'amazon',
    fact: 'Not an eel but a knifefish. It can discharge around 600 volts, and has been seen leaping to press the shock directly into a large animal.',
  },

  {
    id: 'oscar',
    name: 'Oscar',
    sciName: 'Astronotus ocellatus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Astronotus_ocellatus_-_side_%28aka%29.jpg/1280px-Astronotus_ocellatus_-_side_%28aka%29.jpg',
    region: 'amazon',
    fact: 'The false eyespot on its tail is thought to send a striking predator to the wrong end, and it will lie motionless on its side playing dead until something curious swims close enough to eat.',
  },
  {
    id: 'cardinal-tetra',
    name: 'Cardinal Tetra',
    sciName: 'Paracheirodon axelrodi',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Cardinal_Paracheirodon_axelrodi_%283%29.jpg/1280px-Cardinal_Paracheirodon_axelrodi_%283%29.jpg',
    region: 'amazon',
    fact: 'The blue stripe is not pigment but stacked crystal plates bending light, and the fish can tilt them — the colour drains away to near black while it sleeps.',
  },
  {
    id: 'redtail-catfish',
    name: 'Redtail Catfish',
    sciName: 'Phractocephalus hemioliopterus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Hal_-_Phractocephalus_hemioliopterus_-_1.jpg/1280px-Hal_-_Phractocephalus_hemioliopterus_-_1.jpg',
    region: 'amazon',
    fact: 'Swallows whole anything that fits and passes a metre in length, which is why a palm-sized one sold for a home aquarium rarely stays in it.',
  },
  {
    id: 'tambaqui',
    name: 'Tambaqui',
    sciName: 'Colossoma macropomum',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Black_pacu.jpg/1280px-Black_pacu.jpg',
    region: 'amazon',
    fact: 'A relative of the piranha that gave up meat for fruit, waiting under flooded forest trees to crack fallen seeds with molars unnervingly like human teeth.',
  },
  {
    id: 'peacock-bass',
    name: 'Peacock Bass',
    sciName: 'Cichla ocellaris',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Cichla_ocellaris.jpg/1280px-Cichla_ocellaris.jpg',
    region: 'amazon',
    fact: 'Not a bass at all but a giant cichlid, and both parents guard the fry in a shoal so tight it moves like one animal.',
  },
  {
    id: 'silver-arowana',
    name: 'Silver Arowana',
    sciName: 'Osteoglossum bicirrhosum',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/359882847/large.jpeg',
    region: 'amazon',
    fact: 'Launches clear of the water to snatch insects, spiders and even small birds off branches a metre above the surface.',
  },
  {
    id: 'freshwater-angelfish',
    name: 'Freshwater Angelfish',
    sciName: 'Pterophyllum scalare',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/487620135/large.jpg',
    region: 'amazon',
    fact: 'That flattened disc of a body slips edge-on between flooded roots and stems, where a normally built fish would jam.',
  },
  {
    id: 'trahira',
    name: 'Trahira',
    sciName: 'Hoplias malabaricus',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/368268376/large.jpeg',
    region: 'amazon',
    fact: 'Hangs motionless in shallow weed behind a set of conical teeth too big to shut away, and gulps air to sit out a drought as its pool shrinks around it.',
  },
  {
    id: 'severum',
    name: 'Severum',
    sciName: 'Heros efasciatus',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/642205172/large.jpg',
    region: 'amazon',
    fact: 'Both parents dig a pit for the fry, fan the eggs in shifts and spend days steering the strays back into the huddle.',
  },
  {
    id: 'banded-leporinus',
    name: 'Banded Leporinus',
    sciName: 'Leporinus fasciatus',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/187562683/large.jpg',
    region: 'amazon',
    fact: 'Feeds nose-down at a steep angle, nipping algae and fallen fruit, and the heavy black bars break its outline against flooded branches.',
  },
  // ---- North Atlantic ----
  {
    id: 'atlantic-cod',
    name: 'Atlantic Cod',
    sciName: 'Gadus morhua',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Atlantic_Cod%2C_Atlantischer_Kabeljau_%28Gadus_morhua%29.jpg/1280px-Atlantic_Cod%2C_Atlantischer_Kabeljau_%28Gadus_morhua%29.jpg',
    region: 'north-atlantic',
    fact: 'Three dorsal fins and a whisker-like chin barbel it uses to taste the seabed. Centuries of fishing collapsed the Grand Banks stock in 1992.',
  },
  {
    id: 'atlantic-wolffish',
    name: 'Atlantic Wolffish',
    sciName: 'Anarhichas lupus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Anarhichas-lupus-Atlanterhavsparken.jpg/1280px-Anarhichas-lupus-Atlanterhavsparken.jpg',
    region: 'north-atlantic',
    fact: 'Crushes sea urchins and clams with conical fangs, and makes its own antifreeze so its blood keeps flowing in near-freezing water.',
  },
  {
    id: 'atlantic-mackerel',
    name: 'Atlantic Mackerel',
    sciName: 'Scomber scombrus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Atlantic_mackerel_%28Scomber_scombrus%29.jpg/1280px-Atlantic_mackerel_%28Scomber_scombrus%29.jpg',
    region: 'north-atlantic',
    fact: 'Has no swim bladder, so it must keep swimming or sink. The wavy black bars across its back are as individual as a fingerprint.',
  },
  {
    id: 'lumpfish',
    name: 'Lumpfish',
    sciName: 'Cyclopterus lumpus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Lumpfish-Cyclopterus_lumpus.jpg/1280px-Lumpfish-Cyclopterus_lumpus.jpg',
    region: 'north-atlantic',
    fact: 'Its pelvic fins are fused into a suction disc that clamps it to rock against the swell. The male guards the eggs alone, fanning them for weeks.',
  },

  {
    id: 'atlantic-salmon',
    name: 'Atlantic Salmon',
    sciName: 'Salmo salar',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Laks_i_laksetrappa.JPG/1280px-Laks_i_laksetrappa.JPG',
    region: 'north-atlantic',
    fact: 'Unlike its Pacific cousins it does not always die after spawning — a few survive the run, slip back down to the sea and return to breed a second or third time.',
  },
  {
    id: 'cuckoo-wrasse',
    name: 'Cuckoo Wrasse',
    sciName: 'Labrus mixtus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Labrus_mixtus_23_BG.jpg/1280px-Labrus_mixtus_23_BG.jpg',
    region: 'north-atlantic',
    fact: 'Every one hatches female and dull orange. The largest of a group then turns male and repaints itself in electric blue and yellow.',
  },
  {
    id: 'basking-shark',
    name: 'Basking Shark',
    sciName: 'Cetorhinus maximus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Cetorhinus_maximus_atlantic.jpg/1280px-Cetorhinus_maximus_atlantic.jpg',
    region: 'north-atlantic',
    fact: 'The second-largest fish alive strains plankton by cruising with its mouth held wide open, filtering something like two thousand tonnes of water an hour.',
  },
  {
    id: 'sea-lamprey',
    name: 'Sea Lamprey',
    sciName: 'Petromyzon marinus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Petromyzon_marinus_282284066_%28cropped%29.jpg/1280px-Petromyzon_marinus_282284066_%28cropped%29.jpg',
    region: 'north-atlantic',
    fact: 'Older than jaws themselves: it has no hinged mouth, only a rasping funnel of teeth it fastens to a larger fish to drink from.',
  },
  {
    id: 'smallspotted-catshark',
    name: 'Small-spotted Catshark',
    sciName: 'Scyliorhinus canicula',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Ecomare_-_hondshaai_%28hondshaai-zeeaquarium-1108-sd%29.jpg/1280px-Ecomare_-_hondshaai_%28hondshaai-zeeaquarium-1108-sd%29.jpg',
    region: 'north-atlantic',
    fact: 'Lays its eggs in tough horny purses with tendrils at each corner that wind around seaweed like a vine, which is why beachcombers find empty ones by the hundred.',
  },
  {
    id: 'ballan-wrasse',
    name: 'Ballan Wrasse',
    sciName: 'Labrus bergylta',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/54816226/large.jpg',
    region: 'north-atlantic',
    fact: 'Salmon farms keep them on the payroll as live-in cleaners, picking sea lice off the stock.',
  },
  {
    id: 'corkwing-wrasse',
    name: 'Corkwing Wrasse',
    sciName: 'Symphodus melops',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/262631727/large.jpeg',
    region: 'north-atlantic',
    fact: 'Males weave a nest out of seaweed; smaller males take on female colouring to slip inside and fertilise the eggs.',
  },
  {
    id: 'european-conger',
    name: 'European Conger',
    sciName: 'Conger conger',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/562789043/large.jpg',
    region: 'north-atlantic',
    fact: 'The largest eel in the sea, past three metres in wrecks and rock holes — and it dies after one spawning run to deep water.',
  },
  {
    id: 'tompot-blenny',
    name: 'Tompot Blenny',
    sciName: 'Parablennius gattorugine',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/91158104/large.jpeg',
    region: 'north-atlantic',
    fact: 'Props itself upright on its pectoral fins in a rock hole under a pair of branched tentacles, and the same fish will hold the same hole for years.',
  },
  {
    id: 'common-dragonet',
    name: 'Common Dragonet',
    sciName: 'Callionymus lyra',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/609018028/large.jpg',
    region: 'north-atlantic',
    fact: 'The male\'s front dorsal fin unfolds into a sail taller than he is, put up only to court a female or to face down a rival.',
  },
  {
    id: 'sea-scorpion',
    name: 'Long-spined Sea Scorpion',
    sciName: 'Taurulus bubalis',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/443945449/large.jpeg',
    region: 'north-atlantic',
    fact: 'Shifts colour over days to settle into whatever weed it is living in, so the same species turns up red, green or brown depending where it landed.',
  },
  {
    id: 'garfish',
    name: 'Garfish',
    sciName: 'Belone belone',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/222165464/large.jpeg',
    region: 'north-atlantic',
    fact: 'Its bones are a vivid green — a harmless pigment called biliverdin — which has never done the fish any favours on the slab.',
  },
  {
    id: 'sand-tiger-shark',
    name: 'Sand Tiger Shark',
    sciName: 'Carcharias taurus',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/528604108/large.jpg',
    region: 'north-atlantic',
    fact: 'Looks murderous — the teeth show even with the mouth shut — and is famously placid. It gulps air at the surface and holds it in its stomach to hang motionless in midwater.',
  },
  // ---- Mediterranean Sea ----
  {
    id: 'gilt-head-bream',
    name: 'Gilt-head Bream',
    sciName: 'Sparus aurata',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Brest_-_Oc%C3%A9anopolis_-_2015_-_051.jpg/1280px-Brest_-_Oc%C3%A9anopolis_-_2015_-_051.jpg',
    region: 'mediterranean',
    fact: 'Named for the golden band between its eyes. Every one starts life male and some later become female — a trick called protandry.',
  },
  {
    id: 'dusky-grouper',
    name: 'Dusky Grouper',
    sciName: 'Epinephelus marginatus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Mero_%28Epinephelus_marginatus%29%2C_Cabo_de_Palos%2C_Espa%C3%B1a%2C_2022-07-15%2C_DD_34.jpg/1280px-Mero_%28Epinephelus_marginatus%29%2C_Cabo_de_Palos%2C_Espa%C3%B1a%2C_2022-07-15%2C_DD_34.jpg',
    region: 'mediterranean',
    fact: 'A long-lived rocky-reef ambusher that holds the same territory for years. All are born female and the largest turn male around age twelve.',
  },
  {
    id: 'european-seabass',
    name: 'European Seabass',
    sciName: 'Dicentrarchus labrax',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Dicentrarchus_labrax_LoroParqueTenerife_seabass_IMG_4959.JPG/1280px-Dicentrarchus_labrax_LoroParqueTenerife_seabass_IMG_4959.JPG',
    region: 'mediterranean',
    fact: 'A fast coastal hunter that pushes far into brackish lagoons and river mouths, tolerating water from nearly fresh to fully salt.',
  },
  {
    id: 'mediterranean-moray',
    name: 'Mediterranean Moray',
    sciName: 'Muraena helena',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Morena_del_Mediterr%C3%A1neo_%28Muraena_helena%29%2C_Catania%2C_Sicilia%2C_Italia%2C_2025-04-05%2C_DD_35.jpg/1280px-Morena_del_Mediterr%C3%A1neo_%28Muraena_helena%29%2C_Catania%2C_Sicilia%2C_Italia%2C_2025-04-05%2C_DD_35.jpg',
    region: 'mediterranean',
    fact: 'Has a second set of jaws in its throat that lunge forward to drag prey down, since it cannot suck food in the way most fish do.',
  },

  {
    id: 'red-scorpionfish',
    name: 'Red Scorpionfish',
    sciName: 'Scorpaena scrofa',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Red_Scorpionfish_%28cropped%29.jpg/1280px-Red_Scorpionfish_%28cropped%29.jpg',
    region: 'mediterranean',
    fact: 'Sits motionless under a fringe of skin tassels until prey drifts within reach, then swallows it in a gulp measured in milliseconds; the spines along its back are venomous.',
  },
  {
    id: 'striped-red-mullet',
    name: 'Striped Red Mullet',
    sciName: 'Mullus surmuletus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Mullus_surmuletus_Cala_Gracio.jpg/1280px-Mullus_surmuletus_Cala_Gracio.jpg',
    region: 'mediterranean',
    fact: 'Rakes buried prey out of the sand with a pair of long chin barbels it tastes with. Roman diners paid absurd sums for a large one and kept it alive at the table to watch its colours change.',
  },
  {
    id: 'angelshark',
    name: 'Angelshark',
    sciName: 'Squatina squatina',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Squatina_squatina_120867948.jpg/1280px-Squatina_squatina_120867948.jpg',
    region: 'mediterranean',
    fact: 'Lies buried with only its eyes above the sand and strikes upward in about a tenth of a second; once so common it was a market staple, now critically endangered.',
  },
  {
    id: 'flying-gurnard',
    name: 'Flying Gurnard',
    sciName: 'Dactylopterus volitans',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/FlyingGurnard.jpg/1280px-FlyingGurnard.jpg',
    region: 'mediterranean',
    fact: 'Cannot fly at all: the enormous blue-spangled fans are opened on the sea floor to startle whatever is chasing it, and it walks on the front rays of its pelvic fins.',
  },
  {
    id: 'ornate-wrasse',
    name: 'Ornate Wrasse',
    sciName: 'Thalassoma pavo',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Thalassoma_pavo_male.jpg/1280px-Thalassoma_pavo_male.jpg',
    region: 'mediterranean',
    fact: 'Born female and barred in orange; the largest of a group then turns male and repaints itself in green and blue.',
  },
  {
    id: 'marbled-electric-ray',
    name: 'Marbled Electric Ray',
    sciName: 'Torpedo marmorata',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Torpedo_marmorata_%2820150825%29_01.jpg/1280px-Torpedo_marmorata_%2820150825%29_01.jpg',
    region: 'mediterranean',
    fact: 'Two blocks of muscle behind the eyes are wired into batteries that deliver about 200 volts, enough to stun a fish outright and to make a careless hand let go.',
  },
  {
    id: 'painted-comber',
    name: 'Painted Comber',
    sciName: 'Serranus scriba',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/267427430/large.jpg',
    region: 'mediterranean',
    fact: 'Carries working ovaries and testes at once, and the blue scribble across its cheek is different on every fish.',
  },
  {
    id: 'mediterranean-damselfish',
    name: 'Mediterranean Damselfish',
    sciName: 'Chromis chromis',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/340635744/large.jpg',
    region: 'mediterranean',
    fact: 'The adults are a plain sooty brown, but the juveniles are an electric neon blue that fades as they grow.',
  },
  {
    id: 'salema',
    name: 'Salema',
    sciName: 'Sarpa salpa',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/267908104/large.jpg',
    region: 'mediterranean',
    fact: 'Eating one can bring on hallucinations that last for days — the fish was reportedly taken recreationally in Roman times.',
  },
  {
    id: 'mediterranean-cardinalfish',
    name: 'Mediterranean Cardinalfish',
    sciName: 'Apogon imberbis',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/407529574/large.jpg',
    region: 'mediterranean',
    fact: 'Spends the day hanging under cave roofs and ledges, often upside down, on an eye built for picking prey out of near-darkness.',
  },
  {
    id: 'two-banded-seabream',
    name: 'Two-banded Seabream',
    sciName: 'Diplodus vulgaris',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/136804197/large.jpg',
    region: 'mediterranean',
    fact: 'Every one begins life male and a share of them turn female with age, while the two black bars — one at the neck, one at the tail — stay put throughout.',
  },
  {
    id: 'yellowmouth-barracuda',
    name: 'Yellowmouth Barracuda',
    sciName: 'Sphyraena viridensis',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/458133929/large.jpg',
    region: 'mediterranean',
    fact: 'Hangs almost still in mid-water in a loose pack, then closes the last few metres onto a fish faster than the eye follows.',
  },
  {
    id: 'common-cuttlefish',
    name: 'Common Cuttlefish',
    sciName: 'Sepia officinalis',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/442345541/large.jpeg',
    region: 'mediterranean',
    fact: 'Colour-blind, yet it matches any background it settles on — and it rolls waves of colour down its skin to stupefy a crab while it closes the distance.',
  },
  // ---- Congo Basin ----
  {
    id: 'goliath-tigerfish',
    name: 'Goliath Tigerfish',
    sciName: 'Hydrocynus goliath',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Hydrocynus_goliath.jpg/1280px-Hydrocynus_goliath.jpg',
    region: 'congo',
    fact: 'Grows past 1.5 m and 50 kg, with 32 interlocking dagger teeth. It hunts by sight in fast, turbid water where few predators can.',
  },
  {
    id: 'elephantnose-fish',
    name: 'Elephantnose Fish',
    sciName: 'Gnathonemus petersii',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Mormyridae_Gnathonemus_petersii_2.jpg/1280px-Mormyridae_Gnathonemus_petersii_2.jpg',
    region: 'congo',
    fact: 'Navigates pitch-dark, muddy water by reading distortions in its own weak electric field, and devotes a larger share of its body energy to its brain than a human does.',
  },
  {
    id: 'congo-tetra',
    name: 'Congo Tetra',
    sciName: 'Phenacogrammus interruptus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Phenacogrammus_interruptus_1.jpg/1280px-Phenacogrammus_interruptus_1.jpg',
    region: 'congo',
    fact: 'Its scales scatter light into shifting bands of blue, gold and violet, and older males trail long feathered extensions from the middle of the tail.',
  },
  {
    id: 'african-butterflyfish',
    name: 'African Butterflyfish',
    sciName: 'Pantodon buchholzi',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Pantodon_buchholzi_K%C3%B6ln_Zoo_31122014_1.jpg/1280px-Pantodon_buchholzi_K%C3%B6ln_Zoo_31122014_1.jpg',
    region: 'congo',
    fact: 'Hangs motionless at the surface watching upward for insects, and can burst clear of the water on its huge wing-like pectoral fins.',
  },

  {
    id: 'six-barred-distichodus',
    name: 'Six-barred Distichodus',
    sciName: 'Distichodus sexfasciatus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Distichodontidae_-_Distichodus_sexfasciatus.JPG/1280px-Distichodontidae_-_Distichodus_sexfasciatus.JPG',
    region: 'congo',
    fact: 'The bold black bars that make young fish so striking fade as it grows, until a metre-long adult looks like an entirely different species.',
  },
  {
    id: 'ornate-bichir',
    name: 'Ornate Bichir',
    sciName: 'Polypterus ornatipinnis',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Polypterus_ornatipinnis_VA_01.jpg/1280px-Polypterus_ornatipinnis_VA_01.jpg',
    region: 'congo',
    fact: 'Breathes air through a pair of true lungs and will drown if it cannot reach the surface — a body plan little changed since before the dinosaurs.',
  },
  {
    id: 'reedfish',
    name: 'Reedfish',
    sciName: 'Erpetoichthys calabaricus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Erpetoichthys_calabaricus_01.jpg/1280px-Erpetoichthys_calabaricus_01.jpg',
    region: 'congo',
    fact: 'A snake-shaped survivor from before the dinosaurs, with a pair of working lungs; it drowns if it cannot reach the surface, and will crawl overland between pools.',
  },
  {
    id: 'upside-down-catfish',
    name: 'Upside-down Catfish',
    sciName: 'Synodontis nigriventris',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/423397251/large.jpg',
    region: 'congo',
    fact: 'Swims on its back to graze the undersides of leaves and logs, with its counter-shading reversed to match: dark belly, pale back.',
  },
  {
    id: 'electric-catfish',
    name: 'Electric Catfish',
    sciName: 'Malapterurus electricus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Malapterurus_electricus_1.jpg/1280px-Malapterurus_electricus_1.jpg',
    region: 'congo',
    fact: 'Muscle wrapped around almost its entire body fires a shock of some 350 volts — Egyptian tomb carvers were recording the fish more than four thousand years ago.',
  },
  {
    id: 'leopard-bushfish',
    name: 'Leopard Bushfish',
    sciName: 'Ctenopoma acutirostre',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Ctenopoma_acutirostre_1.JPG/1280px-Ctenopoma_acutirostre_1.JPG',
    region: 'congo',
    fact: 'Hangs head-down among drowned branches looking like a rotting leaf until something small swims within reach, and gulps air at the surface through a labyrinth organ when the water runs short of oxygen.',
  },
  // ---- East African Rift Lakes ----
  {
    id: 'electric-yellow-cichlid',
    name: 'Electric Yellow Cichlid',
    sciName: 'Labidochromis caeruleus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Labidochromis_caeruleus_%28male%29.jpg/1280px-Labidochromis_caeruleus_%28male%29.jpg',
    region: 'rift-lakes',
    fact: 'A mouthbrooder: the female carries her eggs and fry in her mouth for around three weeks, not eating the whole time.',
  },
  {
    id: 'frontosa',
    name: 'Frontosa',
    sciName: 'Cyphotilapia frontosa',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Cyphotilapia_frontosa_-_Karlsruhe_Zoo_01.jpg/1280px-Cyphotilapia_frontosa_-_Karlsruhe_Zoo_01.jpg',
    region: 'rift-lakes',
    fact: 'Found only in Lake Tanganyika, hunting in deep water down to 100 m. Dominant males develop a large fatty hump above the eyes.',
  },
  {
    id: 'zebra-mbuna',
    name: 'Zebra Mbuna',
    sciName: 'Maylandia zebra',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Maylandia_zebra_B.jpg/1280px-Maylandia_zebra_B.jpg',
    region: 'rift-lakes',
    fact: 'One of the rock-dwelling "mbuna" of Lake Malawi, where hundreds of cichlid species evolved from a handful of ancestors in under a million years.',
  },
  {
    id: 'malawi-eyebiter',
    name: 'Malawi Eyebiter',
    sciName: 'Dimidiochromis compressiceps',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Cichlidae_-_Dimidiochromis_compressiceps.JPG/1280px-Cichlidae_-_Dimidiochromis_compressiceps.JPG',
    region: 'rift-lakes',
    fact: 'Hunts hanging head-down among reed stems, its blade-thin body almost invisible end-on until it strikes.',
  },

  {
    id: 'white-spotted-cichlid',
    name: 'White-spotted Cichlid',
    sciName: 'Tropheus duboisi',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/%E7%8F%8D%E7%8F%A0%E8%9D%B4%E8%9D%B6_Tropheus_duboisi_%28Marlier%2C_1959%29_-_panoramio.jpg/1280px-%E7%8F%8D%E7%8F%A0%E8%9D%B4%E8%9D%B6_Tropheus_duboisi_%28Marlier%2C_1959%29_-_panoramio.jpg',
    region: 'rift-lakes',
    fact: 'Juveniles are jet black under a scatter of brilliant white spots. The spots fade as the fish matures until nothing is left but a dark body crossed by one broad pale band.',
  },
  {
    id: 'cuckoo-catfish',
    name: 'Cuckoo Catfish',
    sciName: 'Synodontis multipunctatus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Synodontis-multipunctatus.jpg/1280px-Synodontis-multipunctatus.jpg',
    region: 'rift-lakes',
    fact: 'Slips its own eggs into a mouthbrooding cichlid\'s clutch as she gathers them up. The catfish hatch first and eat her young from inside her mouth.',
  },
  {
    id: 'peacock-cichlid',
    name: 'Peacock Cichlid',
    sciName: 'Aulonocara stuartgranti',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/327643275/large.jpg',
    region: 'rift-lakes',
    fact: 'Hovers with its face pressed to the sand, listening through pits along its jaw for invertebrates moving underneath.',
  },
  {
    id: 'blunthead-cichlid',
    name: 'Blunthead Cichlid',
    sciName: 'Tropheus moorii',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Tropheus_moorii_%27Moliro%27_-_Karlsruhe_Zoo_01.jpg/1280px-Tropheus_moorii_%27Moliro%27_-_Karlsruhe_Zoo_01.jpg',
    region: 'rift-lakes',
    fact: 'Every stretch of rocky shore in Lake Tanganyika has its own colour form, and a few kilometres of open sand is enough to keep them apart.',
  },
  {
    id: 'golden-mbuna',
    name: 'Golden Mbuna',
    sciName: 'Melanochromis auratus',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/237366321/large.jpeg',
    region: 'rift-lakes',
    fact: 'Females and young are gold with black stripes; a male turns the pattern inside out as he matures, ending up near-black with gold lines.',
  },
  {
    id: 'fairy-cichlid',
    name: 'Fairy Cichlid',
    sciName: 'Neolamprologus brichardi',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Neolamprologus_brichardi_LoroParqueTenerife_princess_of_burundi_IMG_5384.JPG/1280px-Neolamprologus_brichardi_LoroParqueTenerife_princess_of_burundi_IMG_5384.JPG',
    region: 'rift-lakes',
    fact: 'Grown offspring stay home instead of leaving, guarding and fanning their parents\' next brood, so a single rock face in Lake Tanganyika can hold a colony hundreds strong across several generations.',
  },
  // ---- Coral Triangle ----
  {
    id: 'mandarinfish',
    name: 'Mandarinfish',
    sciName: 'Synchiropus splendidus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Synchiropus_splendidus_2_Luc_Viatour.jpg/1280px-Synchiropus_splendidus_2_Luc_Viatour.jpg',
    region: 'coral-triangle',
    fact: 'One of only two animals known to make blue with cellular pigment rather than structural colour. It has no scales — just toxic, foul-smelling slime.',
  },
  {
    id: 'clown-anemonefish',
    name: 'Clown Anemonefish',
    sciName: 'Amphiprion ocellaris',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Amphiprion_ocellaris_%28Clown_anemonefish%29_by_Nick_Hobgood.jpg/1280px-Amphiprion_ocellaris_%28Clown_anemonefish%29_by_Nick_Hobgood.jpg',
    region: 'coral-triangle',
    fact: 'Coats itself in mucus to live unstung among anemone tentacles. Every one is born male; when the resident female dies, her mate becomes female.',
  },
  {
    id: 'banggai-cardinalfish',
    name: 'Banggai Cardinalfish',
    sciName: 'Pterapogon kauderni',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Banggai-Kardinalbarsch_Pterapogon_kauderni.jpg/1280px-Banggai-Kardinalbarsch_Pterapogon_kauderni.jpg',
    region: 'coral-triangle',
    fact: 'Wild populations live only around Indonesia’s Banggai Islands — a range smaller than most cities. Males brood the eggs, then the hatched young, in their mouths.',
  },
  {
    id: 'ribbon-eel',
    name: 'Ribbon Eel',
    sciName: 'Rhinomuraena quaesita',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Anguila_list%C3%B3n_azul_%28Rhinomuraena_quaesita%29%2C_Anilao%2C_Filipinas%2C_2023-08-23%2C_DD_60.jpg/1280px-Anguila_list%C3%B3n_azul_%28Rhinomuraena_quaesita%29%2C_Anilao%2C_Filipinas%2C_2023-08-23%2C_DD_60.jpg',
    region: 'coral-triangle',
    fact: 'Every one starts black as a juvenile, turns blue and yellow as a male, then yellow as a female — the same fish in three different liveries.',
  },

  {
    id: 'pygmy-seahorse',
    name: 'Pygmy Seahorse',
    sciName: 'Hippocampus bargibanti',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Pygmy_seahorse_%28Hippocampus_bargibanti%29_%2816245385685%29.jpg/1280px-Pygmy_seahorse_%28Hippocampus_bargibanti%29_%2816245385685%29.jpg',
    region: 'coral-triangle',
    fact: 'Under two centimetres long and so exactly matched to the gorgonian coral it grips that science only noticed it in 1969, when a collected sea fan reached the laboratory with seahorses still aboard.',
  },
  {
    id: 'harlequin-sweetlips',
    name: 'Harlequin Sweetlips',
    sciName: 'Plectorhinchus chaetodonoides',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Harlequin_sweetlips_%28Plectorhinchus_chaetodonoides%29_%2840815006613%29.jpg/1280px-Harlequin_sweetlips_%28Plectorhinchus_chaetodonoides%29_%2840815006613%29.jpg',
    region: 'coral-triangle',
    fact: 'The juvenile is blotched brown and white and swims in a lurching, tumbling motion that mimics a toxic flatworm. The adult drops the act and turns pale under dark spots.',
  },
  {
    id: 'tasselled-wobbegong',
    name: 'Tasselled Wobbegong',
    sciName: 'Eucrossorhinus dasypogon',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Tasselled_wobbegong_%28Eucrossorhinus_dasypogon%29.jpg/1280px-Tasselled_wobbegong_%28Eucrossorhinus_dasypogon%29.jpg',
    region: 'coral-triangle',
    fact: 'The fringe of branched skin flaps around its head breaks up its outline so completely that fish will swim to within a mouth-length of it.',
  },
  {
    id: 'psychedelic-frogfish',
    name: 'Psychedelic Frogfish',
    sciName: 'Histiophryne psychedelica',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Psychedelic_frogfish_juvenile.jpg/1280px-Psychedelic_frogfish_juvenile.jpg',
    region: 'coral-triangle',
    fact: 'Every fish wears a different maze of white stripes, and it gets about by bouncing off the bottom, jetting water from its gills to shove itself along.',
  },
  {
    id: 'warty-frogfish',
    name: 'Warty Frogfish',
    sciName: 'Antennarius maculatus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Pez_sapo_payaso_%28Antennarius_maculatus%29%2C_Anilao%2C_Filipinas%2C_2023-08-24%2C_DD_39.jpg/1280px-Pez_sapo_payaso_%28Antennarius_maculatus%29%2C_Anilao%2C_Filipinas%2C_2023-08-24%2C_DD_39.jpg',
    region: 'coral-triangle',
    fact: 'Does not swim so much as walk, on pectoral fins jointed like elbows, and swallows prey in about six milliseconds — one of the fastest strikes measured in any vertebrate.',
  },
  {
    id: 'clown-triggerfish',
    name: 'Clown Triggerfish',
    sciName: 'Balistoides conspicillum',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Balistoides_conspicillum_01.jpg/1280px-Balistoides_conspicillum_01.jpg',
    region: 'coral-triangle',
    fact: 'The white blotches sit only on its underside and the yellow saddle only on its back, so from below and from above it reads as two different fish.',
  },
  {
    id: 'pyjama-cardinalfish',
    name: 'Pyjama Cardinalfish',
    sciName: 'Sphaeramia nematoptera',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Pajama_cardinalfish_%28Sphaeramia_nematoptera%29_%2844065265714%29.jpg/1280px-Pajama_cardinalfish_%28Sphaeramia_nematoptera%29_%2844065265714%29.jpg',
    region: 'coral-triangle',
    fact: 'The male takes the whole clutch into his mouth and holds it there until the eggs hatch, going without food for the week or so it takes.',
  },
  {
    id: 'bluegirdled-angelfish',
    name: 'Blue-girdled Angelfish',
    sciName: 'Pomacanthus navarchus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Bluegirdled_angelfish_%28Pomacanthus_navarchus%29_%2846982094954%29.jpg/1280px-Bluegirdled_angelfish_%28Pomacanthus_navarchus%29_%2846982094954%29.jpg',
    region: 'coral-triangle',
    fact: 'Starts life black with concentric blue rings and looks like an entirely different species until the orange saddle grows in.',
  },
  {
    id: 'whitetip-reef-shark',
    name: 'Whitetip Reef Shark',
    sciName: 'Triaenodon obesus',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/14416499/large.jpeg',
    region: 'coral-triangle',
    fact: 'Unusually for a shark it can lie still on the bottom and pump water over its gills, so it spends the day piled in caves and hunts by night.',
  },
  {
    id: 'longhorn-cowfish',
    name: 'Longhorn Cowfish',
    sciName: 'Lactoria cornuta',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/427404909/large.jpg',
    region: 'coral-triangle',
    fact: 'Its body is a rigid box of fused bony plates, so only the fins move; cornered, it leaks a poison that can kill everything in the water around it, itself included.',
  },
  {
    id: 'moorish-idol',
    name: 'Moorish Idol',
    sciName: 'Zanclus cornutus',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/242697/large.JPG',
    region: 'coral-triangle',
    fact: 'The white streamer trailing off its back can be longer than the rest of the fish, and pairs frequently stay together for life.',
  },
  {
    id: 'bumphead-parrotfish',
    name: 'Bumphead Parrotfish',
    sciName: 'Bolbometopon muricatum',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/465188715/large.jpg',
    region: 'coral-triangle',
    fact: 'Rams living coral head-first to break mouthfuls loose, and one adult grinds several tonnes of reef a year into white sand.',
  },
  {
    id: 'blue-ringed-octopus',
    name: 'Blue-ringed Octopus',
    sciName: 'Hapalochlaena lunulata',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/721801465/large.jpg',
    region: 'coral-triangle',
    fact: 'Holds enough tetrodotoxin to kill a roomful of people and there is no antivenom. The rings only light up that blue once it has decided to warn you.',
  },
  {
    id: 'blacktip-reef-shark',
    name: 'Blacktip Reef Shark',
    sciName: 'Carcharhinus melanopterus',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/466660591/large.jpeg',
    region: 'coral-triangle',
    fact: 'Works water shallow enough that its dorsal fin cuts the surface, and keeps to a home range of a few square kilometres for years on end.',
  },
  {
    id: 'grey-reef-shark',
    name: 'Grey Reef Shark',
    sciName: 'Carcharhinus amblyrhynchos',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/229383492/large.jpg',
    region: 'coral-triangle',
    fact: 'Gives warning before it bites: back arched, pectoral fins dropped, swimming in a stiff exaggerated roll. Divers are taught to read that and leave.',
  },
  // ---- Northern Australia ----
  {
    id: 'barramundi',
    name: 'Barramundi',
    sciName: 'Lates calcarifer',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Lates_calcarifer%2C_2014-09-19a.jpg/1280px-Lates_calcarifer%2C_2014-09-19a.jpg',
    region: 'northern-australia',
    fact: 'Nearly all barramundi mature as males and change to female around five years old, so the biggest fish are almost always female.',
  },
  {
    id: 'australian-lungfish',
    name: 'Australian Lungfish',
    sciName: 'Neoceratodus forsteri',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Neoceratodus_forsteri_Nagoya1.jpg/1280px-Neoceratodus_forsteri_Nagoya1.jpg',
    region: 'northern-australia',
    fact: 'Native to just a few Queensland rivers, and barely changed in 100 million years. It has a single true lung and can gulp air when its pool goes stagnant.',
  },
  {
    id: 'potato-cod',
    name: 'Potato Cod',
    sciName: 'Epinephelus tukula',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Serranidae_Epinephelus_tukula_1.jpg/1280px-Serranidae_Epinephelus_tukula_1.jpg',
    region: 'northern-australia',
    fact: 'Named for the potato-sized blotches along its flanks. At the Great Barrier Reef’s Cod Hole they grow to two metres and are famously unbothered by divers.',
  },
  {
    id: 'gulf-saratoga',
    name: 'Gulf Saratoga',
    sciName: 'Scleropages jardinii',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Scleropages_jardinii_043.JPG/1280px-Scleropages_jardinii_043.JPG',
    region: 'northern-australia',
    fact: 'A mouthbrooder that carries its young for weeks, and an ancient "bonytongue" — its lineage was swimming before Australia broke from Gondwana.',
  },

  {
    id: 'nurseryfish',
    name: 'Nurseryfish',
    sciName: 'Kurtus gulliveri',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Kurtus_gulliveri.jpg/1280px-Kurtus_gulliveri.jpg',
    region: 'northern-australia',
    fact: 'The male grows a bony hook on his forehead and carries the whole egg cluster hanging from it until the young hatch.',
  },
  {
    id: 'eastern-rainbowfish',
    name: 'Eastern Rainbowfish',
    sciName: 'Melanotaenia splendida',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Melanotaenia_splendida_splendida_188164829.jpg/1280px-Melanotaenia_splendida_splendida_188164829.jpg',
    region: 'northern-australia',
    fact: 'Colour is a morning affair — males flush red and gold at first light to display, then fade back as the day goes on.',
  },
  {
    id: 'epaulette-shark',
    name: 'Epaulette Shark',
    sciName: 'Hemiscyllium ocellatum',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Epaulette_shark_camden2.jpg/1280px-Epaulette_shark_camden2.jpg',
    region: 'northern-australia',
    fact: 'Walks on its fins from one tide pool to the next across dry reef, and survives hours of almost no oxygen by shutting down parts of its own brain.',
  },
  {
    id: 'barrier-reef-anemonefish',
    name: 'Barrier Reef Anemonefish',
    sciName: 'Amphiprion akindynos',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Amphiprion_akindynos.jpg/1280px-Amphiprion_akindynos.jpg',
    region: 'northern-australia',
    fact: 'Every one of them is born male; when the resident female dies the dominant male becomes her, and the next fish in the queue moves up.',
  },
  {
    id: 'coral-trout',
    name: 'Coral Trout',
    sciName: 'Plectropomus leopardus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Plectropomus_leopardus.jpg/1280px-Plectropomus_leopardus.jpg',
    region: 'northern-australia',
    fact: 'Hunts in partnership with moray eels and octopuses, recruiting one with a headstand and a shimmy to flush prey out of holes it cannot reach itself.',
  },
  {
    id: 'archerfish',
    name: 'Banded Archerfish',
    sciName: 'Toxotes jaculatrix',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/561355621/large.jpg',
    region: 'northern-australia',
    fact: 'Shoots a jet of water from its mouth to knock insects off overhanging leaves, correcting as it aims for the way light bends at the surface.',
  },
  {
    id: 'largetooth-sawfish',
    name: 'Largetooth Sawfish',
    sciName: 'Pristis pristis',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Pristis_pristis_-_Daly_River.JPG/1280px-Pristis_pristis_-_Daly_River.JPG',
    region: 'northern-australia',
    fact: 'The saw is a sensing blade as much as a weapon: it is studded with receptors that pick up hidden fish, and then it is swung sideways through the shoal.',
  },
  {
    id: 'mangrove-jack',
    name: 'Mangrove Jack',
    sciName: 'Lutjanus argentimaculatus',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/321542891/large.jpg',
    region: 'northern-australia',
    fact: 'Spends its first years far up tidal creeks among mangrove roots, then leaves for offshore reefs to breed and never comes back.',
  },
  {
    id: 'jungle-perch',
    name: 'Jungle Perch',
    sciName: 'Kuhlia rupestris',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/88959003/large.jpg',
    region: 'northern-australia',
    fact: 'Works its way up rapids and waterfalls to reach headwater pools, but its young are washed the whole way out to sea and have to climb back.',
  },
  {
    id: 'spangled-perch',
    name: 'Spangled Perch',
    sciName: 'Leiopotherapon unicolor',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/700729274/large.jpg',
    region: 'northern-australia',
    fact: 'The most widely spread freshwater fish in Australia: it holds on in bore drains and warm puddles, and crosses flooded ground overland to reach new water.',
  },
  {
    id: 'zebra-shark',
    name: 'Zebra Shark',
    sciName: 'Stegostoma tigrinum',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/31228966/large.jpeg',
    region: 'northern-australia',
    fact: 'Hatches striped black and white, then breaks up into leopard spots as it grows — which is why half the world calls it the leopard shark instead.',
  },
  // ---- Southern Ocean ----
  {
    id: 'antarctic-toothfish',
    name: 'Antarctic Toothfish',
    sciName: 'Dissostichus mawsoni',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Dissostichus_mawsoni.jpg/1280px-Dissostichus_mawsoni.jpg',
    region: 'southern-ocean',
    fact: 'Its blood carries antifreeze glycoproteins that stop ice crystals growing, letting it live in water below the normal freezing point.',
  },
  {
    id: 'blackfin-icefish',
    name: 'Blackfin Icefish',
    sciName: 'Chaenocephalus aceratus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/C._aceratus.jpg/1280px-C._aceratus.jpg',
    region: 'southern-ocean',
    fact: 'The only known vertebrates with no haemoglobin — their blood runs clear and carries oxygen dissolved straight into the plasma.',
  },
  {
    id: 'emerald-rockcod',
    name: 'Emerald Rockcod',
    sciName: 'Trematomus bernacchii',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Emerald_rockcod%2C_Trematomus_bernacchii.jpg/1280px-Emerald_rockcod%2C_Trematomus_bernacchii.jpg',
    region: 'southern-ocean',
    fact: 'Rests on the seabed under the sea ice at about −1.9 °C, kept liquid by antifreeze proteins that bind to ice crystals before they can spread.',
  },
  {
    id: 'ocellated-icefish',
    name: 'Ocellated Icefish',
    sciName: 'Chionodraco rastrospinosus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Chionodraco_rastrospinosus.jpg/1280px-Chionodraco_rastrospinosus.jpg',
    region: 'southern-ocean',
    fact: 'White-blooded like its relatives, and named for the dark ringed spot on the first dorsal fin. It hangs almost motionless in the water to spend as little oxygen as it can.',
  },
  {
    id: 'black-rockcod',
    name: 'Black Rockcod',
    sciName: 'Notothenia coriiceps',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/72700520/large.jpg',
    region: 'southern-ocean',
    fact: 'Keeps red blood where its icefish neighbours gave theirs up, and has no swim bladder at all, so it props itself on the bottom on splayed fins and idles through the polar winter barely growing.',
  },
  // ---- Arctic Ocean ----
  {
    id: 'greenland-shark',
    name: 'Greenland Shark',
    sciName: 'Somniosus microcephalus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Greenland_shark_profile.jpg/1280px-Greenland_shark_profile.jpg',
    region: 'arctic',
    fact: 'The longest-lived vertebrate known: radiocarbon dating of the eye lens puts some individuals near 400 years old, and they mature at about 150.',
  },
  {
    id: 'polar-cod',
    name: 'Polar Cod',
    sciName: 'Boreogadus saida',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Boreogadus_saida_Kaiyukan.jpg/1280px-Boreogadus_saida_Kaiyukan.jpg',
    region: 'arctic',
    fact: 'Lives in the brine channels inside sea ice, kept liquid by antifreeze proteins. Almost every Arctic seal and seabird depends on it.',
  },
  {
    id: 'capelin',
    name: 'Capelin',
    sciName: 'Mallotus villosus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Mallotus_villosus.jpg/1280px-Mallotus_villosus.jpg',
    region: 'arctic',
    fact: 'Spawns by hurling itself onto gravel beaches in such numbers that the shoreline turns silver, then mostly dies where it lands.',
  },
  {
    id: 'arctic-char',
    name: 'Arctic Char',
    sciName: 'Salvelinus alpinus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Salvelinus_alpinus_Kaiyukan.jpg/1280px-Salvelinus_alpinus_Kaiyukan.jpg',
    region: 'arctic',
    fact: 'The northernmost freshwater fish on Earth, living in lakes that stay frozen most of the year.',
  },

  {
    id: 'arctic-grayling',
    name: 'Arctic Grayling',
    sciName: 'Thymallus arcticus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Underwater_Arctic_Grayling.jpg/1280px-Underwater_Arctic_Grayling.jpg',
    region: 'arctic',
    fact: 'The oversized dorsal fin folds flat while swimming and opens like a spotted, purple-edged sail when the fish displays or holds its place in the current.',
  },
  {
    id: 'shorthorn-sculpin',
    name: 'Shorthorn Sculpin',
    sciName: 'Myoxocephalus scorpius',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/698530829/large.jpg',
    region: 'arctic',
    fact: 'Antifreeze proteins in its blood let it sit out water below freezing, and a cornered one flares its gill covers into a spiked mask half again the size of its head.',
  },
  {
    id: 'beluga-whale',
    name: 'Beluga Whale',
    sciName: 'Delphinapterus leucas',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/229562407/large.jpeg',
    region: 'arctic',
    fact: 'The one whale that can turn its head — its neck vertebrae never fuse, so it looks over its shoulder. Sailors called it the sea canary for the racket it makes.',
  },
  {
    id: 'spiny-lumpsucker',
    name: 'Atlantic Spiny Lumpsucker',
    sciName: 'Eumicrotremus spinosus',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/384399023/large.jpeg',
    region: 'arctic',
    fact: 'A knobbly ball the size of a plum and a hopeless swimmer, it rides out the current clamped to a stone by a suction disc made from its own fused pelvic fins.',
  },
  // ---- Great Lakes ----
  {
    id: 'lake-sturgeon',
    name: 'Lake Sturgeon',
    sciName: 'Acipenser fulvescens',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Juvenile_Acipenser_fulvescens_black_background.jpg/1280px-Juvenile_Acipenser_fulvescens_black_background.jpg',
    region: 'great-lakes',
    fact: 'Armoured with bony plates instead of scales and little changed in 150 million years. Females may not spawn until they are twenty-five.',
  },
  {
    id: 'muskellunge',
    name: 'Muskellunge',
    sciName: 'Esox masquinongy',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Esox_masquinongy_%28muskellunge%29_1.jpg/1280px-Esox_masquinongy_%28muskellunge%29_1.jpg',
    region: 'great-lakes',
    fact: 'Nicknamed "the fish of ten thousand casts" for how rarely it strikes. It ambushes from weed beds and takes prey a third of its own length.',
  },
  {
    id: 'lake-trout',
    name: 'Lake Trout',
    sciName: 'Salvelinus namaycush',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Iron_River_NFH_lake_trout_6_March_2024.png/1280px-Iron_River_NFH_lake_trout_6_March_2024.png.jpg',
    region: 'great-lakes',
    fact: 'A cold, deep-water char that grows slowly and lives for decades. Sea lamprey arriving through the shipping canals nearly wiped it out.',
  },
  {
    id: 'bluegill',
    name: 'Bluegill',
    sciName: 'Lepomis macrochirus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Bluegill_%28Lepomis_macrochirus%29_black_background.jpg/1280px-Bluegill_%28Lepomis_macrochirus%29_black_background.jpg',
    region: 'great-lakes',
    fact: 'Males scrape shallow nests in colonies and fan them constantly; smaller males mimic females to sneak into a guarded nest and spawn.',
  },

  {
    id: 'walleye',
    name: 'Walleye',
    sciName: 'Sander vitreus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Sander_vitreus.jpg/1280px-Sander_vitreus.jpg',
    region: 'great-lakes',
    fact: 'A mirror-like layer behind the retina gathers what little light is left at dusk, so it hunts in the gloom that leaves its prey effectively blind.',
  },
  {
    id: 'yellow-perch',
    name: 'Yellow Perch',
    sciName: 'Perca flavescens',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Yellow_Perch_%28Perca_flavescens%29.jpg/1280px-Yellow_Perch_%28Perca_flavescens%29.jpg',
    region: 'great-lakes',
    fact: 'Hunts in packs that herd smaller fish against the shallows, and the dark bars down its sides break its outline up against weed.',
  },
  {
    id: 'longnose-gar',
    name: 'Longnose Gar',
    sciName: 'Lepisosteus osseus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Longnose_Gar_%28Lepisosteus_osseus%29.jpg/1280px-Longnose_Gar_%28Lepisosteus_osseus%29.jpg',
    region: 'great-lakes',
    fact: 'Armoured in interlocking enamel-hard scales and able to gulp air at the surface, it survives water that suffocates other fish. Its eggs are poisonous to whatever eats them.',
  },
  {
    id: 'bowfin',
    name: 'Bowfin',
    sciName: 'Amia calva',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Bowfin_01.jpg/1280px-Bowfin_01.jpg',
    region: 'great-lakes',
    fact: 'The last survivor of a family that has been around for 150 million years; it gulps air from a swim bladder plumbed like a lung and can outlast a pond going stagnant.',
  },
  {
    id: 'smallmouth-bass',
    name: 'Smallmouth Bass',
    sciName: 'Micropterus dolomieu',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Detailed_underwater_photo_of_smallmouth_bass_fish_micropterus_dolomieu.jpg/1280px-Detailed_underwater_photo_of_smallmouth_bass_fish_micropterus_dolomieu.jpg',
    region: 'great-lakes',
    fact: 'The male fans out a gravel nest and then guards it for weeks, driving off anything that comes near long after the eggs have hatched.',
  },
  {
    id: 'pumpkinseed',
    name: 'Pumpkinseed',
    sciName: 'Lepomis gibbosus',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/19503061/large.jpeg',
    region: 'great-lakes',
    fact: 'Males sweep a saucer-shaped nest into the shallows and guard it, fanning the eggs and driving off anything that comes near.',
  },
  {
    id: 'northern-pike',
    name: 'Northern Pike',
    sciName: 'Esox lucius',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/142449749/large.jpg',
    region: 'great-lakes',
    fact: 'Waits motionless in the weed and strikes in a fraction of a second, taking prey up to half its own length — other pike included.',
  },
  {
    id: 'american-paddlefish',
    name: 'American Paddlefish',
    sciName: 'Polyodon spathula',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/458720587/large.jpg',
    region: 'great-lakes',
    fact: 'The long paddle is an antenna, not a shovel: it is covered in receptors that read the faint electrical fields of the plankton the fish filters out of open water.',
  },
  {
    id: 'rainbow-darter',
    name: 'Rainbow Darter',
    sciName: 'Etheostoma caeruleum',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/15385004/large.jpg',
    region: 'great-lakes',
    fact: 'Carries no swim bladder, so hovering is beyond it: it hops along the stream bed in short bursts and settles back onto its fins between them.',
  },
  {
    id: 'northern-hogsucker',
    name: 'Northern Hogsucker',
    sciName: 'Hypentelium nigricans',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/400558298/large.jpg',
    region: 'great-lakes',
    fact: 'Shoves stones aside with a fleshy, down-turned mouth to get at what is sheltering under them, and other fish tail it to snap up whatever gets stirred loose.',
  },
  // ---- Sea of Japan ----
  {
    id: 'sakhalin-taimen',
    name: 'Sakhalin Taimen',
    sciName: 'Parahucho perryi',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Hucho_perryi_Yamano1.jpg/1280px-Hucho_perryi_Yamano1.jpg',
    region: 'sea-of-japan',
    fact: 'Passes a metre in length, lives thirty years and turns deep red to spawn. So few rivers still hold it that anglers call it the phantom fish.',
  },
  {
    id: 'red-seabream',
    name: 'Red Seabream',
    sciName: 'Pagrus major',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Pagrus_major_ioworld.jpg/1280px-Pagrus_major_ioworld.jpg',
    region: 'sea-of-japan',
    fact: 'Called tai, and served at weddings and New Year because the word rides inside "medetai" — auspicious.',
  },
  {
    id: 'torafugu',
    name: 'Torafugu',
    sciName: 'Takifugu rubripes',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Takifugu_rubripes_AQUAS.jpg/1280px-Takifugu_rubripes_AQUAS.jpg',
    region: 'sea-of-japan',
    fact: 'Carries tetrodotoxin far deadlier than cyanide, which it does not make itself but accumulates from the bacteria in its diet.',
  },
  {
    id: 'pacific-saury',
    name: 'Pacific Saury',
    sciName: 'Cololabis saira',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Cololabis_saira_in_a_tank.jpg/1280px-Cololabis_saira_in_a_tank.jpg',
    region: 'sea-of-japan',
    fact: 'A slender surface fish with no true stomach, so it digests continuously — and an autumn staple grilled whole as sanma.',
  },

  {
    id: 'ayu',
    name: 'Ayu',
    sciName: 'Plecoglossus altivelis',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Plecoglossus_altivelis_Totto.jpg/1280px-Plecoglossus_altivelis_Totto.jpg',
    region: 'sea-of-japan',
    fact: 'Scrapes algae off river stones and leaves oval grazing marks behind; its flesh smells of melon, and almost every fish lives just one year.',
  },
  {
    id: 'sailfin-sandfish',
    name: 'Sailfin Sandfish',
    sciName: 'Arctoscopus japonicus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Arctoscopus_japonicus_Umigatari.png/1280px-Arctoscopus_japonicus_Umigatari.png.jpg',
    region: 'sea-of-japan',
    fact: 'Has no scales at all. It spawns during the winter storms, crowding into the shallows in numbers that leave the surf thick with eggs.',
  },
  {
    id: 'japanese-bullhead-shark',
    name: 'Japanese Bullhead Shark',
    sciName: 'Heterodontus japonicus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Japanese_bullhead_shark_Suma_Aqualife_Park.jpg/1280px-Japanese_bullhead_shark_Suma_Aqualife_Park.jpg',
    region: 'sea-of-japan',
    fact: 'Grinds shellfish with flat crushing back teeth, and lays spiral egg cases that it screws into rock crevices like a corkscrew.',
  },
  {
    id: 'cherry-anthias',
    name: 'Cherry Anthias',
    sciName: 'Sacura margaritacea',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Japan_fish%2C_Sakuradai_%28Sacura_margaritacea%29_%2815770306721%29.jpg/1280px-Japan_fish%2C_Sakuradai_%28Sacura_margaritacea%29_%2815770306721%29.jpg',
    region: 'sea-of-japan',
    fact: 'Named for the cherry blossom: males are crimson flecked with white, while the females they grew out of stay a plain orange.',
  },
  {
    id: 'barred-knifejaw',
    name: 'Barred Knifejaw',
    sciName: 'Oplegnathus fasciatus',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/454966244/large.jpeg',
    region: 'sea-of-japan',
    fact: 'Its teeth fuse into a solid parrot-like beak that crunches barnacles and sea urchins straight off the rock.',
  },
  {
    id: 'japanese-pineconefish',
    name: 'Japanese Pineconefish',
    sciName: 'Monocentris japonica',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/613333857/large.jpg',
    region: 'sea-of-japan',
    fact: 'Armoured head to tail in plates like a walking pine cone, and it hunts by the light of two organs on its lower jaw, lit by bacteria it farms.',
  },
  {
    id: 'threadsail-filefish',
    name: 'Threadsail Filefish',
    sciName: 'Stephanolepis cirrhifer',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/551333795/large.jpg',
    region: 'sea-of-japan',
    fact: 'Skin like sandpaper, and a dorsal spine that locks upright: wedged into a crevice with the spine up, it cannot be pulled out.',
  },
  {
    id: 'zebra-bullhead-shark',
    name: 'Zebra Bullhead Shark',
    sciName: 'Heterodontus zebra',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/181071087/large.jpeg',
    region: 'sea-of-japan',
    fact: 'Lays an egg case shaped like a screw thread and works it into a crack in the rock, where the spiral jams tight against the surge.',
  },
  {
    id: 'japanese-seabass',
    name: 'Japanese Sea Bass',
    sciName: 'Lateolabrax japonicus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Lateolabrax_japonicus_Iwaki.jpg/1280px-Lateolabrax_japonicus_Iwaki.jpg',
    region: 'sea-of-japan',
    fact: 'Japanese gives it a new name at each size it reaches — seigo, then fukko, then suzuki — one of a handful of fish said to be promoted as they grow.',
  },
  // ---- Mekong Basin ----
  {
    id: 'mekong-giant-catfish',
    name: 'Mekong Giant Catfish',
    sciName: 'Pangasianodon gigas',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Mekong_giant_catfish.jpg/1280px-Mekong_giant_catfish.jpg',
    region: 'mekong',
    fact: 'One of the largest freshwater fish ever recorded, near three metres. Adults lose their teeth and barbels and live entirely on algae.',
  },
  {
    id: 'siamese-fighting-fish',
    name: 'Siamese Fighting Fish',
    sciName: 'Betta splendens',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Bojownik_syjamski.jpg/1280px-Bojownik_syjamski.jpg',
    region: 'mekong',
    fact: 'Breathes air through a labyrinth organ, so it survives in rice paddies too stagnant for other fish. The male builds a nest of bubbles.',
  },
  {
    id: 'giant-freshwater-stingray',
    name: 'Giant Freshwater Stingray',
    sciName: 'Urogymnus polylepis',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Urogymnus_polylepis_at_Itabashi_Botanical_Garden.png/1280px-Urogymnus_polylepis_at_Itabashi_Botanical_Garden.png.jpg',
    region: 'mekong',
    fact: 'Can span two metres across and carries a serrated spine longer than a hand, used only in defence against river-bottom predators.',
  },
  {
    id: 'giant-snakehead',
    name: 'Giant Snakehead',
    sciName: 'Channa micropeltes',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Channa_micropeltes_-_T%C3%AAte_de_serpent_-_Aqua_Porte_Dor%C3%A9e_01.JPG/1280px-Channa_micropeltes_-_T%C3%AAte_de_serpent_-_Aqua_Porte_Dor%C3%A9e_01.JPG',
    region: 'mekong',
    fact: 'Breathes air and can cross damp ground between pools. Both parents guard the shoal of red fry and will drive off anything that comes near.',
  },

  {
    id: 'giant-barb',
    name: 'Giant Barb',
    sciName: 'Catlocarpio siamensis',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Siamese_giant_carp_%28Catlocarpio_siamensis%29_2.jpg/1280px-Siamese_giant_carp_%28Catlocarpio_siamensis%29_2.jpg',
    region: 'mekong',
    fact: 'The largest carp in the world at up to three metres, and it lives on algae, plankton and fruit dropped from flooded riverbanks.',
  },
  {
    id: 'clown-featherback',
    name: 'Clown Featherback',
    sciName: 'Chitala ornata',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Adult_Clown_featherback_in_aquarium.jpg/1280px-Adult_Clown_featherback_in_aquarium.jpg',
    region: 'mekong',
    fact: 'Holds its body rigid and swims by rippling one long unbroken fin along its underside, forwards or backwards with equal ease.',
  },
  {
    id: 'giant-mudskipper',
    name: 'Giant Mudskipper',
    sciName: 'Periophthalmodon schlosseri',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Giant_Mudskipper_%28Periophthalmodon_schlosseri%29.jpg/1280px-Giant_Mudskipper_%28Periophthalmodon_schlosseri%29.jpg',
    region: 'mekong',
    fact: 'Spends most of the tide out of the water, breathing through its skin and a mouthful of held water, and digs burrows it gulps air down into for its eggs.',
  },
  {
    id: 'glass-catfish',
    name: 'Glass Catfish',
    sciName: 'Kryptopterus vitreolus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Kryptopterus_vitreolus_%28Cologne_Zoo%29.jpg/1280px-Kryptopterus_vitreolus_%28Cologne_Zoo%29.jpg',
    region: 'mekong',
    fact: 'So transparent that its spine and the silvery sac around its organs are the only parts you can see; the rest of the fish is a suggestion.',
  },
  {
    id: 'siamese-tigerfish',
    name: 'Siamese Tigerfish',
    sciName: 'Datnioides pulcher',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Datnioides_pulcher_by_OpenCage.jpg/1280px-Datnioides_pulcher_by_OpenCage.jpg',
    region: 'mekong',
    fact: 'Hangs almost motionless among flooded branches, its broad black bars breaking up its outline, then swings its whole body to inhale a passing fish.',
  },
  {
    id: 'climbing-perch',
    name: 'Climbing Perch',
    sciName: 'Anabas testudineus',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/52464343/large.jpg',
    region: 'mekong',
    fact: 'Breathes air through an organ above its gills and hauls itself overland on its gill covers and fins, crossing dry ground between pools and lasting days out of water.',
  },
  {
    id: 'giant-gourami',
    name: 'Giant Gourami',
    sciName: 'Osphronemus goramy',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/433963804/large.jpg',
    region: 'mekong',
    fact: 'Breathes air through a folded organ above its gills, so it lives on in water gone too stale for anything else, and the male weaves a nest out of plant fibre.',
  },
  {
    id: 'kissing-gourami',
    name: 'Kissing Gourami',
    sciName: 'Helostoma temminckii',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/319810426/large.jpg',
    region: 'mekong',
    fact: 'The kiss is a fight. Two fish lock lips and shove, each testing how hard the other can push, sometimes for minutes at a stretch.',
  },
  {
    id: 'bala-shark',
    name: 'Bala Shark',
    sciName: 'Balantiocheilos melanopterus',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/315322142/large.jpeg',
    region: 'mekong',
    fact: 'The name is borrowed. It is a minnow, and the black-edged fins and pointed snout are the whole of what it has in common with a shark.',
  },
  {
    id: 'striped-catfish',
    name: 'Striped Catfish',
    sciName: 'Pangasianodon hypophthalmus',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/358821280/large.jpeg',
    region: 'mekong',
    fact: 'Farmed by the million and sold worldwide as basa or swai, while the wild fish still runs hundreds of kilometres up the river to spawn.',
  },
  // ---- New Zealand ----
  {
    id: 'australasian-snapper',
    name: 'Australasian Snapper',
    sciName: 'Chrysophrys auratus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Pagrus_auratus_%28Forster%2C_1801%29_%28AM_MA36682-1%29.jpg/1280px-Pagrus_auratus_%28Forster%2C_1801%29_%28AM_MA36682-1%29.jpg',
    region: 'new-zealand',
    fact: 'Older fish develop a pronounced bony hump on the forehead and snout, and can live past sixty years.',
  },
  {
    id: 'longfin-eel',
    name: 'New Zealand Longfin Eel',
    sciName: 'Anguilla dieffenbachii',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Anguilla_dieffenbachii_01.jpg/1280px-Anguilla_dieffenbachii_01.jpg',
    region: 'new-zealand',
    fact: 'Spends up to a century in fresh water, then swims thousands of kilometres to spawn near Tonga once, and dies.',
  },
  {
    id: 'blue-cod',
    name: 'Blue Cod',
    sciName: 'Parapercis colias',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Blue_Cod_in_Milford_Sound.jpg/1280px-Blue_Cod_in_Milford_Sound.jpg',
    region: 'new-zealand',
    fact: 'Found nowhere but New Zealand. Every one begins life female, and the largest turn male and take a territory.',
  },
  {
    id: 'kahawai',
    name: 'Kahawai',
    sciName: 'Arripis trutta',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/103084334/large.jpg',
    region: 'new-zealand',
    fact: 'Hunts in fast surface shoals that drive baitfish into a boil, with seabirds working the same school from above.',
  },
  {
    id: 'red-moki',
    name: 'Red Moki',
    sciName: 'Cheilodactylus spectabilis',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Red_Moki_%28Cheilodactylus_spectabilis%29.jpg/1280px-Red_Moki_%28Cheilodactylus_spectabilis%29.jpg',
    region: 'new-zealand',
    fact: 'Sifts invertebrates out of mouthfuls of sand with thick fleshy lips, and holds the same patch of reef for decades — some are over sixty years old.',
  },
  {
    id: 'red-gurnard',
    name: 'Red Gurnard',
    sciName: 'Chelidonichthys kumu',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Chelidonichthys_kumu.jpg/1280px-Chelidonichthys_kumu.jpg',
    region: 'new-zealand',
    fact: 'Walks the seabed on three stiff finger-like rays split off from each pectoral fin, feeling for buried prey, and grunts audibly by drumming its swim bladder.',
  },
  {
    id: 'draughtsboard-shark',
    name: 'Draughtsboard Shark',
    sciName: 'Cephaloscyllium isabellum',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Carpetshark.jpg/1280px-Carpetshark.jpg',
    region: 'new-zealand',
    fact: 'Swallows water until it swells to twice its size and wedges itself immovably into a crevice — and if it is lifted out, it gulps air and barks.',
  },
  {
    id: 'spotty',
    name: 'Spotty',
    sciName: 'Notolabrus celidotus',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/571299606/large.jpg',
    region: 'new-zealand',
    fact: 'Juveniles work as cleaners, and larger fish queue up and hold still while their parasites are picked off.',
  },
  {
    id: 'banded-wrasse',
    name: 'Banded Wrasse',
    sciName: 'Notolabrus fucicola',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/178195908/large.jpeg',
    region: 'new-zealand',
    fact: 'A second set of jaws back in the throat crushes whole crabs and sea urchins, shell and spines together.',
  },
  {
    id: 'blue-maomao',
    name: 'Blue Maomao',
    sciName: 'Scorpis violacea',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/472573320/large.jpeg',
    region: 'new-zealand',
    fact: 'Hangs in huge blue clouds inside sea caves and arches by day, drifting out at dusk to pick plankton from the current.',
  },
  {
    id: 'tarakihi',
    name: 'Tarakihi',
    sciName: 'Nemadactylus macropterus',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/501281187/large.jpg',
    region: 'new-zealand',
    fact: 'Its young spend close to a year adrift in the open ocean as flat silver sheets before ever settling on the seabed.',
  },
  {
    id: 'luderick',
    name: 'Luderick',
    sciName: 'Girella tricuspidata',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/245831432/large.jpeg',
    region: 'new-zealand',
    fact: 'One of the very few sea fish that lives on seaweed, and anglers bait their hooks with green weed to catch it.',
  },
  {
    id: 'butterfish',
    name: 'Butterfish',
    sciName: 'Odax pullus',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/191237471/large.jpg',
    region: 'new-zealand',
    fact: 'Eats nothing but seaweed, and every one starts life female — the largest turn male, trading brown juvenile mottling for a deep blue-green.',
  },
  {
    id: 'yellowtail-kingfish',
    name: 'Yellowtail Kingfish',
    sciName: 'Seriola lalandi',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/469265745/large.jpg',
    region: 'new-zealand',
    fact: 'Runs prey down in the open in short violent bursts, and the same fish will come back to one particular reef or pinnacle year after year.',
  },
  {
    id: 'sevengill-shark',
    name: 'Broadnose Sevengill Shark',
    sciName: 'Notorynchus cepedianus',
    image: 'https://inaturalist-open-data.s3.amazonaws.com/photos/599687346/large.jpg',
    region: 'new-zealand',
    fact: 'Keeps seven gill slits where nearly every other shark makes do with five, an arrangement its line has held for over a hundred million years. Hunts in groups large enough to take seals.',
  },
];
