/* Fishguesser — the guessable fish, grouped by home region.
 *
 * `region` must match an id in REGIONS (see regions.js); several fish share a
 * region, which is what makes the map worth reading rather than memorising.
 * Photos are linked straight from Wikimedia Commons rather than stored here, so
 * the game needs a network connection to show them. The URLs point at the CDN
 * thumbnail directly — the path hash is derived from the filename, not the
 * contents, so it stays valid if the file is re-uploaded. Which Commons file
 * each fish uses, and who to credit, is recorded in assets/fish/credits.json;
 * see CREDITS.md. Regenerate the URLs with tools/build_photo_urls.py.
 *
 * Species are picked so their natural range genuinely centres on the region
 * they are filed under — a widespread Indo-Pacific fish would make for an
 * unfair round. */

const FISH = [
  // ---- North Pacific ----
  {
    id: 'sockeye-salmon',
    name: 'Sockeye Salmon',
    sciName: 'Oncorhynchus nerka',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Oncorhynchus_nerka_2.jpg/1280px-Oncorhynchus_nerka_2.jpg',
    region: 'north-pacific',
    fact: 'Sockeye spend years at sea silver, then turn brilliant red with a green head to spawn in the same freshwater stream they hatched in.',
  },
  {
    id: 'yelloweye-rockfish',
    name: 'Yelloweye Rockfish',
    sciName: 'Sebastes ruberrimus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Sebastes_ruberrimus_143567641.jpg/1280px-Sebastes_ruberrimus_143567641.jpg',
    region: 'north-pacific',
    fact: 'One of the longest-lived fish in the world — individuals over 100 years old have been aged. Growing that slowly makes the species very slow to recover from fishing.',
  },
  {
    id: 'lingcod',
    name: 'Lingcod',
    sciName: 'Ophiodon elongatus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Ophiodon_elongatus_458366655.jpg/1280px-Ophiodon_elongatus_458366655.jpg',
    region: 'north-pacific',
    fact: 'Not a cod at all, but a greenling. Roughly one in five has startling blue-green flesh from a harmless pigment that cooks away white.',
  },
  {
    id: 'pacific-halibut',
    name: 'Pacific Halibut',
    sciName: 'Hippoglossus stenolepis',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Hippoglossus_stenolepis_1.JPG/1280px-Hippoglossus_stenolepis_1.JPG',
    region: 'north-pacific',
    fact: 'Hatches upright with an eye on each side, then one eye migrates across its skull as it tips over to live flat on the seabed.',
  },

  {
    id: 'spotted-ratfish',
    name: 'Spotted Ratfish',
    sciName: 'Hydrolagus colliei',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Hydrolagus_colliei_8049778.jpg/1280px-Hydrolagus_colliei_8049778.jpg',
    region: 'north-pacific',
    fact: 'Not a shark but a chimaera, from a branch that split off before sharks were sharks: it grinds shellfish with permanent tooth plates, and the spine in front of its dorsal fin is venomous.',
  },
  {
    id: 'kelp-greenling',
    name: 'Kelp Greenling',
    sciName: 'Hexagrammos decagrammus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Hexagrammos_decagrammus_hembra.jpg/1280px-Hexagrammos_decagrammus_hembra.jpg',
    region: 'north-pacific',
    fact: 'Males and females look like separate species — he is grey-blue under electric blue spots, she is brown under golden-orange ones — and both carry five lateral lines down each flank where most fish have one.',
  },
  {
    id: 'pacific-spiny-dogfish',
    name: 'Pacific Spiny Dogfish',
    sciName: 'Squalus suckleyi',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Squalus_suckleyi_in_an_aquarium.jpg/1280px-Squalus_suckleyi_in_an_aquarium.jpg',
    region: 'north-pacific',
    fact: 'Carries a mildly venomous spine in front of each dorsal fin, lives past eighty, and is pregnant for about two years — the longest gestation of any shark.',
  },
  {
    id: 'leopard-shark',
    name: 'Leopard Shark',
    sciName: 'Triakis semifasciata',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Triakis_semifasciata_Gratwicke.jpg/1280px-Triakis_semifasciata_Gratwicke.jpg',
    region: 'north-pacific',
    fact: 'Rides the flooding tide up onto mudflats to hunt in water barely deep enough to cover it, then slips back out with the ebb.',
  },
  {
    id: 'sarcastic-fringehead',
    name: 'Sarcastic Fringehead',
    sciName: 'Neoclinus blanchardi',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Sarcastic_fringehead.jpg/1280px-Sarcastic_fringehead.jpg',
    region: 'north-pacific',
    fact: 'Lives in a bottle or an empty shell and defends it by unfolding its whole head into a gaping frill, then wrestling rivals mouth to mouth.',
  },
  // ---- Caribbean Sea ----
  {
    id: 'queen-angelfish',
    name: 'Queen Angelfish',
    sciName: 'Holacanthus ciliaris',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Pez_%C3%A1ngel_reina_%28Holacanthus_ciliaris%29%2C_Cozumel%2C_M%C3%A9xico%2C_2025-12-20%2C_DD_134.jpg/1280px-Pez_%C3%A1ngel_reina_%28Holacanthus_ciliaris%29%2C_Cozumel%2C_M%C3%A9xico%2C_2025-12-20%2C_DD_134.jpg',
    region: 'caribbean',
    fact: 'Named for the ringed blue "crown" on its forehead. It grazes mostly on sponges around Caribbean and Floridian reefs.',
  },
  {
    id: 'nassau-grouper',
    name: 'Nassau Grouper',
    sciName: 'Epinephelus striatus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Epinephelus_striatus_2.jpg/1280px-Epinephelus_striatus_2.jpg',
    region: 'caribbean',
    fact: 'Gathers by the thousand to spawn at the same reefs each winter full moon — predictable enough that fishing collapsed the species to critically endangered.',
  },
  {
    id: 'stoplight-parrotfish',
    name: 'Stoplight Parrotfish',
    sciName: 'Sparisoma viride',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Stoplight-parrotfish.jpg/1280px-Stoplight-parrotfish.jpg',
    region: 'caribbean',
    fact: 'Scrapes algae off coral with a beak of fused teeth and excretes the ground-up rock as fine white sand — a single fish can make hundreds of kilos of beach a year.',
  },
  {
    id: 'tarpon',
    name: 'Atlantic Tarpon',
    sciName: 'Megalops atlanticus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Megalops_atlanticus_by_DaijuAzuma.jpg/1280px-Megalops_atlanticus_by_DaijuAzuma.jpg',
    region: 'caribbean',
    fact: 'Gulps air at the surface through a lung-like swim bladder, which lets it survive in stagnant backwaters that would suffocate its predators.',
  },

  {
    id: 'atlantic-blue-tang',
    name: 'Atlantic Blue Tang',
    sciName: 'Acanthurus coeruleus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Pez_cirujano_azul_%28Acanthurus_coeruleus%29%2C_Cozumel%2C_M%C3%A9xico%2C_2025-12-20%2C_DD_75.jpg/1280px-Pez_cirujano_azul_%28Acanthurus_coeruleus%29%2C_Cozumel%2C_M%C3%A9xico%2C_2025-12-20%2C_DD_75.jpg',
    region: 'caribbean',
    fact: 'Hatches bright yellow and darkens to deep blue as it matures, keeping a scalpel-sharp hinged spine at the base of the tail that it swings sideways like a switchblade.',
  },
  {
    id: 'foureye-butterflyfish',
    name: 'Foureye Butterflyfish',
    sciName: 'Chaetodon capistratus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Chaetodon_capistratus_394406658.jpg/1280px-Chaetodon_capistratus_394406658.jpg',
    region: 'caribbean',
    fact: 'The big ringed spot near the tail is a decoy eye, and the real one is hidden in a dark band — a predator aims for the wrong end and the fish escapes forwards.',
  },
  {
    id: 'queen-triggerfish',
    name: 'Queen Triggerfish',
    sciName: 'Balistes vetula',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Queen_Triggerfish_Balistes_vetula.jpg/1280px-Queen_Triggerfish_Balistes_vetula.jpg',
    region: 'caribbean',
    fact: 'Wedges itself into a crevice by locking a stout dorsal spine upright; a smaller spine behind it works the catch, and until that is released the fish cannot be pulled out.',
  },
  {
    id: 'bonnethead',
    name: 'Bonnethead',
    sciName: 'Sphyrna tiburo',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Bonnethead_shark_Aquarium_of_the_Pacific.jpg/1280px-Bonnethead_shark_Aquarium_of_the_Pacific.jpg',
    region: 'caribbean',
    fact: 'The only shark known to properly digest plants: seagrass makes up more than half of what it eats, and it grows on the stuff.',
  },
  {
    id: 'nurse-shark',
    name: 'Nurse Shark',
    sciName: 'Ginglymostoma cirratum',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Nurse_shark_turning.jpg/1280px-Nurse_shark_turning.jpg',
    region: 'caribbean',
    fact: 'Sucks prey out of rock crevices hard enough that divers can hear the slurp, and spends the day piled up motionless with dozens of others.',
  },
  {
    id: 'spanish-hogfish',
    name: 'Spanish Hogfish',
    sciName: 'Bodianus rufus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Bodianus_rufus_%2846598633625%29.jpg/1280px-Bodianus_rufus_%2846598633625%29.jpg',
    region: 'caribbean',
    fact: 'Young ones set up as cleaners, picking parasites off fish easily big enough to eat them, and give up the trade once they are grown.',
  },
  {
    id: 'rock-beauty',
    name: 'Rock Beauty',
    sciName: 'Holacanthus tricolor',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Chabelita_tricolor_%28Holacanthus_tricolor%29%2C_Cozumel%2C_M%C3%A9xico%2C_2025-12-20%2C_DD_104.jpg/1280px-Chabelita_tricolor_%28Holacanthus_tricolor%29%2C_Cozumel%2C_M%C3%A9xico%2C_2025-12-20%2C_DD_104.jpg',
    region: 'caribbean',
    fact: 'Juveniles are entirely yellow but for one blue-ringed spot, and the black spreads outward from that spot as the fish grows until it covers most of the body.',
  },
  {
    id: 'royal-gramma',
    name: 'Royal Gramma',
    sciName: 'Gramma loreto',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Gramma_loreto_01.jpg/1280px-Gramma_loreto_01.jpg',
    region: 'caribbean',
    fact: 'Holds itself square to whatever surface it is nearest, so a fish tucked under an overhang hangs there calmly upside down.',
  },
  // ---- Amazon Basin ----
  {
    id: 'red-bellied-piranha',
    name: 'Red-bellied Piranha',
    sciName: 'Pygocentrus nattereri',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Pygocentrus_nattereri_-_Karlsruhe_Zoo_01.jpg/1280px-Pygocentrus_nattereri_-_Karlsruhe_Zoo_01.jpg',
    region: 'amazon',
    fact: 'Far less bloodthirsty than its reputation — it mostly scavenges and eats insects, and shoals largely for protection from predators.',
  },
  {
    id: 'arapaima',
    name: 'Arapaima',
    sciName: 'Arapaima gigas',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Arapaima_gigas_5147.jpg/1280px-Arapaima_gigas_5147.jpg',
    region: 'amazon',
    fact: 'One of the largest freshwater fish alive, past three metres. It breathes air through a lung-like swim bladder and drowns if kept from the surface.',
  },
  {
    id: 'discus',
    name: 'Discus',
    sciName: 'Symphysodon aequifasciatus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Symphysodon_aequifasciatus_-_Karlsruhe_Zoo_04.jpg/1280px-Symphysodon_aequifasciatus_-_Karlsruhe_Zoo_04.jpg',
    region: 'amazon',
    fact: 'Both parents grow a nutritious skin mucus that their fry graze on for the first few weeks — a fish equivalent of nursing.',
  },
  {
    id: 'electric-eel',
    name: 'Electric Eel',
    sciName: 'Electrophorus electricus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Electrophorus_electricus_in_Ouwehands_Dierenpark_01.jpg/1280px-Electrophorus_electricus_in_Ouwehands_Dierenpark_01.jpg',
    region: 'amazon',
    fact: 'Not an eel but a knifefish. It can discharge around 600 volts, and has been seen leaping to press the shock directly into a large animal.',
  },

  {
    id: 'oscar',
    name: 'Oscar',
    sciName: 'Astronotus ocellatus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Astronotus_ocellatus_-_side_%28aka%29.jpg/1280px-Astronotus_ocellatus_-_side_%28aka%29.jpg',
    region: 'amazon',
    fact: 'The false eyespot on its tail is thought to send a striking predator to the wrong end, and it will lie motionless on its side playing dead until something curious swims close enough to eat.',
  },
  {
    id: 'cardinal-tetra',
    name: 'Cardinal Tetra',
    sciName: 'Paracheirodon axelrodi',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Cardinal_Paracheirodon_axelrodi_%283%29.jpg/1280px-Cardinal_Paracheirodon_axelrodi_%283%29.jpg',
    region: 'amazon',
    fact: 'The blue stripe is not pigment but stacked crystal plates bending light, and the fish can tilt them — the colour drains away to near black while it sleeps.',
  },
  {
    id: 'redtail-catfish',
    name: 'Redtail Catfish',
    sciName: 'Phractocephalus hemioliopterus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Hal_-_Phractocephalus_hemioliopterus_-_1.jpg/1280px-Hal_-_Phractocephalus_hemioliopterus_-_1.jpg',
    region: 'amazon',
    fact: 'Swallows whole anything that fits and passes a metre in length, which is why a palm-sized one sold for a home aquarium rarely stays in it.',
  },
  {
    id: 'tambaqui',
    name: 'Tambaqui',
    sciName: 'Colossoma macropomum',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Black_pacu.jpg/1280px-Black_pacu.jpg',
    region: 'amazon',
    fact: 'A relative of the piranha that gave up meat for fruit, waiting under flooded forest trees to crack fallen seeds with molars unnervingly like human teeth.',
  },
  // ---- North Atlantic ----
  {
    id: 'atlantic-cod',
    name: 'Atlantic Cod',
    sciName: 'Gadus morhua',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Atlantic_Cod%2C_Atlantischer_Kabeljau_%28Gadus_morhua%29.jpg/1280px-Atlantic_Cod%2C_Atlantischer_Kabeljau_%28Gadus_morhua%29.jpg',
    region: 'north-atlantic',
    fact: 'Three dorsal fins and a whisker-like chin barbel it uses to taste the seabed. Centuries of fishing collapsed the Grand Banks stock in 1992.',
  },
  {
    id: 'atlantic-wolffish',
    name: 'Atlantic Wolffish',
    sciName: 'Anarhichas lupus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Anarhichas-lupus-Atlanterhavsparken.jpg/1280px-Anarhichas-lupus-Atlanterhavsparken.jpg',
    region: 'north-atlantic',
    fact: 'Crushes sea urchins and clams with conical fangs, and makes its own antifreeze so its blood keeps flowing in near-freezing water.',
  },
  {
    id: 'atlantic-mackerel',
    name: 'Atlantic Mackerel',
    sciName: 'Scomber scombrus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Atlantic_mackerel_%28Scomber_scombrus%29.jpg/1280px-Atlantic_mackerel_%28Scomber_scombrus%29.jpg',
    region: 'north-atlantic',
    fact: 'Has no swim bladder, so it must keep swimming or sink. The wavy black bars across its back are as individual as a fingerprint.',
  },
  {
    id: 'lumpfish',
    name: 'Lumpfish',
    sciName: 'Cyclopterus lumpus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Merivarblane.jpg/1280px-Merivarblane.jpg',
    region: 'north-atlantic',
    fact: 'Its pelvic fins are fused into a suction disc that clamps it to rock against the swell. The male guards the eggs alone, fanning them for weeks.',
  },

  {
    id: 'atlantic-salmon',
    name: 'Atlantic Salmon',
    sciName: 'Salmo salar',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Laks_i_laksetrappa.JPG/1280px-Laks_i_laksetrappa.JPG',
    region: 'north-atlantic',
    fact: 'Unlike its Pacific cousins it does not always die after spawning — a few survive the run, slip back down to the sea and return to breed a second or third time.',
  },
  {
    id: 'cuckoo-wrasse',
    name: 'Cuckoo Wrasse',
    sciName: 'Labrus mixtus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Labrus_mixtus_23_BG.jpg/1280px-Labrus_mixtus_23_BG.jpg',
    region: 'north-atlantic',
    fact: 'Every one hatches female and dull orange. The largest of a group then turns male and repaints itself in electric blue and yellow.',
  },
  {
    id: 'basking-shark',
    name: 'Basking Shark',
    sciName: 'Cetorhinus maximus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Cetorhinus_maximus_atlantic.jpg/1280px-Cetorhinus_maximus_atlantic.jpg',
    region: 'north-atlantic',
    fact: 'The second-largest fish alive strains plankton by cruising with its mouth held wide open, filtering something like two thousand tonnes of water an hour.',
  },
  {
    id: 'sea-lamprey',
    name: 'Sea Lamprey',
    sciName: 'Petromyzon marinus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Petromyzon_marinus_282284066_%28cropped%29.jpg/1280px-Petromyzon_marinus_282284066_%28cropped%29.jpg',
    region: 'north-atlantic',
    fact: 'Older than jaws themselves: it has no hinged mouth, only a rasping funnel of teeth it fastens to a larger fish to drink from.',
  },
  // ---- Mediterranean Sea ----
  {
    id: 'gilt-head-bream',
    name: 'Gilt-head Bream',
    sciName: 'Sparus aurata',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Brest_-_Oc%C3%A9anopolis_-_2015_-_051.jpg/1280px-Brest_-_Oc%C3%A9anopolis_-_2015_-_051.jpg',
    region: 'mediterranean',
    fact: 'Named for the golden band between its eyes. Every one starts life male and some later become female — a trick called protandry.',
  },
  {
    id: 'dusky-grouper',
    name: 'Dusky Grouper',
    sciName: 'Epinephelus marginatus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Mero_%28Epinephelus_marginatus%29%2C_Cabo_de_Palos%2C_Espa%C3%B1a%2C_2022-07-15%2C_DD_34.jpg/1280px-Mero_%28Epinephelus_marginatus%29%2C_Cabo_de_Palos%2C_Espa%C3%B1a%2C_2022-07-15%2C_DD_34.jpg',
    region: 'mediterranean',
    fact: 'A long-lived rocky-reef ambusher that holds the same territory for years. All are born female and the largest turn male around age twelve.',
  },
  {
    id: 'european-seabass',
    name: 'European Seabass',
    sciName: 'Dicentrarchus labrax',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Dicentrarchus_labrax_LoroParqueTenerife_seabass_IMG_4959.JPG/1280px-Dicentrarchus_labrax_LoroParqueTenerife_seabass_IMG_4959.JPG',
    region: 'mediterranean',
    fact: 'A fast coastal hunter that pushes far into brackish lagoons and river mouths, tolerating water from nearly fresh to fully salt.',
  },
  {
    id: 'mediterranean-moray',
    name: 'Mediterranean Moray',
    sciName: 'Muraena helena',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Morena_del_Mediterr%C3%A1neo_%28Muraena_helena%29%2C_Catania%2C_Sicilia%2C_Italia%2C_2025-04-05%2C_DD_35.jpg/1280px-Morena_del_Mediterr%C3%A1neo_%28Muraena_helena%29%2C_Catania%2C_Sicilia%2C_Italia%2C_2025-04-05%2C_DD_35.jpg',
    region: 'mediterranean',
    fact: 'Has a second set of jaws in its throat that lunge forward to drag prey down, since it cannot suck food in the way most fish do.',
  },

  {
    id: 'red-scorpionfish',
    name: 'Red Scorpionfish',
    sciName: 'Scorpaena scrofa',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Red_Scorpionfish_%28cropped%29.jpg/1280px-Red_Scorpionfish_%28cropped%29.jpg',
    region: 'mediterranean',
    fact: 'Sits motionless under a fringe of skin tassels until prey drifts within reach, then swallows it in a gulp measured in milliseconds; the spines along its back are venomous.',
  },
  {
    id: 'striped-red-mullet',
    name: 'Striped Red Mullet',
    sciName: 'Mullus surmuletus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Mullus_surmuletus_Cala_Gracio.jpg/1280px-Mullus_surmuletus_Cala_Gracio.jpg',
    region: 'mediterranean',
    fact: 'Rakes buried prey out of the sand with a pair of long chin barbels it tastes with. Roman diners paid absurd sums for a large one and kept it alive at the table to watch its colours change.',
  },
  {
    id: 'angelshark',
    name: 'Angelshark',
    sciName: 'Squatina squatina',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Squatina_squatina_eingegraben_bearbeitet.JPG/1280px-Squatina_squatina_eingegraben_bearbeitet.JPG',
    region: 'mediterranean',
    fact: 'Lies buried with only its eyes above the sand and strikes upward in about a tenth of a second; once so common it was a market staple, now critically endangered.',
  },
  {
    id: 'flying-gurnard',
    name: 'Flying Gurnard',
    sciName: 'Dactylopterus volitans',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/FlyingGurnard.jpg/1280px-FlyingGurnard.jpg',
    region: 'mediterranean',
    fact: 'Cannot fly at all: the enormous blue-spangled fans are opened on the sea floor to startle whatever is chasing it, and it walks on the front rays of its pelvic fins.',
  },
  {
    id: 'ornate-wrasse',
    name: 'Ornate Wrasse',
    sciName: 'Thalassoma pavo',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Thalassoma_pavo_male.jpg/1280px-Thalassoma_pavo_male.jpg',
    region: 'mediterranean',
    fact: 'Born female and barred in orange; the largest of a group then turns male and repaints itself in green and blue.',
  },
  // ---- Congo Basin ----
  {
    id: 'goliath-tigerfish',
    name: 'Goliath Tigerfish',
    sciName: 'Hydrocynus goliath',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Hydrocynus_goliath.jpg/1280px-Hydrocynus_goliath.jpg',
    region: 'congo',
    fact: 'Grows past 1.5 m and 50 kg, with 32 interlocking dagger teeth. It hunts by sight in fast, turbid water where few predators can.',
  },
  {
    id: 'elephantnose-fish',
    name: 'Elephantnose Fish',
    sciName: 'Gnathonemus petersii',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Mormyridae_Gnathonemus_petersii_2.jpg/1280px-Mormyridae_Gnathonemus_petersii_2.jpg',
    region: 'congo',
    fact: 'Navigates pitch-dark, muddy water by reading distortions in its own weak electric field, and devotes a larger share of its body energy to its brain than a human does.',
  },
  {
    id: 'congo-tetra',
    name: 'Congo Tetra',
    sciName: 'Phenacogrammus interruptus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Phenacogrammus_interruptus_1.jpg/1280px-Phenacogrammus_interruptus_1.jpg',
    region: 'congo',
    fact: 'Its scales scatter light into shifting bands of blue, gold and violet, and older males trail long feathered extensions from the middle of the tail.',
  },
  {
    id: 'african-butterflyfish',
    name: 'African Butterflyfish',
    sciName: 'Pantodon buchholzi',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Pantodon_buchholzi_K%C3%B6ln_Zoo_31122014_1.jpg/1280px-Pantodon_buchholzi_K%C3%B6ln_Zoo_31122014_1.jpg',
    region: 'congo',
    fact: 'Hangs motionless at the surface watching upward for insects, and can burst clear of the water on its huge wing-like pectoral fins.',
  },

  {
    id: 'six-barred-distichodus',
    name: 'Six-barred Distichodus',
    sciName: 'Distichodus sexfasciatus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Distichodontidae_-_Distichodus_sexfasciatus.JPG/1280px-Distichodontidae_-_Distichodus_sexfasciatus.JPG',
    region: 'congo',
    fact: 'The bold black bars that make young fish so striking fade as it grows, until a metre-long adult looks like an entirely different species.',
  },
  {
    id: 'ornate-bichir',
    name: 'Ornate Bichir',
    sciName: 'Polypterus ornatipinnis',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Polypterus_ornatipinnis_VA_01.jpg/1280px-Polypterus_ornatipinnis_VA_01.jpg',
    region: 'congo',
    fact: 'Breathes air through a pair of true lungs and will drown if it cannot reach the surface — a body plan little changed since before the dinosaurs.',
  },
  {
    id: 'reedfish',
    name: 'Reedfish',
    sciName: 'Erpetoichthys calabaricus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Erpetoichthys_calabaricus_01.jpg/1280px-Erpetoichthys_calabaricus_01.jpg',
    region: 'congo',
    fact: 'A snake-shaped survivor from before the dinosaurs, with a pair of working lungs; it drowns if it cannot reach the surface, and will crawl overland between pools.',
  },
  // ---- East African Rift Lakes ----
  {
    id: 'electric-yellow-cichlid',
    name: 'Electric Yellow Cichlid',
    sciName: 'Labidochromis caeruleus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Labidochromis_caeruleus_%28male%29.jpg/1280px-Labidochromis_caeruleus_%28male%29.jpg',
    region: 'rift-lakes',
    fact: 'A mouthbrooder: the female carries her eggs and fry in her mouth for around three weeks, not eating the whole time.',
  },
  {
    id: 'frontosa',
    name: 'Frontosa',
    sciName: 'Cyphotilapia frontosa',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Cyphotilapia_frontosa_-_Karlsruhe_Zoo_01.jpg/1280px-Cyphotilapia_frontosa_-_Karlsruhe_Zoo_01.jpg',
    region: 'rift-lakes',
    fact: 'Found only in Lake Tanganyika, hunting in deep water down to 100 m. Dominant males develop a large fatty hump above the eyes.',
  },
  {
    id: 'zebra-mbuna',
    name: 'Zebra Mbuna',
    sciName: 'Maylandia zebra',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Maylandia_zebra_B.jpg/1280px-Maylandia_zebra_B.jpg',
    region: 'rift-lakes',
    fact: 'One of the rock-dwelling "mbuna" of Lake Malawi, where hundreds of cichlid species evolved from a handful of ancestors in under a million years.',
  },
  {
    id: 'malawi-eyebiter',
    name: 'Malawi Eyebiter',
    sciName: 'Dimidiochromis compressiceps',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Cichlidae_-_Dimidiochromis_compressiceps.JPG/1280px-Cichlidae_-_Dimidiochromis_compressiceps.JPG',
    region: 'rift-lakes',
    fact: 'Hunts hanging head-down among reed stems, its blade-thin body almost invisible end-on until it strikes.',
  },

  {
    id: 'white-spotted-cichlid',
    name: 'White-spotted Cichlid',
    sciName: 'Tropheus duboisi',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/%E7%8F%8D%E7%8F%A0%E8%9D%B4%E8%9D%B6_Tropheus_duboisi_%28Marlier%2C_1959%29_-_panoramio.jpg/1280px-%E7%8F%8D%E7%8F%A0%E8%9D%B4%E8%9D%B6_Tropheus_duboisi_%28Marlier%2C_1959%29_-_panoramio.jpg',
    region: 'rift-lakes',
    fact: 'Juveniles are jet black under a scatter of brilliant white spots. The spots fade as the fish matures until nothing is left but a dark body crossed by one broad pale band.',
  },
  {
    id: 'cuckoo-catfish',
    name: 'Cuckoo Catfish',
    sciName: 'Synodontis multipunctatus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Synodontis-multipunctatus.jpg/1280px-Synodontis-multipunctatus.jpg',
    region: 'rift-lakes',
    fact: 'Slips its own eggs into a mouthbrooding cichlid\'s clutch as she gathers them up. The catfish hatch first and eat her young from inside her mouth.',
  },
  // ---- Coral Triangle ----
  {
    id: 'mandarinfish',
    name: 'Mandarinfish',
    sciName: 'Synchiropus splendidus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Synchiropus_splendidus_2_Luc_Viatour.jpg/1280px-Synchiropus_splendidus_2_Luc_Viatour.jpg',
    region: 'coral-triangle',
    fact: 'One of only two animals known to make blue with cellular pigment rather than structural colour. It has no scales — just toxic, foul-smelling slime.',
  },
  {
    id: 'clown-anemonefish',
    name: 'Clown Anemonefish',
    sciName: 'Amphiprion ocellaris',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Amphiprion_ocellaris_%28Clown_anemonefish%29_by_Nick_Hobgood.jpg/1280px-Amphiprion_ocellaris_%28Clown_anemonefish%29_by_Nick_Hobgood.jpg',
    region: 'coral-triangle',
    fact: 'Coats itself in mucus to live unstung among anemone tentacles. Every one is born male; when the resident female dies, her mate becomes female.',
  },
  {
    id: 'banggai-cardinalfish',
    name: 'Banggai Cardinalfish',
    sciName: 'Pterapogon kauderni',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Banggai-Kardinalbarsch_Pterapogon_kauderni.jpg/1280px-Banggai-Kardinalbarsch_Pterapogon_kauderni.jpg',
    region: 'coral-triangle',
    fact: 'Wild populations live only around Indonesia’s Banggai Islands — a range smaller than most cities. Males brood the eggs, then the hatched young, in their mouths.',
  },
  {
    id: 'ribbon-eel',
    name: 'Ribbon Eel',
    sciName: 'Rhinomuraena quaesita',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Anguila_list%C3%B3n_azul_%28Rhinomuraena_quaesita%29%2C_Anilao%2C_Filipinas%2C_2023-08-23%2C_DD_60.jpg/1280px-Anguila_list%C3%B3n_azul_%28Rhinomuraena_quaesita%29%2C_Anilao%2C_Filipinas%2C_2023-08-23%2C_DD_60.jpg',
    region: 'coral-triangle',
    fact: 'Every one starts black as a juvenile, turns blue and yellow as a male, then yellow as a female — the same fish in three different liveries.',
  },

  {
    id: 'pygmy-seahorse',
    name: 'Pygmy Seahorse',
    sciName: 'Hippocampus bargibanti',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Pygmy_seahorse_%28Hippocampus_bargibanti%29_%2816245385685%29.jpg/1280px-Pygmy_seahorse_%28Hippocampus_bargibanti%29_%2816245385685%29.jpg',
    region: 'coral-triangle',
    fact: 'Under two centimetres long and so exactly matched to the gorgonian coral it grips that science only noticed it in 1969, when a collected sea fan reached the laboratory with seahorses still aboard.',
  },
  {
    id: 'harlequin-sweetlips',
    name: 'Harlequin Sweetlips',
    sciName: 'Plectorhinchus chaetodonoides',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Harlequin_sweetlips_%28Plectorhinchus_chaetodonoides%29_%2840815006613%29.jpg/1280px-Harlequin_sweetlips_%28Plectorhinchus_chaetodonoides%29_%2840815006613%29.jpg',
    region: 'coral-triangle',
    fact: 'The juvenile is blotched brown and white and swims in a lurching, tumbling motion that mimics a toxic flatworm. The adult drops the act and turns pale under dark spots.',
  },
  {
    id: 'tasselled-wobbegong',
    name: 'Tasselled Wobbegong',
    sciName: 'Eucrossorhinus dasypogon',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Tasselled_wobbegong_%28Eucrossorhinus_dasypogon%29.jpg/1280px-Tasselled_wobbegong_%28Eucrossorhinus_dasypogon%29.jpg',
    region: 'coral-triangle',
    fact: 'The fringe of branched skin flaps around its head breaks up its outline so completely that fish will swim to within a mouth-length of it.',
  },
  {
    id: 'psychedelic-frogfish',
    name: 'Psychedelic Frogfish',
    sciName: 'Histiophryne psychedelica',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Psychedelic_frogfish_juvenile.jpg/1280px-Psychedelic_frogfish_juvenile.jpg',
    region: 'coral-triangle',
    fact: 'Every fish wears a different maze of white stripes, and it gets about by bouncing off the bottom, jetting water from its gills to shove itself along.',
  },
  {
    id: 'warty-frogfish',
    name: 'Warty Frogfish',
    sciName: 'Antennarius maculatus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Pez_sapo_payaso_%28Antennarius_maculatus%29%2C_Anilao%2C_Filipinas%2C_2023-08-24%2C_DD_39.jpg/1280px-Pez_sapo_payaso_%28Antennarius_maculatus%29%2C_Anilao%2C_Filipinas%2C_2023-08-24%2C_DD_39.jpg',
    region: 'coral-triangle',
    fact: 'Does not swim so much as walk, on pectoral fins jointed like elbows, and swallows prey in about six milliseconds — one of the fastest strikes measured in any vertebrate.',
  },
  {
    id: 'clown-triggerfish',
    name: 'Clown Triggerfish',
    sciName: 'Balistoides conspicillum',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Balistoides_conspicillum_01.jpg/1280px-Balistoides_conspicillum_01.jpg',
    region: 'coral-triangle',
    fact: 'The white blotches sit only on its underside and the yellow saddle only on its back, so from below and from above it reads as two different fish.',
  },
  {
    id: 'pyjama-cardinalfish',
    name: 'Pyjama Cardinalfish',
    sciName: 'Sphaeramia nematoptera',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Pajama_cardinalfish_%28Sphaeramia_nematoptera%29_%2844065265714%29.jpg/1280px-Pajama_cardinalfish_%28Sphaeramia_nematoptera%29_%2844065265714%29.jpg',
    region: 'coral-triangle',
    fact: 'The male takes the whole clutch into his mouth and holds it there until the eggs hatch, going without food for the week or so it takes.',
  },
  {
    id: 'bluegirdled-angelfish',
    name: 'Blue-girdled Angelfish',
    sciName: 'Pomacanthus navarchus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Bluegirdled_angelfish_%28Pomacanthus_navarchus%29_%2846982094954%29.jpg/1280px-Bluegirdled_angelfish_%28Pomacanthus_navarchus%29_%2846982094954%29.jpg',
    region: 'coral-triangle',
    fact: 'Starts life black with concentric blue rings and looks like an entirely different species until the orange saddle grows in.',
  },
  // ---- Northern Australia ----
  {
    id: 'barramundi',
    name: 'Barramundi',
    sciName: 'Lates calcarifer',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Lates_calcarifer%2C_2014-09-19a.jpg/1280px-Lates_calcarifer%2C_2014-09-19a.jpg',
    region: 'northern-australia',
    fact: 'Nearly all barramundi mature as males and change to female around five years old, so the biggest fish are almost always female.',
  },
  {
    id: 'australian-lungfish',
    name: 'Australian Lungfish',
    sciName: 'Neoceratodus forsteri',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Neoceratodus_forsteri_Nagoya1.jpg/1280px-Neoceratodus_forsteri_Nagoya1.jpg',
    region: 'northern-australia',
    fact: 'Native to just a few Queensland rivers, and barely changed in 100 million years. It has a single true lung and can gulp air when its pool goes stagnant.',
  },
  {
    id: 'potato-cod',
    name: 'Potato Cod',
    sciName: 'Epinephelus tukula',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Serranidae_Epinephelus_tukula_1.jpg/1280px-Serranidae_Epinephelus_tukula_1.jpg',
    region: 'northern-australia',
    fact: 'Named for the potato-sized blotches along its flanks. At the Great Barrier Reef’s Cod Hole they grow to two metres and are famously unbothered by divers.',
  },
  {
    id: 'gulf-saratoga',
    name: 'Gulf Saratoga',
    sciName: 'Scleropages jardinii',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Scleropages_jardinii_043.JPG/1280px-Scleropages_jardinii_043.JPG',
    region: 'northern-australia',
    fact: 'A mouthbrooder that carries its young for weeks, and an ancient "bonytongue" — its lineage was swimming before Australia broke from Gondwana.',
  },

  {
    id: 'nurseryfish',
    name: 'Nurseryfish',
    sciName: 'Kurtus gulliveri',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Kurtus_gulliveri.jpg/1280px-Kurtus_gulliveri.jpg',
    region: 'northern-australia',
    fact: 'The male grows a bony hook on his forehead and carries the whole egg cluster hanging from it until the young hatch.',
  },
  {
    id: 'eastern-rainbowfish',
    name: 'Eastern Rainbowfish',
    sciName: 'Melanotaenia splendida',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Melanotaenia_splendida_splendida_188164829.jpg/1280px-Melanotaenia_splendida_splendida_188164829.jpg',
    region: 'northern-australia',
    fact: 'Colour is a morning affair — males flush red and gold at first light to display, then fade back as the day goes on.',
  },
  {
    id: 'epaulette-shark',
    name: 'Epaulette Shark',
    sciName: 'Hemiscyllium ocellatum',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Epaulette_shark_camden2.jpg/1280px-Epaulette_shark_camden2.jpg',
    region: 'northern-australia',
    fact: 'Walks on its fins from one tide pool to the next across dry reef, and survives hours of almost no oxygen by shutting down parts of its own brain.',
  },
  {
    id: 'barrier-reef-anemonefish',
    name: 'Barrier Reef Anemonefish',
    sciName: 'Amphiprion akindynos',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Amphiprion_akindynos.jpg/1280px-Amphiprion_akindynos.jpg',
    region: 'northern-australia',
    fact: 'Every one of them is born male; when the resident female dies the dominant male becomes her, and the next fish in the queue moves up.',
  },
  {
    id: 'coral-trout',
    name: 'Coral Trout',
    sciName: 'Plectropomus leopardus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Plectropomus_leopardus.jpg/1280px-Plectropomus_leopardus.jpg',
    region: 'northern-australia',
    fact: 'Hunts in partnership with moray eels and octopuses, recruiting one with a headstand and a shimmy to flush prey out of holes it cannot reach itself.',
  },
  // ---- Southern Ocean ----
  {
    id: 'antarctic-toothfish',
    name: 'Antarctic Toothfish',
    sciName: 'Dissostichus mawsoni',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Dissostichus_mawsoni_NOAA_Fish8711.jpg/1280px-Dissostichus_mawsoni_NOAA_Fish8711.jpg',
    region: 'southern-ocean',
    fact: 'Its blood carries antifreeze glycoproteins that stop ice crystals growing, letting it live in water below the normal freezing point.',
  },
  {
    id: 'blackfin-icefish',
    name: 'Blackfin Icefish',
    sciName: 'Chaenocephalus aceratus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/C._aceratus.jpg/1280px-C._aceratus.jpg',
    region: 'southern-ocean',
    fact: 'The only known vertebrates with no haemoglobin — their blood runs clear and carries oxygen dissolved straight into the plasma.',
  },
  {
    id: 'emerald-rockcod',
    name: 'Emerald Rockcod',
    sciName: 'Trematomus bernacchii',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Emerald_rockcod%2C_Trematomus_bernacchii.jpg/1280px-Emerald_rockcod%2C_Trematomus_bernacchii.jpg',
    region: 'southern-ocean',
    fact: 'Rests on the seabed under the sea ice at about −1.9 °C, kept liquid by antifreeze proteins that bind to ice crystals before they can spread.',
  },
  {
    id: 'ocellated-icefish',
    name: 'Ocellated Icefish',
    sciName: 'Chionodraco rastrospinosus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Chionodraco_rastrospinosus.jpg/1280px-Chionodraco_rastrospinosus.jpg',
    region: 'southern-ocean',
    fact: 'White-blooded like its relatives, and named for the dark ringed spot on the first dorsal fin. It hangs almost motionless in the water to spend as little oxygen as it can.',
  },

  // ---- Arctic Ocean ----
  {
    id: 'greenland-shark',
    name: 'Greenland Shark',
    sciName: 'Somniosus microcephalus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Greenland_shark_profile.jpg/1280px-Greenland_shark_profile.jpg',
    region: 'arctic',
    fact: 'The longest-lived vertebrate known: radiocarbon dating of the eye lens puts some individuals near 400 years old, and they mature at about 150.',
  },
  {
    id: 'polar-cod',
    name: 'Polar Cod',
    sciName: 'Boreogadus saida',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Boreogadus_saida_Kaiyukan.jpg/1280px-Boreogadus_saida_Kaiyukan.jpg',
    region: 'arctic',
    fact: 'Lives in the brine channels inside sea ice, kept liquid by antifreeze proteins. Almost every Arctic seal and seabird depends on it.',
  },
  {
    id: 'capelin',
    name: 'Capelin',
    sciName: 'Mallotus villosus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Mallotus_villosus.jpg/1280px-Mallotus_villosus.jpg',
    region: 'arctic',
    fact: 'Spawns by hurling itself onto gravel beaches in such numbers that the shoreline turns silver, then mostly dies where it lands.',
  },
  {
    id: 'arctic-char',
    name: 'Arctic Char',
    sciName: 'Salvelinus alpinus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Salvelinus_alpinus_Kaiyukan.jpg/1280px-Salvelinus_alpinus_Kaiyukan.jpg',
    region: 'arctic',
    fact: 'The northernmost freshwater fish on Earth, living in lakes that stay frozen most of the year.',
  },

  {
    id: 'arctic-grayling',
    name: 'Arctic Grayling',
    sciName: 'Thymallus arcticus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Underwater_Arctic_Grayling.jpg/1280px-Underwater_Arctic_Grayling.jpg',
    region: 'arctic',
    fact: 'The oversized dorsal fin folds flat while swimming and opens like a spotted, purple-edged sail when the fish displays or holds its place in the current.',
  },
  // ---- Great Lakes ----
  {
    id: 'lake-sturgeon',
    name: 'Lake Sturgeon',
    sciName: 'Acipenser fulvescens',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Juvenile_Acipenser_fulvescens_black_background.jpg/1280px-Juvenile_Acipenser_fulvescens_black_background.jpg',
    region: 'great-lakes',
    fact: 'Armoured with bony plates instead of scales and little changed in 150 million years. Females may not spawn until they are twenty-five.',
  },
  {
    id: 'muskellunge',
    name: 'Muskellunge',
    sciName: 'Esox masquinongy',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Esox_masquinongy_%28muskellunge%29_1.jpg/1280px-Esox_masquinongy_%28muskellunge%29_1.jpg',
    region: 'great-lakes',
    fact: 'Nicknamed "the fish of ten thousand casts" for how rarely it strikes. It ambushes from weed beds and takes prey a third of its own length.',
  },
  {
    id: 'lake-trout',
    name: 'Lake Trout',
    sciName: 'Salvelinus namaycush',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Lake_trout_fishes_salvelinus_namaycush.jpg/1280px-Lake_trout_fishes_salvelinus_namaycush.jpg',
    region: 'great-lakes',
    fact: 'A cold, deep-water char that grows slowly and lives for decades. Sea lamprey arriving through the shipping canals nearly wiped it out.',
  },
  {
    id: 'bluegill',
    name: 'Bluegill',
    sciName: 'Lepomis macrochirus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Bluegill_%28Lepomis_macrochirus%29_black_background.jpg/1280px-Bluegill_%28Lepomis_macrochirus%29_black_background.jpg',
    region: 'great-lakes',
    fact: 'Males scrape shallow nests in colonies and fan them constantly; smaller males mimic females to sneak into a guarded nest and spawn.',
  },

  {
    id: 'walleye',
    name: 'Walleye',
    sciName: 'Sander vitreus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Sander_vitreus.jpg/1280px-Sander_vitreus.jpg',
    region: 'great-lakes',
    fact: 'A mirror-like layer behind the retina gathers what little light is left at dusk, so it hunts in the gloom that leaves its prey effectively blind.',
  },
  {
    id: 'yellow-perch',
    name: 'Yellow Perch',
    sciName: 'Perca flavescens',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Yellow_Perch_%28Perca_flavescens%29.jpg/1280px-Yellow_Perch_%28Perca_flavescens%29.jpg',
    region: 'great-lakes',
    fact: 'Hunts in packs that herd smaller fish against the shallows, and the dark bars down its sides break its outline up against weed.',
  },
  {
    id: 'longnose-gar',
    name: 'Longnose Gar',
    sciName: 'Lepisosteus osseus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Longnose_Gar_%28Lepisosteus_osseus%29.jpg/1280px-Longnose_Gar_%28Lepisosteus_osseus%29.jpg',
    region: 'great-lakes',
    fact: 'Armoured in interlocking enamel-hard scales and able to gulp air at the surface, it survives water that suffocates other fish. Its eggs are poisonous to whatever eats them.',
  },
  {
    id: 'bowfin',
    name: 'Bowfin',
    sciName: 'Amia calva',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Bowfin_01.jpg/1280px-Bowfin_01.jpg',
    region: 'great-lakes',
    fact: 'The last survivor of a family that has been around for 150 million years; it gulps air from a swim bladder plumbed like a lung and can outlast a pond going stagnant.',
  },
  // ---- Sea of Japan ----
  {
    id: 'sakhalin-taimen',
    name: 'Sakhalin Taimen',
    sciName: 'Parahucho perryi',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Hucho_perryi_Yamano1.jpg/1280px-Hucho_perryi_Yamano1.jpg',
    region: 'sea-of-japan',
    fact: 'Passes a metre in length, lives thirty years and turns deep red to spawn. So few rivers still hold it that anglers call it the phantom fish.',
  },
  {
    id: 'red-seabream',
    name: 'Red Seabream',
    sciName: 'Pagrus major',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Pagrus_major_ioworld.jpg/1280px-Pagrus_major_ioworld.jpg',
    region: 'sea-of-japan',
    fact: 'Called tai, and served at weddings and New Year because the word rides inside "medetai" — auspicious.',
  },
  {
    id: 'torafugu',
    name: 'Torafugu',
    sciName: 'Takifugu rubripes',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Takifugu_rubripes_AQUAS.jpg/1280px-Takifugu_rubripes_AQUAS.jpg',
    region: 'sea-of-japan',
    fact: 'Carries tetrodotoxin far deadlier than cyanide, which it does not make itself but accumulates from the bacteria in its diet.',
  },
  {
    id: 'pacific-saury',
    name: 'Pacific Saury',
    sciName: 'Cololabis saira',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Cololabis_saira_in_a_tank.jpg/1280px-Cololabis_saira_in_a_tank.jpg',
    region: 'sea-of-japan',
    fact: 'A slender surface fish with no true stomach, so it digests continuously — and an autumn staple grilled whole as sanma.',
  },

  {
    id: 'ayu',
    name: 'Ayu',
    sciName: 'Plecoglossus altivelis',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Plecoglossus_altivelis_Totto.jpg/1280px-Plecoglossus_altivelis_Totto.jpg',
    region: 'sea-of-japan',
    fact: 'Scrapes algae off river stones and leaves oval grazing marks behind; its flesh smells of melon, and almost every fish lives just one year.',
  },
  {
    id: 'sailfin-sandfish',
    name: 'Sailfin Sandfish',
    sciName: 'Arctoscopus japonicus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Arctoscopus_japonicus_Umigatari.png/1280px-Arctoscopus_japonicus_Umigatari.png.jpg',
    region: 'sea-of-japan',
    fact: 'Has no scales at all. It spawns during the winter storms, crowding into the shallows in numbers that leave the surf thick with eggs.',
  },
  {
    id: 'japanese-bullhead-shark',
    name: 'Japanese Bullhead Shark',
    sciName: 'Heterodontus japonicus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Japanese_bullhead_shark_Suma_Aqualife_Park.jpg/1280px-Japanese_bullhead_shark_Suma_Aqualife_Park.jpg',
    region: 'sea-of-japan',
    fact: 'Grinds shellfish with flat crushing back teeth, and lays spiral egg cases that it screws into rock crevices like a corkscrew.',
  },
  {
    id: 'cherry-anthias',
    name: 'Cherry Anthias',
    sciName: 'Sacura margaritacea',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Japan_fish%2C_Sakuradai_%28Sacura_margaritacea%29_%2815770306721%29.jpg/1280px-Japan_fish%2C_Sakuradai_%28Sacura_margaritacea%29_%2815770306721%29.jpg',
    region: 'sea-of-japan',
    fact: 'Named for the cherry blossom: males are crimson flecked with white, while the females they grew out of stay a plain orange.',
  },
  // ---- Mekong Basin ----
  {
    id: 'mekong-giant-catfish',
    name: 'Mekong Giant Catfish',
    sciName: 'Pangasianodon gigas',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Mekong_giant_catfish.jpg/1280px-Mekong_giant_catfish.jpg',
    region: 'mekong',
    fact: 'One of the largest freshwater fish ever recorded, near three metres. Adults lose their teeth and barbels and live entirely on algae.',
  },
  {
    id: 'siamese-fighting-fish',
    name: 'Siamese Fighting Fish',
    sciName: 'Betta splendens',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Bojownik_syjamski.jpg/1280px-Bojownik_syjamski.jpg',
    region: 'mekong',
    fact: 'Breathes air through a labyrinth organ, so it survives in rice paddies too stagnant for other fish. The male builds a nest of bubbles.',
  },
  {
    id: 'giant-freshwater-stingray',
    name: 'Giant Freshwater Stingray',
    sciName: 'Urogymnus polylepis',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Urogymnus_polylepis_at_Itabashi_Botanical_Garden.png/1280px-Urogymnus_polylepis_at_Itabashi_Botanical_Garden.png.jpg',
    region: 'mekong',
    fact: 'Can span two metres across and carries a serrated spine longer than a hand, used only in defence against river-bottom predators.',
  },
  {
    id: 'giant-snakehead',
    name: 'Giant Snakehead',
    sciName: 'Channa micropeltes',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Channa_micropeltes_-_T%C3%AAte_de_serpent_-_Aqua_Porte_Dor%C3%A9e_01.JPG/1280px-Channa_micropeltes_-_T%C3%AAte_de_serpent_-_Aqua_Porte_Dor%C3%A9e_01.JPG',
    region: 'mekong',
    fact: 'Breathes air and can cross damp ground between pools. Both parents guard the shoal of red fry and will drive off anything that comes near.',
  },

  {
    id: 'giant-barb',
    name: 'Giant Barb',
    sciName: 'Catlocarpio siamensis',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Siamese_giant_carp_%28Catlocarpio_siamensis%29_2.jpg/1280px-Siamese_giant_carp_%28Catlocarpio_siamensis%29_2.jpg',
    region: 'mekong',
    fact: 'The largest carp in the world at up to three metres, and it lives on algae, plankton and fruit dropped from flooded riverbanks.',
  },
  {
    id: 'clown-featherback',
    name: 'Clown Featherback',
    sciName: 'Chitala ornata',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Adult_Clown_featherback_in_aquarium.jpg/1280px-Adult_Clown_featherback_in_aquarium.jpg',
    region: 'mekong',
    fact: 'Holds its body rigid and swims by rippling one long unbroken fin along its underside, forwards or backwards with equal ease.',
  },
  {
    id: 'giant-mudskipper',
    name: 'Giant Mudskipper',
    sciName: 'Periophthalmodon schlosseri',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Giant_Mudskipper_%28Periophthalmodon_schlosseri%29.jpg/1280px-Giant_Mudskipper_%28Periophthalmodon_schlosseri%29.jpg',
    region: 'mekong',
    fact: 'Spends most of the tide out of the water, breathing through its skin and a mouthful of held water, and digs burrows it gulps air down into for its eggs.',
  },
  {
    id: 'glass-catfish',
    name: 'Glass Catfish',
    sciName: 'Kryptopterus vitreolus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Kryptopterus_vitreolus_%28Cologne_Zoo%29.jpg/1280px-Kryptopterus_vitreolus_%28Cologne_Zoo%29.jpg',
    region: 'mekong',
    fact: 'So transparent that its spine and the silvery sac around its organs are the only parts you can see; the rest of the fish is a suggestion.',
  },
  // ---- New Zealand ----
  {
    id: 'australasian-snapper',
    name: 'Australasian Snapper',
    sciName: 'Chrysophrys auratus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Pagrus_auratus_%28Forster%2C_1801%29_%28AM_MA36682-1%29.jpg/1280px-Pagrus_auratus_%28Forster%2C_1801%29_%28AM_MA36682-1%29.jpg',
    region: 'new-zealand',
    fact: 'Older fish develop a pronounced bony hump on the forehead and snout, and can live past sixty years.',
  },
  {
    id: 'longfin-eel',
    name: 'New Zealand Longfin Eel',
    sciName: 'Anguilla dieffenbachii',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Anguilla_dieffenbachii_62220829.jpg/1280px-Anguilla_dieffenbachii_62220829.jpg',
    region: 'new-zealand',
    fact: 'Spends up to a century in fresh water, then swims thousands of kilometres to spawn near Tonga once, and dies.',
  },
  {
    id: 'blue-cod',
    name: 'Blue Cod',
    sciName: 'Parapercis colias',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Blue_Cod_in_Milford_Sound.jpg/1280px-Blue_Cod_in_Milford_Sound.jpg',
    region: 'new-zealand',
    fact: 'Found nowhere but New Zealand. Every one begins life female, and the largest turn male and take a territory.',
  },
  {
    id: 'kahawai',
    name: 'Kahawai',
    sciName: 'Arripis trutta',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Arripis_trutta_NZ.jpg/1280px-Arripis_trutta_NZ.jpg',
    region: 'new-zealand',
    fact: 'Hunts in fast surface shoals that drive baitfish into a boil, with seabirds working the same school from above.',
  },
  {
    id: 'red-moki',
    name: 'Red Moki',
    sciName: 'Cheilodactylus spectabilis',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Red_Moki_%28Cheilodactylus_spectabilis%29.jpg/1280px-Red_Moki_%28Cheilodactylus_spectabilis%29.jpg',
    region: 'new-zealand',
    fact: 'Sifts invertebrates out of mouthfuls of sand with thick fleshy lips, and holds the same patch of reef for decades — some are over sixty years old.',
  },
  {
    id: 'red-gurnard',
    name: 'Red Gurnard',
    sciName: 'Chelidonichthys kumu',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Chelidonichthys_kumu.jpg/1280px-Chelidonichthys_kumu.jpg',
    region: 'new-zealand',
    fact: 'Walks the seabed on three stiff finger-like rays split off from each pectoral fin, feeling for buried prey, and grunts audibly by drumming its swim bladder.',
  },
  {
    id: 'draughtsboard-shark',
    name: 'Draughtsboard Shark',
    sciName: 'Cephaloscyllium isabellum',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Carpetshark.jpg/1280px-Carpetshark.jpg',
    region: 'new-zealand',
    fact: 'Swallows water until it swells to twice its size and wedges itself immovably into a crevice — and if it is lifted out, it gulps air and barks.',
  },
];
